Repository PennyLaneAI/pennylane, pull requests merged in 2019-11, with the labels that each got.

#357 Add primitives for vqe submodule
  pennylane/__init__.py
  pennylane/decorator.py
  pennylane/interfaces/tf.py
  pennylane/interfaces/torch.py
  pennylane/measure.py
  pennylane/qnode.py
  pennylane/vqe/__init__.py
  pennylane/vqe/vqe.py
  tests/conftest.py
  tests/test_device.py
  tests/test_tf.py
  tests/test_torch.py
  tests/test_vqe.py
Labels: enhancement, review-ready

#380 Tensor network simulator
  pennylane/plugins/__init__.py
  pennylane/plugins/expt_tensornet.py
  requirements.txt
  setup.py
  tests/conftest.py
  tests/test_tensornet.py
Labels: enhancement, plugins, review-ready

#388 Adds an operation recorder for inspecting templates
  .github/CHANGELOG.md
  pennylane/utils.py
  tests/test_utils.py
Labels: core, review-ready, tests

#354 Qnode refactor, part 2.
  .github/CHANGELOG.md
  Makefile
  doc/code/qml_qnode_new.rst
  doc/code/qml_utils.rst
  doc/index.rst
  doc/introduction/circuits.rst
  doc/xanadu_theme/footer.html
  pennylane/_device.py
  pennylane/circuit_graph.py
  pennylane/operation.py
  pennylane/plugins/default_gaussian.py
  pennylane/qnode.py
  pennylane/qnode_new/__init__.py
  pennylane/qnode_new/qnode.py
  tests/conftest.py
  tests/qnode_new/test_base_qnode.py
  tests/qnode_new/test_qnode_metric_tensor.py
  tests/test_operation.py
  tests/test_qnode.py
Labels: core, enhancement, review-ready, tests

#399 Update examples/pennylane_run_variational_classifier.py.
  examples/pennylane_run_variational_classifier.py
Labels: documentation

#400 Adding 'Raises' sections to docstrings throughout PL
  pennylane/_device.py
  pennylane/circuit_graph.py
  pennylane/measure.py
  pennylane/operation.py
  pennylane/plugins/default_qubit.py
  pennylane/qnode.py
  pennylane/qnode_new/qnode.py
  pennylane/templates/embeddings.py
  pennylane/templates/layers.py
  pennylane/utils.py
  pennylane/variable.py
Labels: documentation, in review

#406 Adding variance to tensornetwork simulator
  pennylane/plugins/expt_tensornet.py
  tests/test_tensornet.py
Labels: review-ready

#404 Bug Fix (#393): `qml.about()` function broken with latest `pip` update
  .github/CHANGELOG.md
  pennylane/about.py
  tests/test_about.py
Labels: bug

#396 Adds the U1, U2, U3, and Toffoli gates to PennyLane core.
  pennylane/operation.py
  pennylane/ops/qubit.py
  pennylane/plugins/default_qubit.py
  pennylane/qnode.py
  pennylane/qnode_new/qnode.py
  tests/qnode_new/test_base_qnode.py
  tests/test_circuit_graph.py
  tests/test_default_gaussian.py
  tests/test_default_qubit.py
  tests/test_operation.py
  tests/test_qnode.py
  tests/test_quantum_gradients.py
  tests/test_tensornet.py
Labels: core, review-ready

#410 Refactor getting the operator matrix into separate method
  pennylane/plugins/default_qubit.py
Labels: code quality

#377 Add inv() method to the Operation class
  .github/CHANGELOG.md
  pennylane/_device.py
  pennylane/operation.py
  pennylane/plugins/default_qubit.py
  tests/test_default_qubit.py
  tests/test_device.py
  tests/test_operation.py
Labels: enhancement, review-ready

#405 Fix setup.py
  setup.py
Labels: bug, core, review-ready

#398 QNode refactor, part 3.
  .github/CHANGELOG.md
  doc/code/qml_variable.rst
  pennylane/operation.py
  pennylane/qnode_new/__init__.py
  pennylane/qnode_new/autograd.py
  pennylane/qnode_new/jacobian.py
  pennylane/qnode_new/qnode.py
  pennylane/utils.py
  pennylane/variable.py
  tests/qnode_new/test_qnode_autograd.py
  tests/qnode_new/test_qnode_base.py
  tests/qnode_new/test_qnode_jacobian.py
Labels: WIP, core, enhancement, tests

#336 Add state preparation
  .github/CHANGELOG.md
  doc/code/templates/state_preparations.rst
  pennylane/templates/embeddings.py
  pennylane/templates/state_preparations.py
  tests/test_templates_embeddings.py
  tests/test_templates_state_preparations.py
Labels: review-ready, templates

#411 Fix class docstrings in documentation
  doc/_templates/autosummary/class.rst
  doc/_templates/autosummary_core/base.rst
  doc/_templates/autosummary_core/class.rst
  doc/_templates/autosummary_core/module.rst
  doc/code/qml_qnode_new.rst
  doc/conf.py
  doc/index.rst
  doc/xanadu_theme/layout.html
  doc/xanadu_theme/static/xanadu.css_t
  pennylane/operation.py
Labels: documentation, review-ready

#414 Add decompositions for state preps
  .github/CHANGELOG.md
  pennylane/operation.py
  pennylane/ops/qubit.py
  tests/test_default_gaussian.py
  tests/test_operation.py
Labels: core, review-ready

#415 Creates QubitQNode, CVQnode out of JacobianQNode
  .github/CHANGELOG.md
  pennylane/circuit_graph.py
  pennylane/interfaces/autograd.py
  pennylane/operation.py
  pennylane/ops/__init__.py
  pennylane/qnode_new/__init__.py
  pennylane/qnode_new/autograd.py
  pennylane/qnode_new/cv.py
  pennylane/qnode_new/jacobian.py
  pennylane/qnode_new/qnode.py
  pennylane/qnode_new/qubit.py
  pennylane/utils.py
  tests/qnode_new/test_interfaces_autograd.py
  tests/qnode_new/test_qnode_base.py
  tests/qnode_new/test_qnode_cv.py
  tests/qnode_new/test_qnode_jacobian.py
  tests/qnode_new/test_qnode_metric_tensor.py
  tests/qnode_new/test_qnode_qubit.py
  tests/test_quantum_gradients.py
Labels: autodiff, review-ready

#346 Issue #286 default qubit state prep. consistency with other plugins
  .github/CHANGELOG.md
  pennylane/ops/qubit.py
  pennylane/plugins/default_qubit.py
  tests/test_default_qubit.py
Labels: enhancement, plugins, review-ready

#409 Refactor template tests
  .github/CHANGELOG.md
  pennylane/templates/layers.py
  tests/conftest.py
  tests/test_templates.py
  tests/test_templates_layers.py
Labels: review-ready, templates

#413 Make layer private
  .github/CHANGELOG.md
  doc/introduction/templates.rst
  pennylane/init.py
  pennylane/templates/layers.py
  tests/test_init.py
  tests/test_templates.py
  tests/test_templates_layers.py
  tests/test_templates_subroutines.py
Labels: deprecation, documentation, review-ready, templates

#418 Qiskit QuantumCircuit to PennyLane template
  doc/code/qml.rst
  doc/introduction/circuits.rst
  pennylane/__init__.py
Labels: plugins, review-ready

#420 New-style QNode decorator
  pennylane/qnode_new/__init__.py
  pennylane/qnode_new/decorator.py
  pennylane/qnode_new/jacobian.py
  pennylane/qnode_new/qnode.py
  tests/qnode_new/test_qnode_decorator.py
Labels: core, review-ready

#412 Improve initialization functions
  .github/CHANGELOG.md
  doc/introduction/templates.rst
  pennylane/__init__.py
  pennylane/init.py
  pennylane/templates/layers.py
  tests/conftest.py
  tests/test_init.py
  tests/test_templates.py
  tests/test_vqe.py
Labels: review-ready, templates, tests

#425 Adds Device Jacobian QNode, that delegates gradient computations to the device, and renames QNode to BaseQNode
  .github/CHANGELOG.md
  pennylane/qnode_new/__init__.py
  pennylane/qnode_new/base.py
  pennylane/qnode_new/cv.py
  pennylane/qnode_new/decorator.py
  pennylane/qnode_new/device_jacobian.py
  pennylane/qnode_new/jacobian.py
  pennylane/qnode_new/qubit.py
  tests/qnode_new/test_interfaces_autograd.py
  tests/qnode_new/test_qnode_base.py
  tests/qnode_new/test_qnode_cv.py
  tests/qnode_new/test_qnode_decorator.py
  tests/qnode_new/test_qnode_jacobian.py
  tests/qnode_new/test_qnode_metric_tensor.py
  tests/qnode_new/test_qnode_qubit.py
Labels: core, enhancement, review-ready

#428 Replace pinv with np.linalg.solve in the QNG optimizer
  pennylane/optimize/qng.py
  tests/test_optimize_qng.py
Labels: enhancement, review-ready

#427 Add a `expt.tensornet.tf` device
  .github/CHANGELOG.md
  pennylane/_device.py
  pennylane/interfaces/autograd.py
  pennylane/interfaces/tf.py
  pennylane/interfaces/torch.py
  pennylane/plugins/expt_tensornet.py
  pennylane/plugins/expt_tensornet_tf.py
  pennylane/qnode_new/base.py
  pennylane/qnode_new/jacobian.py
  setup.py
  tests/test_tensornet_tf.py
Labels: plugins, review-ready

#419 Template checks and signatures
  .github/CHANGELOG.md
  pennylane/init.py
  pennylane/plugins/expt_tensornet.py
  pennylane/templates/__init__.py
  pennylane/templates/embeddings.py
  pennylane/templates/layers.py
  pennylane/templates/state_preparations.py
  pennylane/templates/subroutines.py
  pennylane/templates/utils.py
  tests/test_init.py
  tests/test_templates.py
  tests/test_templates_embeddings.py
  tests/test_templates_layers.py
  tests/test_templates_state_preparations.py
  tests/test_templates_subroutines.py
  tests/test_templates_utils.py
  tests/test_vqe.py
Labels: review-ready, templates

#429 Moved experimental features to the beta folder
  doc/code/qml_beta.rst
  doc/index.rst
  doc/requirements.txt
  pennylane/__init__.py
  pennylane/_device.py
  pennylane/_version.py
  pennylane/about.py
  pennylane/beta/__init__.py
  pennylane/beta/interfaces/__init__.py
  pennylane/beta/interfaces/autograd.py
  pennylane/beta/plugins/__init__.py
  pennylane/beta/plugins/expt_tensornet.py
  pennylane/beta/plugins/expt_tensornet_tf.py
  pennylane/beta/qnodes/__init__.py
  pennylane/beta/qnodes/base.py
  pennylane/beta/qnodes/cv.py
  pennylane/beta/qnodes/decorator.py
  pennylane/beta/qnodes/device_jacobian.py
  pennylane/beta/qnodes/jacobian.py
  pennylane/beta/qnodes/qubit.py
  pennylane/beta/vqe/__init__.py
  pennylane/beta/vqe/vqe.py
  pennylane/circuit_graph.py
  pennylane/configuration.py
  pennylane/decorator.py
  pennylane/interfaces/tf.py
  pennylane/interfaces/torch.py
  pennylane/ops/__init__.py
  pennylane/ops/qubit.py
  pennylane/optimize/__init__.py
  pennylane/optimize/adagrad.py
  pennylane/optimize/adam.py
  pennylane/optimize/gradient_descent.py
  pennylane/optimize/momentum.py
  pennylane/optimize/nesterov_momentum.py
  pennylane/optimize/qng.py
  pennylane/optimize/rms_prop.py
  pennylane/variable.py
  setup.py
  tests/beta/test_interfaces_autograd.py
  tests/beta/test_qnode_base.py
  tests/beta/test_qnode_cv.py
  tests/beta/test_qnode_decorator.py
  tests/beta/test_qnode_jacobian.py
  tests/beta/test_qnode_metric_tensor.py
  tests/beta/test_qnode_qubit.py
  tests/beta/test_tensornet.py
  tests/beta/test_tensornet_tf.py
  tests/beta/test_vqe.py
Labels: review-ready
