Repository PennyLaneAI/pennylane, pull requests merged in 2019-10, with the labels that each got.

#338 Documentation: Fix 2 typos in CV operations
  pennylane/ops/cv.py
Labels: bug, documentation

#337 Updates tf interface to be TensorFlow 2.0 compatible
  .github/CHANGELOG.md
  .travis.yml
  doc/code/interfaces/tf.rst
  pennylane/decorator.py
  pennylane/interfaces/__init__.py
  pennylane/interfaces/tf.py
  pennylane/qnode.py
  setup.py
  tests/conftest.py
  tests/test_about.py
  tests/test_tf.py
Labels: interface, review-ready

#332 (Tutorial) Barren plateaus in Quantum Neural Networks
  doc/tutorials.rst
  examples/figures/barren_plateaus/surface.png
  examples/pennylane_run_barren_plateaus.py
Labels: documentation, merge-ready

#310 Migrating the rest of the tests from unittest to pytest
  pennylane/operation.py
  pennylane/utils.py
  pennylane/variable.py
  tests/conftest.py
  tests/defaults.py
  tests/test_about.py
  tests/test_circuit_graph.py
  tests/test_default_gaussian.py
  tests/test_device.py
  tests/test_operation.py
  tests/test_ops.py
  tests/test_optimize.py
  tests/test_qnode.py
  tests/test_quantum_gradients.py
  tests/test_variable.py
Labels: code quality, help wanted, tests

#348 CRLF line endings normalized to LF.
  pennylane/optimize/qng.py
  tests/test_decorator.py
  tests/test_default_gaussian.py
  tests/test_optimize_qng.py
Labels: code quality, review-ready

#267 Tensor observables
  .github/CHANGELOG.md
  pennylane/_device.py
  pennylane/circuit_graph.py
  pennylane/measure.py
  pennylane/operation.py
  pennylane/plugins/default_qubit.py
  pennylane/qnode.py
  tests/test_default_qubit.py
  tests/test_device.py
  tests/test_measure.py
  tests/test_operation.py
  tests/test_tensor_measurements.py
Labels: core, plugins, review-ready

#344 CircuitGraph refactor
  doc/API/circuit_graph.rst
  doc/Makefile
  doc/index.rst
  pennylane/circuit_graph.py
  pennylane/operation.py
  pennylane/qnode.py
  pennylane/utils.py
  tests/test_circuit_graph.py
  tests/test_observable.py
  tests/test_qnode.py
  tests/test_quantum_gradients.py
Labels: enhancement, review-ready, tests

#319 Add the ising model examples to pennylane tutorials
  .github/CHANGELOG.md
  doc/tutorials.rst
  examples/figures/isingspins.png
  examples/figures/pytorch.png
  examples/pennylane_run_isingmodel_PyTorch.py
Labels: documentation, merge-ready, review-ready

#356 Remove unnecessary uses of autograd.numpy.
  pennylane/_device.py
  pennylane/operation.py
  pennylane/optimize/adagrad.py
  pennylane/optimize/adam.py
  pennylane/optimize/qng.py
  pennylane/optimize/rms_prop.py
  pennylane/qnode.py
  pennylane/utils.py
  tests/test_qnode.py
  tests/test_quantum_gradients.py
Labels: autodiff, review-ready, tests

#364 Make quick reference a top level section in docs
  doc/index.rst
  doc/introduction/configuration.rst
  doc/introduction/measurements.rst
  doc/introduction/operations.rst
  doc/introduction/optimizers.rst
  doc/introduction/pennylane.rst
  doc/introduction/reference.rst
  doc/introduction/templates.rst
Labels: documentation

#367 Rewriting the documentation landing page
  doc/index.rst
  doc/xanadu_theme/layout.html
  doc/xanadu_theme/static/xanadu.css_t
Labels: documentation, review-ready

#370 Refining interfaces page
  doc/introduction/interfaces.rst
Labels: documentation, merge-ready

#371 Fix scrolling behaviour on API links
  doc/xanadu_theme/layout.html
Labels: documentation, review-ready

#374 Changing deprecated abstract property definitions in _device.py
  .github/CHANGELOG.md
  pennylane/_device.py
Labels: code quality

#372 Updates measurements page
  doc/introduction/measurements.rst
Labels: documentation, review-ready

#355 Operator base class
  .github/CHANGELOG.md
  doc/code/qml.rst
  pennylane/operation.py
  tests/test_operation.py
Labels: code quality, merge-ready

#373 Adding missing modules to documentation API
  Makefile
  doc/_templates/autosummary/module.rst
  doc/code/qml.rst
  doc/code/qml_init.rst
  doc/code/qml_interfaces.rst
  doc/code/qml_operation.rst
  doc/code/qml_plugins.rst
  doc/code/qml_templates.rst
  doc/code/qml_templates_embeddings.rst
  doc/code/qml_templates_layers.rst
  doc/code/qml_utils.rst
  doc/code/qml_variable.rst
  doc/conf.py
  doc/index.rst
  doc/introduction/interfaces.rst
  doc/introduction/operations.rst
  doc/introduction/templates.rst
  doc/requirements.txt
  doc/xanadu_theme/layout.html
  pennylane/interfaces/__init__.py
  pennylane/operation.py
  pennylane/plugins/__init__.py
  pennylane/templates/__init__.py
  pennylane/variable.py
Labels: documentation, review-ready

#378 Adds a print_applied method to QNodes
  pennylane/decorator.py
  pennylane/interfaces/tf.py
  pennylane/interfaces/torch.py
  pennylane/qnode.py
  tests/test_qnode.py
Labels: enhancement, review-ready

#379 Updates the building a plugin guide
  doc/development/plugins.rst
Labels: documentation, review-ready

#381 Adding interface gradient tests
  pennylane/interfaces/tf.py
  tests/test_qnode.py
  tests/test_tf.py
  tests/test_torch.py
Labels: bug, merge-ready, tests

#382 Updates the development guide
  doc/development/docs.rst
  doc/development/example_module_autosummary.txt
  doc/development/example_module_rst.txt
  doc/development/example_package_rst.txt
  doc/development/guide.rst
  doc/development/plugins.rst
  doc/index.rst
Labels: documentation, review-ready

#385 Fixes bug to allow interface tests to work without TF/PyTorch installed
  tests/test_tf.py
  tests/test_torch.py
Labels: bug, tests

#387 Light polishing of the introduction section
  doc/_static/intro.png
  doc/_static/intro.svg
  doc/_static/jigsaw.png
  doc/_static/jigsaw.svg
  doc/index.rst
  doc/introduction/circuits.rst
  doc/introduction/operations.rst
  doc/introduction/pennylane.rst
  doc/introduction/templates.rst
Labels: documentation, review-ready
