Repository PennyLaneAI/pennylane, pull requests merged in 2019-04, with the labels that each got.

#179 Feature/variable division
  pennylane/variable.py
  tests/test_variable.py
Labels: review

#184 Explicit import for scipy.linalg.block_diag
  pennylane/ops/cv.py
Labels: review

#183 PyTest styled refactoring of tests.
  tests/test_ops.py
Labels: review

#185 PyTest refactoring of test_variable.py
  tests/test_variable.py
Labels: review

#189 PyTest refactoring of test_expval
  tests/test_expval.py
Labels: review, review-ready

#188 Remove logic which allows wires to be passed to operations as a positional argument (Issue 187)
  doc/research.rst
  pennylane/operation.py
  tests/test_expval.py
  tests/test_operation.py
  tests/test_ops.py
  tests/test_qnode.py
  tests/test_quantum_gradients.py
  tests/test_tfe.py
  tests/test_torch.py
Labels: merge-ready, review

#186 A minimal `pennylane.about` to generate information about pennylane installations
  pennylane/__init__.py
  pennylane/about.py
  tests/test_about.py
Labels: review, review-ready
