Repository PennyLaneAI/pennylane, pull requests merged in 2019-09, with the labels that each got.

#311 Rename the Quantum Natural Gradient optimizer
  pennylane/optimize/__init__.py
  pennylane/optimize/qng.py
  tests/test_optimize_qng.py
Labels: core, review-ready

#313 Add generators to the controlled rotation gates
  pennylane/ops/qubit.py
Labels: enhancement, review-ready

#315 Updates the changelog and version number for the 0.5.0 release
  .github/CHANGELOG.md
  doc/requirements.txt
  pennylane/_version.py
  pennylane/plugins/default_gaussian.py
  pennylane/plugins/default_qubit.py
Labels: review-ready

#274 Universal classifier with data-reuploading
  doc/tutorials.rst
  examples/figures/universal_bloch.png
  examples/figures/universal_circles.png
  examples/figures/universal_dnn.png
  examples/figures/universal_layers.png
  examples/pennylane_run_data_reuploading_classifier.py
Labels: documentation, in review

#289 Adds support for homodyne sampling in `default.gaussian`
  pennylane/plugins/default_gaussian.py
  tests/test_default_gaussian.py
Labels: CV, plugins

#309 Add embeddings page to key concepts section of documentation
  doc/concepts/concept_embeddings.rst
  doc/concepts/introduction.rst
  doc/concepts/quantum_nodes.rst
  doc/concepts/varcirc.rst
  doc/index.rst
  doc/references.bib
Labels: documentation, in review

#320 Fix punctuation in the data re-uploading tutorial
  examples/pennylane_run_data_reuploading_classifier.py
Labels: documentation

#321 Fix 2 typos in state preparation tutorial
  .github/CHANGELOG.md
  examples/pennylane_run_state_preparation.py
Labels: documentation

#312 Adds tutorial on quantum natural gradient optimization
  doc/tutorials.rst
  examples/figures/quantum_natural_gradient/qng1.png
  examples/figures/quantum_natural_gradient/qng2.png
  examples/figures/quantum_natural_gradient/qng3.png
  examples/figures/quantum_natural_gradient/qng4.png
  examples/figures/quantum_natural_gradient/qng5.png
  examples/figures/quantum_natural_gradient/qng7.png
  examples/figures/quantum_natural_gradient/qng8.png
  examples/figures/quantum_natural_gradient/qng_optimization.png
  examples/pennylane_run_quantum_natural_gradient.py
  pennylane/optimize/qng.py
Labels: documentation, review-ready

#317 Remove parameter from device.sample, make device.shots changeable and add an indicator for analytic mode
  .github/CHANGELOG.md
  default_config.toml
  doc/API/overview.rst
  pennylane/_device.py
  pennylane/configuration.py
  pennylane/measure.py
  pennylane/plugins/default_gaussian.py
  pennylane/plugins/default_qubit.py
  pennylane/qnode.py
  tests/test_configuration.py
  tests/test_default_gaussian.py
  tests/test_default_qubit.py
  tests/test_device.py
  tests/test_measure.py
  tests/test_quantum_gradients.py
Labels: core, review-ready

#329 Fix #300: unify import shortcuts to qml
  .github/CHANGELOG.md
  pennylane/qnode.py
  tests/test_about.py
  tests/test_operation.py
Labels: code quality

#330 Add C-SWAP to the qubit operations
  .github/CHANGELOG.md
  pennylane/ops/qubit.py
  pennylane/plugins/default_qubit.py
  tests/test_default_gaussian.py
  tests/test_default_qubit.py
Labels: enhancement, review-ready

#306 Expand DAG usage in QNode
  pennylane/qnode.py
  pennylane/utils.py
  tests/test_default_qubit.py
  tests/test_qnode.py
  tests/test_quantum_gradients.py
  tests/test_templates_layers.py
Labels: enhancement, merge-ready

#326 Add missing figures for gallery thumbnails of state-preparation and QGAN tutorials.
  .github/CHANGELOG.md
  doc/tutorials.rst
  examples/figures/NOON.png
  examples/figures/gan.png
  examples/figures/gauss-circuit.png
  examples/figures/qgan3.png
Labels: documentation, review-ready

#322 Create circuit_graph module and tests
  pennylane/circuit_graph.py
  pennylane/qnode.py
  pennylane/utils.py
  tests/test_circuit_graph.py
  tests/test_qnode.py
  tests/test_utils.py
Labels: enhancement, review-ready

#333 Add figure to QGAN tutorial
  .github/CHANGELOG.md
  examples/figures/gan.png
  examples/figures/qgan.png
  examples/pennylane_run_QGAN.py
Labels: documentation, review-ready

#328 Documentation change: add QAOA tutorial
  .github/CHANGELOG.md
  doc/tutorials.rst
  examples/figures/qaoa_maxcut_partition.png
  examples/figures/qaoa_operators.png
  examples/figures/qaoa_optimal_state.png
  examples/pennylane_run_qaoa_maxcut.py
Labels: documentation, review-ready
