Repository PennyLaneAI/pennylane, pull requests merged in 2019-01, with the labels that each got.

#148 Makes DisplacedSqueezedState() and CatState() take real (abs and phase) parameters instead of complex ones.
  .travis.yml
  pennylane/ops/cv.py
  pennylane/plugins/default_gaussian.py
  pennylane/qnode.py
  pennylane/utils.py
  tests/test_classical_gradients.py
  tests/test_default_gaussian.py
  tests/test_optimize.py
Labels: bug

#151 Support wires as variable objects
  pennylane/operation.py
  pennylane/qnode.py
  pennylane/variable.py
  tests/test_qnode.py
Labels: enhancement

#134 Add QML templates module
  doc/code/template.rst
  doc/index.rst
  doc/references.bib
  pennylane/__init__.py
  pennylane/plugins/default_qubit.py
  pennylane/template.py
  pennylane/utils.py
  tests/test_default_qubit.py
  tests/test_template.py
Labels: enhancement

#149 Add the CV Interferometer operation
  .pylintrc
  doc/references.bib
  pennylane/operation.py
  pennylane/ops/cv.py
  pennylane/plugins/default_gaussian.py
  pennylane/plugins/default_qubit.py
  pennylane/qnode.py
  tests/test_default_gaussian.py
  tests/test_default_qubit.py
  tests/test_operation.py
  tests/test_quantum_gradients.py
  tests/test_template.py
Labels: enhancement, review

#163 actually use n=len(par[0]) to make code more readable
  pennylane/plugins/default_qubit.py
Labels: review

#164 Some docs fixes and version number bump
  doc/_static/clements.png
  doc/_static/reck.png
  pennylane/_version.py
  pennylane/ops/cv.py
  pennylane/plugins/default_gaussian.py
  pennylane/plugins/default_qubit.py
Labels: review
