Repository PennyLaneAI/pennylane, pull requests merged in 2020-08, with the labels that each got.

#728 [Queuing] Adds AnnotatingQueue()
  .github/CHANGELOG.md
  pennylane/_queuing.py
  tests/test_queuing.py
Labels: review-ready :ok_hand:

#733 Adds CLI and Python invocations for the device test suite
  pennylane/plugins/__init__.py
  pennylane/plugins/tests/__init__.py
  pennylane/plugins/tests/conftest.py
  pennylane/plugins/tests/pytest.ini
  setup.py
Labels: review-ready :ok_hand:

#666 [WIRES] Allow user to define non-consecutive wires for a device
  .github/CHANGELOG.md
  pennylane/__init__.py
  pennylane/_device.py
  pennylane/_qubit_device.py
  pennylane/beta/plugins/default_tensor.py
  pennylane/circuit_drawer/circuit_drawer.py
  pennylane/circuit_drawer/representation_resolver.py
  pennylane/circuit_graph.py
  pennylane/collections/map.py
  pennylane/operation.py
  pennylane/plugins/default_gaussian.py
  pennylane/plugins/default_qubit.py
  pennylane/plugins/default_qubit_tf.py
  pennylane/plugins/tests/conftest.py
  pennylane/plugins/tests/test_wires.py
  pennylane/qnodes/base.py
  pennylane/qnodes/cv.py
  pennylane/qnodes/passthru.py
  pennylane/qnodes/qubit.py
  pennylane/qnodes/rev.py
  pennylane/templates/broadcast.py
  pennylane/templates/layers/strongly_entangling.py
  pennylane/templates/state_preparations/arbitrary_state_preparation.py
  pennylane/templates/state_preparations/mottonen.py
  pennylane/templates/subroutines/arbitrary_unitary.py
  pennylane/templates/subroutines/single_excitation_unitary.py
  pennylane/templates/subroutines/uccsd.py
  pennylane/utils.py
  pennylane/vqe/vqe.py
  pennylane/wires.py
  qchem/pennylane_qchem/qchem/structure.py
  tests/beta/test_default_tensor.py
  tests/circuit_drawer/test_circuit_drawer.py
  tests/circuit_drawer/test_representation_resolver.py
  tests/circuit_graph/test_circuit_graph.py
  tests/circuit_graph/test_circuit_graph_hash.py
  tests/circuit_graph/test_qasm.py
  tests/conftest.py
  tests/ops/test_cv_ops.py
  tests/ops/test_qubit_ops.py
  tests/plugins/test_default_gaussian.py
  tests/plugins/test_default_qubit.py
  tests/plugins/test_default_qubit_tf.py
  tests/qnodes/test_qnode_base.py
  tests/templates/test_embeddings.py
  tests/templates/test_integration.py
  tests/templates/test_layers.py
  tests/templates/test_state_preparations.py
  tests/templates/test_subroutines.py
  tests/test_device.py
  tests/test_operation.py
  tests/test_qaoa.py
  tests/test_qubit_device.py
  tests/test_vqe.py
  tests/test_wires.py
Labels: review-ready :ok_hand:

#746 Fix test suite which fails for default.qubit when in non-analytic mode
  pennylane/devices/tests/test_wires.py
Labels: bug :bug:

#753 Updated the interface documentation
  doc/_static/numpy.png
  doc/introduction/circuits.rst
  doc/introduction/interfaces.rst
  doc/introduction/interfaces/numpy.rst
  doc/introduction/interfaces/tf.rst
  doc/introduction/interfaces/torch.rst
  pennylane/__init__.py
Labels: documentation :blue_book:

#759 Minor refactor of the 'obs' module
  qchem/CHANGELOG.md
  qchem/pennylane_qchem/qchem/obs.py
  qchem/tests/test_particle_number_obs.py
  qchem/tests/test_s2_obs.py
  qchem/tests/test_sz_obs.py
Labels: qchem :atom_symbol:, review-ready :ok_hand:

#735 Refactor functions used to construct the molecular Hamiltonian
  doc/_static/qchem/fig_mult_active_space.png
  doc/_static/qchem/hf_references.png
  doc/_static/qchem/sketch_active_space.png
  doc/introduction/chemistry.rst
  qchem/CHANGELOG.md
  qchem/pennylane_qchem/qchem/__init__.py
  qchem/pennylane_qchem/qchem/structure.py
  qchem/tests/test_active_space.py
  qchem/tests/test_convert_observable.py
  qchem/tests/test_decompose.py
  qchem/tests/test_generate_hamiltonian.py
  qchem/tests/test_meanfield.py
  qchem/tests/test_molecular_hamiltonian.py
Labels: qchem :atom_symbol:, review-ready :ok_hand:

#750 Qchem custom wires
  pennylane/vqe/vqe.py
  pennylane/wires.py
  qchem/CHANGELOG.md
  qchem/pennylane_qchem/qchem/obs.py
  qchem/pennylane_qchem/qchem/structure.py
  qchem/tests/conftest.py
  qchem/tests/test_convert_observable.py
  qchem/tests/test_observable.py
  qchem/tests/test_particle_number_obs.py
  qchem/tests/test_s2_obs.py
  qchem/tests/test_sz_obs.py
  tests/test_vqe.py
  tests/test_wires.py
Labels: qchem :atom_symbol:, review-ready :ok_hand:

#742 Refactor QChem functions required for UCCSD
  doc/_static/qchem/sd_excitations.png
  pennylane/vqe/vqe.py
  pennylane/wires.py
  qchem/CHANGELOG.md
  qchem/pennylane_qchem/qchem/__init__.py
  qchem/pennylane_qchem/qchem/obs.py
  qchem/pennylane_qchem/qchem/structure.py
  qchem/tests/conftest.py
  qchem/tests/test_convert_observable.py
  qchem/tests/test_excitations.py
  qchem/tests/test_excitations_to_wires.py
  qchem/tests/test_hf_state.py
  qchem/tests/test_observable.py
  qchem/tests/test_particle_number_obs.py
  qchem/tests/test_s2_obs.py
  qchem/tests/test_sd_excitations.py
  qchem/tests/test_sz_obs.py
  tests/test_vqe.py
  tests/test_wires.py
Labels: qchem :atom_symbol:, review-ready :ok_hand:

#748 Refactor the templates used to build the UCCSD ansatz
  .github/CHANGELOG.md
  doc/_static/templates/subroutines/double_excitation_unitary.png
  doc/_static/templates/subroutines/single_excitation_unitary.png
  pennylane/templates/subroutines/double_excitation_unitary.py
  pennylane/templates/subroutines/single_excitation_unitary.py
  pennylane/templates/subroutines/uccsd.py
  qchem/tests/test_excitations_to_wires.py
  tests/templates/test_integration.py
  tests/templates/test_subroutines.py
Labels: qchem :atom_symbol:, review-ready :ok_hand:, templates :file_folder:

#768 Update broken PennyLane links
  doc/conf.py
  doc/development/guide/adr.rst
  doc/development/guide/installation.rst
  doc/development/guide/pullrequests.rst
  doc/development/plugins.rst
  doc/index.rst
  doc/xanadu_theme/footer.html
  doc/xanadu_theme/header.html
  doc/xanadu_theme/layout.html
  pennylane/__init__.py
Labels: documentation :blue_book:

#760 Add quantum channel operation subclass
  .github/CHANGELOG.md
  pennylane/operation.py
  tests/test_operation.py
Labels: core :atom:, review-ready :ok_hand:

#766 Adding known Quantum channels
  .github/CHANGELOG.md
  doc/introduction/operations.rst
  pennylane/operation.py
  pennylane/ops/__init__.py
  pennylane/ops/channel.py
  tests/ops/test_channel_ops.py
Labels: review-ready :ok_hand:

#772 Speed up default.qubit by using permutations to apply some gates
  .github/CHANGELOG.md
  pennylane/_qubit_device.py
  pennylane/devices/default_qubit.py
  pennylane/devices/default_qubit_autograd.py
  pennylane/devices/default_qubit_tf.py
  tests/devices/test_default_qubit.py
  tests/devices/test_default_qubit_autograd.py
  tests/devices/test_default_qubit_tf.py
Labels: merge-ready :heavy_check_mark:
