Repository PennyLaneAI/pennylane, pull requests merged in 2020-06, with the labels that each got.

#659 Fix bug in the functions "test_single_ex_unitary_operations" and "test_double_ex_unitary_operations"
  .github/CHANGELOG.md
  tests/templates/test_subroutines.py
Labels: qchem :atom_symbol:, review-ready :ok_hand:, templates :file_folder:, tests :test_tube:

#663 Update Rotoselect and Rotosolve examples
  pennylane/optimize/rotoselect.py
  pennylane/optimize/rotosolve.py
Labels: bug :bug:, documentation :blue_book:, review-ready :ok_hand:

#645 [WIRES] Use new wire class in templates
  pennylane/templates/broadcast.py
  pennylane/templates/embeddings/amplitude.py
  pennylane/templates/embeddings/angle.py
  pennylane/templates/embeddings/basis.py
  pennylane/templates/embeddings/displacement.py
  pennylane/templates/embeddings/iqp.py
  pennylane/templates/embeddings/qaoa.py
  pennylane/templates/embeddings/squeezing.py
  pennylane/templates/layers/basic_entangler.py
  pennylane/templates/layers/cv_neural_net.py
  pennylane/templates/layers/random.py
  pennylane/templates/layers/simplified_two_design.py
  pennylane/templates/layers/strongly_entangling.py
  pennylane/templates/state_preparations/arbitrary_state_preparation.py
  pennylane/templates/state_preparations/basis.py
  pennylane/templates/state_preparations/mottonen.py
  pennylane/templates/subroutines/arbitrary_unitary.py
  pennylane/templates/subroutines/double_excitation_unitary.py
  pennylane/templates/subroutines/interferometer.py
  pennylane/templates/subroutines/single_excitation_unitary.py
  pennylane/templates/subroutines/uccsd.py
  pennylane/wires.py
  tests/templates/test_broadcast.py
  tests/templates/test_embeddings.py
  tests/templates/test_layers.py
  tests/templates/test_subroutines.py
  tests/test_wires.py
Labels: code quality :mortar_board:, review-ready :ok_hand:

#664 Fix qnn.cost module tests for early versions of Torch
  tests/qnn/test_cost.py
Labels: bug :bug:, review-ready :ok_hand:

#660 Tensor variable refactor refactor
  .github/CHANGELOG.md
  pennylane/interfaces/autograd.py
  pennylane/interfaces/tf.py
  pennylane/interfaces/torch.py
  pennylane/qnodes/base.py
  pennylane/qnodes/jacobian.py
  tests/interfaces/test_autograd.py
  tests/interfaces/test_tf.py
  tests/interfaces/test_torch.py
  tests/qnodes/test_qnode_base.py
Labels: autodiff :chart_with_upwards_trend:, bug :bug:, interface :electric_plug:, review-ready :ok_hand:

#662 Adds a new `default.qubit.tf` pure-state simulator with PassthruQNode support
  .github/CHANGELOG.md
  pennylane/_qubit_device.py
  pennylane/beta/plugins/__init__.py
  pennylane/beta/plugins/default_qubit_tf.py
  pennylane/beta/plugins/tf_ops.py
  pennylane/plugins/default_qubit.py
  pennylane/qnodes/decorator.py
  setup.py
  tests/beta/test_default_qubit_tf.py
  tests/beta/test_default_tensor_tf.py
Labels: plugins :computer:, review-ready :ok_hand:

#669 Graduated default.qubit.tf out of beta
  pennylane/beta/plugins/__init__.py
  pennylane/plugins/__init__.py
  pennylane/plugins/default_qubit_tf.py
  pennylane/plugins/tf_ops.py
  setup.py
  tests/plugins/test_default_gaussian.py
  tests/plugins/test_default_qubit.py
  tests/plugins/test_default_qubit_tf.py
Labels: review-ready :ok_hand:

#653 [WIRES] Use wire class in operations
  doc/code/qml_operation.rst
  pennylane/_device.py
  pennylane/_qubit_device.py
  pennylane/beta/plugins/default_tensor_tf.py
  pennylane/circuit_drawer/circuit_drawer.py
  pennylane/circuit_drawer/representation_resolver.py
  pennylane/circuit_graph.py
  pennylane/operation.py
  pennylane/plugins/default_gaussian.py
  pennylane/plugins/default_qubit.py
  pennylane/qnodes/base.py
  pennylane/qnodes/qubit.py
  pennylane/templates/broadcast.py
  pennylane/templates/embeddings/amplitude.py
  pennylane/templates/embeddings/basis.py
  pennylane/templates/layers/random.py
  pennylane/templates/state_preparations/basis.py
  pennylane/templates/state_preparations/mottonen.py
  pennylane/templates/subroutines/double_excitation_unitary.py
  pennylane/templates/subroutines/interferometer.py
  pennylane/templates/subroutines/single_excitation_unitary.py
  pennylane/templates/subroutines/uccsd.py
  pennylane/vqe/vqe.py
  qchem/pennylane_qchem/qchem.py
  qchem/tmplv5rrgvd
  tests/circuit_drawer/test_circuit_drawer.py
  tests/circuit_graph/test_circuit_graph.py
  tests/circuit_graph/test_qasm.py
  tests/ops/test_cv_ops.py
  tests/ops/test_qubit_ops.py
  tests/plugins/test_default_qubit.py
  tests/qnodes/test_qnode_base.py
  tests/templates/test_embeddings.py
  tests/templates/test_layers.py
  tests/templates/test_state_preparations.py
  tests/templates/test_subroutines.py
  tests/test_operation.py
  tests/test_qubit_device.py
  tests/test_wires.py
Labels: code quality :mortar_board:

#672 [WIRES] Include wires class in documentation
  doc/code/qml_wires.rst
  doc/index.rst
  pennylane/wires.py
Labels: documentation :blue_book:

#628 Update benchmarking suite to support running on older commits
  benchmark/README.rst
  benchmark/benchmark_utils.py
  benchmark/bm_iqp_circuit.py
Labels: WIP :construction:, enhancement :sparkles:

#599 Update `default.tensor` plugin
  .github/CHANGELOG.md
  doc/requirements.txt
  pennylane/beta/plugins/default_tensor.py
  pennylane/beta/plugins/default_tensor_tf.py
  pennylane/beta/plugins/numpy_ops.py
  requirements.txt
  tests/beta/test_default_tensor.py
  tests/beta/test_default_tensor_tf.py
  tests/conftest.py
Labels: enhancement :sparkles:, plugins :computer:

#677 Rename function 'convert_hamiltonian' to 'convert_observable'
  qchem/CHANGELOG.md
  qchem/pennylane_qchem/qchem.py
  qchem/tests/test_convert_observable.py
Labels: qchem :atom_symbol:, review-ready :ok_hand:

#687 Update CHANGELOG for release v0.10
  .github/CHANGELOG.md
Labels: documentation :blue_book:, merge-ready :heavy_check_mark:

#694 Adds details on ADR structure to the documentation.
  doc/development/guide.rst
  doc/development/guide/adr.rst
Labels: documentation :blue_book:, review-ready :ok_hand:

#693 Adds ArbitraryUnitary and ArbitraryStatePreparation templates to the templates gallery
  doc/_static/templates/subroutines/arbitrarystateprep.png
  doc/_static/templates/subroutines/arbitraryunitary.png
  doc/introduction/templates.rst
Labels: documentation :blue_book:, review-ready :ok_hand:

#682 Architectural overview
  doc/development/guide.rst
  doc/development/guide/architecture.rst
  doc/development/guide/architecture_diagram.png
  pennylane/_queuing_context.py
Labels: documentation :blue_book:

#671 Revamped code for hamiltonian decomposition
  .github/CHANGELOG.md
  doc/code/qml_utils.rst
  pennylane/utils.py
  tests/test_utils.py
Labels: merge-ready :heavy_check_mark:

#679 Map the indices of 1p1h and 2p2h configurations to an arbitrary set of wires
  qchem/CHANGELOG.md
  qchem/pennylane_qchem/qchem.py
  qchem/tests/test_excitations_to_wires.py
Labels: qchem :atom_symbol:, review-ready :ok_hand:

#688 Benchmark for short-depth nearest-neighbour circuits
  benchmark/README.rst
  benchmark/benchmark.py
  benchmark/benchmark_utils.py
  benchmark/bm_nearest_neighbour_circuit.py
Labels: merge-ready :heavy_check_mark:, performance :timer_clock:

#689 Implement total-spin observable in PennyLane-QChem
  doc/code/qml_qchem.rst
  qchem/CHANGELOG.md
  qchem/pennylane_qchem/__init__.py
  qchem/pennylane_qchem/qchem/__init__.py
  qchem/pennylane_qchem/qchem/obs.py
  qchem/pennylane_qchem/qchem/structure.py
  qchem/setup.py
  qchem/tests/test_observable.py
  qchem/tests/test_s2_obs.py
  qchem/tmplv5rrgvd
Labels: qchem :atom_symbol:, review-ready :ok_hand:

#696 Implement spin projection observable in PennyLane-QChem
  qchem/CHANGELOG.md
  qchem/pennylane_qchem/qchem/obs.py
  qchem/tests/test_sz_obs.py
Labels: qchem :atom_symbol:, review-ready :ok_hand:

#699 Use cutoff for CV base state probabilities
  .github/CHANGELOG.md
  pennylane/qnodes/base.py
  pennylane/qnodes/cv.py
Labels: photonics :zap:
