Repository PennyLaneAI/pennylane, pull requests merged in 2020-03, with the labels that each got.

#538 Update author list
  README.rst
  doc/conf.py
  doc/index.rst
Labels: documentation, review-ready

#530 Adding step size for finite differences method, adjusting kwargs in QNodes
  .github/CHANGELOG.md
  pennylane/qnodes/base.py
  pennylane/qnodes/decorator.py
  pennylane/qnodes/jacobian.py
  pennylane/qnodes/passthru.py
  tests/qnodes/test_qnode_base.py
  tests/qnodes/test_qnode_decorator.py
Labels: enhancement

#540 Add inverses and probabilities to CircuitDrawer
  pennylane/circuit_drawer/charsets.py
  pennylane/circuit_drawer/representation_resolver.py
  tests/circuit_drawer/test_circuit_drawer.py
  tests/circuit_drawer/test_grid.py
  tests/circuit_drawer/test_representation_resolver.py
Labels: core, review-ready

#544 Fix bug in single qubit strongly entangling layers
  pennylane/templates/layers/strongly_entangling.py
  tests/test_templates_layers.py
Labels: bug, review-ready

#546 Fix typo in operations.py
  pennylane/operation.py
Labels: code quality

#542 Fix print_applied for Probabilities
  pennylane/circuit_graph.py
  tests/qnodes/test_qnode_base.py
Labels: bug, core

#543 Fix inversion of decompositions
  pennylane/qnodes/base.py
  tests/qnodes/test_qnode_base.py
Labels: bug, core, review-ready

#545 Fix typo and adding missing arg
  pennylane/vqe/vqe.py
Labels: documentation

#547 [WIP] Simplify decomposition of CRY
  doc/_static/cry_circuit.png
  pennylane/ops/qubit.py
  tests/qnodes/test_qnode_base.py
  tests/test_operation.py
Labels: code quality

#508 Operators string-represent themselves.
  pennylane/circuit_graph.py
  pennylane/operation.py
  pennylane/utils.py
  tests/qnodes/test_qnode_base.py
Labels: code quality, core, merge-ready

#539 Rotosolve and rotoselect optimizers
  doc/introduction/optimizers.rst
  pennylane/optimize/__init__.py
  pennylane/optimize/rotoselect.py
  pennylane/optimize/rotosolve.py
  tests/test_optimize.py
Labels: enhancement

#548 Add QueuingContext for queue interactions
  .github/CHANGELOG.md
  pennylane/__init__.py
  pennylane/_queuing_context.py
  pennylane/measure.py
  pennylane/operation.py
  pennylane/qnodes/base.py
  pennylane/utils.py
  tests/qnodes/test_qnode_base.py
  tests/test_queuing_context.py
  tests/test_utils.py
Labels: code quality, core, review-ready

#516 Benchmarking script, two benchmarks.
  benchmark/README.rst
  benchmark/benchmark.py
  benchmark/benchmark_utils.py
  benchmark/bm_entangling_layers.py
  benchmark/bm_mutable_rotations.py
  benchmark/requirements.txt
  benchmark/view_pstats.sh
Labels: benchmarking, merge-ready, review-ready

#555 Add CnotRing template
  .github/CHANGELOG.md
  doc/_static/templates/layers/basic_entangler.png
  doc/_static/templates/layers/basic_entangler_2wires.png
  doc/introduction/templates.rst
  pennylane/init.py
  pennylane/templates/layers/__init__.py
  pennylane/templates/layers/basic_entangler.py
  tests/test_init.py
  tests/test_templates.py
  tests/test_templates_layers.py
Labels: review-ready, templates

#560 New benchmark measuring QNode _construct efficiency.
  benchmark/bm_entangling_layers.py
  benchmark/bm_mutable_complicated_params.py
Labels: benchmarking, core, merge-ready, review-ready

#556 Add coles template
  .github/CHANGELOG.md
  doc/_static/templates/layers/cnot_ring_1wire.png
  doc/_static/templates/layers/cvqnn.png
  doc/_static/templates/layers/random.png
  doc/_static/templates/layers/simplified_two_design.png
  doc/_static/templates/layers/strongly_entangling.png
  doc/introduction/templates.rst
  pennylane/init.py
  pennylane/templates/layers/__init__.py
  pennylane/templates/layers/simplified_two_design.py
  tests/test_init.py
  tests/test_templates.py
  tests/test_templates_layers.py
Labels: review-ready, templates
