Repository PennyLaneAI/pennylane, pull requests merged in 2020-05, with the labels that each got.

#568 Add script to compare commits and additional benchmarks
  .github/CHANGELOG.md
  .gitignore
  benchmark/README.rst
  benchmark/benchmark_revisions.py
  benchmark/benchmark_utils.py
  benchmark/bm_entangling_layers.py
  benchmark/bm_iqp_circuit.py
Labels: benchmarking, review-ready

#614 Refactor old Wires class
  .github/CHANGELOG.md
  pennylane/operation.py
  pennylane/ops/__init__.py
  pennylane/ops/cv.py
  pennylane/ops/qubit.py
  pennylane/qnodes/base.py
  tests/beta/test_default_tensor.py
  tests/qnodes/test_qnode_base.py
  tests/test_operation.py
Labels: code quality

#605 Add iqp template
  .github/CHANGELOG.md
  doc/_static/templates/embeddings/iqp.png
  doc/_static/templates/embeddings/iqp_custom.png
  doc/introduction/templates.rst
  pennylane/templates/embeddings/__init__.py
  pennylane/templates/embeddings/iqp.py
  tests/templates/test_embeddings.py
  tests/templates/test_integration.py
Labels: templates

#610 Update the default behaviour of the example configuration
  MANIFEST.in
  default_config.toml
  doc/introduction/configuration.rst
  example_config.toml
  tests/test_configuration.py
Labels: code quality, documentation, review-ready

#618 Enable QNG for VQE-like problems (QNodeCollection with same ansatz)
  .github/CHANGELOG.md
  pennylane/optimize/qng.py
  pennylane/vqe/vqe.py
  tests/test_optimize_qng.py
Labels: review-ready

#609 Use multiz in qaoaembedding
  .github/CHANGELOG.md
  pennylane/templates/embeddings/qaoa.py
  tests/templates/test_embeddings.py
Labels: bug, code quality

#535 added feature to decompose hamiltonians to Pauli matrices
  doc/code/qml_utils.rst
  pennylane/utils.py
  tests/test_utils.py
Labels: WIP, enhancement

#552 Adding classical and device differentiation methods to the qnode decorator using a factory method
  .github/CHANGELOG.md
  pennylane/beta/plugins/default_tensor_tf.py
  pennylane/qnodes/decorator.py
  pennylane/qnodes/passthru.py
  tests/beta/test_default_tensor_tf.py
  tests/qnodes/test_qnode_decorator.py
  tests/qnodes/test_qnode_passthru.py
Labels: code quality, enhancement, merge-ready

#590 Add templates for arbitrary unitaries and state preparations
  .github/CHANGELOG.md
  pennylane/templates/state_preparations/__init__.py
  pennylane/templates/state_preparations/arbitrary_state_preparation.py
  pennylane/templates/subroutines/__init__.py
  pennylane/templates/subroutines/arbitrary_unitary.py
  tests/templates/test_layers.py
  tests/templates/test_state_preparations.py
  tests/templates/test_subroutines.py
Labels: review-ready, templates

#608 Adding the TensorN observable
  .github/CHANGELOG.md
  doc/introduction/operations.rst
  pennylane/ops/cv.py
  tests/test_default_gaussian.py
  tests/test_operation.py
Labels: CV, review-ready

#567 Improve default.qubit performance
  .github/CHANGELOG.md
  doc/development/plugins.rst
  pennylane/beta/plugins/default_tensor.py
  pennylane/operation.py
  pennylane/ops/__init__.py
  pennylane/ops/cv.py
  pennylane/ops/qubit.py
  pennylane/optimize/adagrad.py
  pennylane/optimize/adam.py
  pennylane/optimize/rms_prop.py
  pennylane/plugins/default_gaussian.py
  pennylane/plugins/default_qubit.py
  pennylane/templates/embeddings/amplitude.py
  pennylane/templates/state_preparations/mottonen.py
  tests/gate_data.py
  tests/ops/test_qubit_ops.py
  tests/templates/test_embeddings.py
  tests/templates/test_state_preparations.py
  tests/test_default_qubit.py
  tests/test_operation.py
Labels: benchmarking, core, enhancement, plugins, review-ready

#520 Adding tolerance test for Amplitude embedding
  tests/templates/test_embeddings.py
Labels: WIP, tests

#626 Fix TensorFlow's jacobian when applied to a QNode
  .github/CHANGELOG.md
  pennylane/interfaces/tf.py
  tests/interfaces/test_tf.py
Labels: bug, review-ready

#631 Fix passthru decomposition
  pennylane/qnodes/passthru.py
  tests/qnodes/test_qnode_passthru.py
Labels: bug

#633 Fix string representation of devices
  pennylane/_device.py
Labels: bug

#635 Rename the classical diff_method to backprop
  pennylane/beta/plugins/default_tensor_tf.py
  pennylane/qnodes/decorator.py
  tests/beta/test_default_tensor_tf.py
  tests/qnodes/test_qnode_decorator.py
Labels: code quality

#634 Release v0.9
  .github/CHANGELOG.md
  doc/conf.py
  pennylane/_version.py
  setup.py
Labels: on-hold, review-ready

#623 Serialize CircuitGraph to QASM
  .github/CHANGELOG.md
  pennylane/circuit_graph.py
  tests/circuit_graph/test_qasm.py
Labels: enhancement

#629 Add function 'hf_state' to 'qchem' module
  qchem/CHANGELOG.md
  qchem/pennylane_qchem/_version.py
  qchem/pennylane_qchem/qchem.py
  qchem/tests/test_hf_state.py
Labels: enhancement, merge-ready, qchem

#622 Add the new template SingleExcitationOp
  .github/CHANGELOG.md
  doc/_static/templates/subroutines/single_excitation_unitary.png
  doc/introduction/templates.rst
  pennylane/templates/subroutines/__init__.py
  pennylane/templates/subroutines/single_excitation_unitary.py
  pennylane/templates/utils.py
  tests/templates/test_integration.py
  tests/templates/test_subroutines.py
Labels: enhancement, merge-ready, templates

#640 Fixes a typo in the TF interface documentation
  doc/introduction/interfaces/tf.rst
Labels: bug, documentation

#588 Add Torch layers support
  .github/CHANGELOG.md
  .travis.yml
  pennylane/qnn/__init__.py
  pennylane/qnn/keras.py
  pennylane/qnn/torch.py
  tests/collections/conftest.py
  tests/collections/test_collections.py
  tests/collections/test_qnode_collection.py
  tests/qnn/conftest.py
  tests/qnn/test_keras.py
  tests/qnn/test_qnn_torch.py
Labels: enhancement, interface, merge-ready

#639 Officially remove Python 3.5 support, update TF1.X support to >=1.15
  .github/CHANGELOG.md
  .travis.yml
  README.rst
  doc/development/guide/installation.rst
  pennylane/interfaces/tf.py
  qchem/CHANGELOG.md
  qchem/setup.py
  setup.py
  tests/collections/test_collections.py
  tests/collections/test_qnode_collection.py
  tests/interfaces/test_tf.py
  tests/interfaces/test_torch.py
  tests/templates/test_integration.py
  tests/test_configuration.py
  tests/test_vqe.py
Labels: deprecation

#638 Add the new template 'DoubleExcitationUnitary'
  .github/CHANGELOG.md
  doc/_static/templates/subroutines/double_excitation_unitary.png
  doc/introduction/templates.rst
  pennylane/templates/subroutines/__init__.py
  pennylane/templates/subroutines/double_excitation_unitary.py
  tests/templates/test_integration.py
  tests/templates/test_subroutines.py
Labels: qchem, review-ready, templates

#615 [WIP] Introduce wire class
  .github/CHANGELOG.md
  doc/xanadu_theme/static/jquery.min.map
  pennylane/vqe/vqe.py
  pennylane/wires.py
  tests/templates/test_layers.py
  tests/test_wires.py
Labels: code quality

#641 Extend the development documentation page
  doc/development/guide/documentation.rst
  doc/development/guide/pullrequests.rst
Labels: documentation, review-ready

#648 [Tensor refactor] Subclass ndarray to allow marking of trainable parameters
  .github/CHANGELOG.md
  pennylane/__init__.py
  pennylane/numpy/__init__.py
  pennylane/numpy/fft.py
  pennylane/numpy/linalg.py
  pennylane/numpy/random.py
  pennylane/numpy/tensor.py
  pennylane/numpy/wrapper.py
  pennylane/optimize/rotoselect.py
  pennylane/optimize/rotosolve.py
  tests/collections/test_qnode_collection.py
  tests/test_classical_gradients.py
  tests/test_numpy_wrapper.py
  tests/test_optimize.py
Labels: autodiff, core, review-ready

#650 [Tensor refactor] update the Autograd interface to use the new PennyLane tensor class
  .github/CHANGELOG.md
  .travis.yml
  pennylane/__init__.py
  pennylane/init.py
  pennylane/interfaces/autograd.py
  pennylane/operation.py
  pennylane/qnodes/jacobian.py
  tests/interfaces/test_autograd.py
  tests/qnodes/test_qnode_cv.py
  tests/qnodes/test_qnode_jacobian.py
  tests/test_quantum_gradients.py
Labels: autodiff :chart_with_upwards_trend:, core :atom:, enhancement :sparkles:, review-ready :ok_hand:

#651 [WIP] introduce wire class (continuation of #615)
  .github/CHANGELOG.md
  pennylane/wires.py
  tests/test_wires.py
Labels: WIP :construction:, code quality :mortar_board:

#655 [Tensor refactor] Updates the TF interface to exclude the quantum gradients for input tensors not watched by the GradientTape
  .github/CHANGELOG.md
  pennylane/interfaces/tf.py
  pennylane/operation.py
  tests/interfaces/test_tf.py
Labels: enhancement :sparkles:, interface :electric_plug:, review-ready :ok_hand:

#656 [WIRES] Make tensor observables wires a flat list
  pennylane/_device.py
  pennylane/operation.py
  pennylane/qnodes/base.py
  qchem/pennylane_qchem/qchem.py
  qchem/tests/test_convert_hamiltonian.py
  tests/circuit_graph/test_circuit_graph_hash.py
  tests/test_operation.py
  tests/test_wires.py
Labels: code quality :mortar_board:, review-ready :ok_hand:

#642 Add MSECost
  .github/CHANGELOG.md
  .gitignore
  pennylane/qnn/__init__.py
  pennylane/qnn/cost.py
  tests/qnn/test_cost.py
Labels: review-ready :ok_hand:

#652 [Tensor refactor] Updates the Torch interface to exclude the quantum gradients for input tensors where requires_grad is False
  .github/CHANGELOG.md
  pennylane/interfaces/torch.py
  tests/interfaces/test_torch.py
Labels: autodiff :chart_with_upwards_trend:, enhancement :sparkles:, review-ready :ok_hand:

#654 Uccsd template
  .github/CHANGELOG.md
  doc/_static/templates/subroutines/uccsd.png
  doc/introduction/templates.rst
  pennylane/templates/subroutines/__init__.py
  pennylane/templates/subroutines/uccsd.py
  tests/templates/test_integration.py
  tests/templates/test_subroutines.py
Labels: qchem :atom_symbol:, review-ready :ok_hand:, templates :file_folder:
