Repository PennyLaneAI/pennylane, pull requests merged in 2020-01, with the labels that each got.

#454 Adding the diagonalizing_gates method for the Tensor
  .github/CHANGELOG.md
  pennylane/operation.py
  pennylane/ops/__init__.py
  pennylane/ops/qubit.py
  tests/ops/test_qubit_ops.py
  tests/test_operation.py
  tests/test_ops_qubit.py
Labels: review-ready

#458 Added quantum chemistry quickstart
  doc/index.rst
  doc/introduction/chemistry.rst
Labels: documentation

#452 [WIP] Creating the Qubit device class
  .github/CHANGELOG.md
  pennylane/__init__.py
  pennylane/_qubit_device.py
  pennylane/operation.py
  pennylane/ops/qubit.py
  pennylane/plugins/default_qubit.py
  pennylane/qnodes/qubit.py
  qchem/tests/test_load_hamiltonian.py
  tests/conftest.py
  tests/interfaces/test_tf.py
  tests/ops/test_qubit_ops.py
  tests/test_default_qubit.py
  tests/test_operation.py
  tests/test_tensor_measurements.py
Labels: WIP

#463 Refactor function names
  doc/introduction/chemistry.rst
  qchem/pennylane_qchem/qchem.py
  qchem/tests/test_active_space.py
  qchem/tests/test_convert_hamiltonian.py
  qchem/tests/test_decompose_hamiltonian.py
  qchem/tests/test_generate_hamiltonian.py
  qchem/tests/test_meanfield_data.py
Labels: qchem

#464 Change output of generate_hamiltonian()
  doc/introduction/chemistry.rst
  qchem/pennylane_qchem/qchem.py
  qchem/tests/test_generate_hamiltonian.py
Labels: qchem

#466 Adds QNodeCollections and map-reduce functionality
  .github/CHANGELOG.md
  doc/xanadu_theme/static/xanadu.css_t
  pennylane/__init__.py
  pennylane/collections.py
  pennylane/measure.py
  tests/test_collections.py
Labels: core, review-ready

#459 Add pyquil loading convenience functions
  .github/CHANGELOG.md
  pennylane/__init__.py
  pennylane/io.py
  tests/test_io.py
Labels: core, plugins, review-ready

#461 [WIP] Unify sampling
  .github/CHANGELOG.md
  pennylane/_qubit_device.py
  pennylane/plugins/default_qubit.py
  pennylane/qnodes/qubit.py
  tests/test_default_qubit.py
  tests/test_measure.py
  tests/test_qubit_device.py
  tests/test_tensor_measurements.py
Labels: WIP, plugins

#469 Adds release notes to documentation
  .github/CHANGELOG.md
  doc/conf.py
  doc/development/release_notes.md
  doc/development/research.rst
  doc/index.rst
  doc/introduction/circuits.rst
  doc/requirements.txt
  pennylane/io.py
Labels: documentation

#462 Add an inversion function for templates
  .github/CHANGELOG.md
  doc/introduction/templates.rst
  pennylane/__init__.py
  pennylane/qnodes/base.py
  pennylane/templates/__init__.py
  pennylane/templates/decorator.py
  pennylane/templates/embeddings.py
  pennylane/templates/layers.py
  pennylane/templates/state_preparations.py
  pennylane/templates/subroutines.py
  pennylane/utils.py
  tests/qnodes/test_qnode_base.py
  tests/test_templates_decorator.py
  tests/test_utils.py
Labels: core, templates

#467 Graduate VQE module
  .github/CHANGELOG.md
  .gitignore
  .travis.yml
  doc/code/qml_beta.rst
  doc/code/qml_operation.rst
  doc/conf.py
  doc/development/guide.rst
  doc/introduction/chemistry.rst
  pennylane/__init__.py
  pennylane/beta/__init__.py
  pennylane/beta/vqe/vqe.py
  pennylane/collections.py
  pennylane/vqe/__init__.py
  pennylane/vqe/vqe.py
  qchem/README.rst
  qchem/pennylane_qchem/qchem.py
  qchem/setup.py
  qchem/tests/test_convert_hamiltonian.py
  qchem/tests/test_generate_hamiltonian.py
  setup.py
  tests/test_about.py
  tests/test_vqe.py
Labels: qchem, review-ready

#470 Circuit graph hash
  .github/CHANGELOG.md
  pennylane/circuit_graph.py
  pennylane/qnodes/base.py
  tests/circuit_graph/test_circuit_graph.py
  tests/circuit_graph/test_circuit_graph_hash.py
Labels: enhancement

#472 Improve measurement intro
  doc/introduction/measurements.rst
Labels: documentation, review-ready

#473 Refactor the execute method of QubitDevice
  .github/CHANGELOG.md
  pennylane/_device.py
  pennylane/_qubit_device.py
  pennylane/circuit_graph.py
  pennylane/plugins/default_qubit.py
  pennylane/qnodes/base.py
  pennylane/qnodes/qubit.py
  tests/circuit_graph/test_circuit_graph.py
  tests/qnodes/test_qnode_base.py
  tests/test_default_qubit.py
  tests/test_observable.py
  tests/test_qubit_device.py
Labels: plugins, review-ready

#476 CRLF line endings normalized to LF.
  pennylane/beta/__init__.py
  pennylane/beta/plugins/__init__.py
  pennylane/interfaces/autograd.py
  pennylane/qnodes/decorator.py
  pennylane/qnodes/device_jacobian.py
  tests/qnodes/test_qnode_cv.py
  tests/qnodes/test_qnode_decorator.py
  tests/qnodes/test_qnode_qubit.py
Labels: code quality, review-ready

#478 Add some default values to the QubitDevice capabilities dictionary
  pennylane/_qubit_device.py
  pennylane/plugins/default_qubit.py
Labels: plugins, review-ready

#482 Added a pull request docs check
  .github/workflows/main.yml
Labels: documentation

#477 Clean up default.qubit
  pennylane/_qubit_device.py
  pennylane/beta/plugins/expt_tensornet.py
  pennylane/beta/plugins/expt_tensornet_tf.py
  pennylane/operation.py
  pennylane/plugins/default_qubit.py
  tests/beta/test_tensornet.py
  tests/beta/test_tensornet_tf.py
  tests/gate_data.py
  tests/interfaces/test_tf.py
  tests/interfaces/test_torch.py
  tests/ops/test_qubit_ops.py
  tests/qnodes/test_qnode_metric_tensor.py
  tests/qnodes/test_qnode_qubit.py
  tests/test_default_qubit.py
  tests/test_operation.py
  tests/test_quantum_gradients.py
  tests/test_tensor_measurements.py
Labels: code quality, review-ready

#481 Fixes a sampling bug affecting QubitDevice
  pennylane/_qubit_device.py
  pennylane/operation.py
  pennylane/ops/qubit.py
  tests/ops/test_qubit_ops.py
  tests/test_hermitian_edge_cases.py
  tests/test_qubit_device.py
  tests/test_tensor_measurements.py
Labels: bug, review-ready

#485 Adding keyword arguments to QubitDevice.execute and QubitDevice.apply
  pennylane/_qubit_device.py
  tests/test_qubit_device.py
Labels: enhancement

#479 Adds figure sketching PennyLane-QChem
  doc/_static/sketch_pennylane_qchem.png
  doc/introduction/chemistry.rst
Labels: qchem

#484 Add support for asynchronous evaluation of QNode collections
  .github/CHANGELOG.md
  pennylane/collections.py
  requirements.txt
  tests/circuit_graph/test_circuit_graph_hash.py
  tests/collections/conftest.py
  tests/collections/test_collections.py
  tests/collections/test_qnode_collection.py
Labels: enhancement

#483 Update the developers plugin guide to use QubitDevice
  doc/development/plugins.rst
  pennylane/_qubit_device.py
Labels: documentation, plugins

#489 Setting shots when instantiating Device
  pennylane/_device.py
  tests/test_device.py
Labels: bug, merge-ready

#446 Add a text-based circuit drawer
  .github/CHANGELOG.md
  pennylane/circuit_drawer/__init__.py
  pennylane/circuit_drawer/charsets.py
  pennylane/circuit_drawer/circuit_drawer.py
  pennylane/circuit_drawer/grid.py
  pennylane/circuit_drawer/representation_resolver.py
  pennylane/circuit_graph.py
  pennylane/ops/qubit.py
  pennylane/qnodes/base.py
  pennylane/qnodes/cv.py
  pennylane/qnodes/qubit.py
  pennylane/variable.py
  setup.py
  tests/circuit_drawer/test_circuit_drawer.py
  tests/circuit_drawer/test_grid.py
  tests/circuit_drawer/test_representation_resolver.py
  tests/circuit_graph/test_circuit_graph.py
  tests/qnodes/test_qnode_base.py
  tests/test_variable.py
Labels: core, enhancement, review-ready

#490 Import inv into qml namespace
  pennylane/__init__.py
  pennylane/utils.py
  tests/test_utils.py
Labels: core, review-ready, templates

#492 Move collections module to its own subpackage
  .github/CHANGELOG.md
  doc/introduction/templates.rst
  pennylane/collections.py
  pennylane/collections/__init__.py
  pennylane/collections/apply.py
  pennylane/collections/dot.py
  pennylane/collections/map.py
  pennylane/collections/qnode_collection.py
  pennylane/collections/sum.py
  setup.py
Labels: code quality, review-ready
