Repository PennyLaneAI/pennylane, pull requests merged in 2020-10, with the labels that each got.

#833 Fixing compatibility related to scalar NumPy tensors and hashing
  .github/CHANGELOG.md
  pennylane/numpy/tensor.py
  tests/test_numpy_wrapper.py
Labels: review-ready :ok_hand:

#761 Measurement optimization utilities
  pennylane/grouping/__init__.py
  pennylane/grouping/graph_colouring.py
  pennylane/grouping/group_observables.py
  pennylane/grouping/optimize_measurements.py
  pennylane/grouping/transformations.py
  pennylane/grouping/utils.py
  tests/test_graph_colouring.py
  tests/test_group_observables.py
  tests/test_grouping_utils.py
  tests/test_measurement_transformations.py
  tests/test_optimize_measurements.py
Labels: review-ready :ok_hand:

#841 Fix applying operations in default.qubit.tf when using 9 or more wires
  pennylane/devices/default_qubit_tf.py
  tests/devices/test_default_qubit_tf.py
Labels: bug :bug:, review-ready :ok_hand:

#836 Update changelog for measurement grouping
  .github/CHANGELOG.md
  pennylane/grouping/group_observables.py
  pennylane/grouping/utils.py
  tests/grouping/test_graph_colouring.py
  tests/grouping/test_group_observables.py
  tests/grouping/test_grouping_utils.py
  tests/grouping/test_optimize_measurements.py
Labels: merge-ready :heavy_check_mark:

#819 Adds a mixed-state simulator: part 3
  .github/CHANGELOG.md
  .github/workflows/tests.yml
  pennylane/devices/default_mixed.py
  tests/devices/test_default_mixed.py
Labels: devices :computer:

#844 Add batch_execute function to Device
  pennylane/_device.py
  pennylane/_qubit_device.py
  pennylane/tape/qnode.py
  pennylane/tape/tapes/jacobian_tape.py
  pennylane/tape/tapes/tape.py
  tests/tape/tapes/test_caching.py
  tests/test_device.py
  tests/test_qubit_device.py
Labels: review-ready :ok_hand:

#853 add execution property to Device class for tracking the number of device executions over a QNodes lifetime
  .github/CHANGELOG.md
  pennylane/_device.py
  pennylane/_qubit_device.py
  pennylane/qnodes/base.py
  tests/test_device.py
  tests/test_qubit_device.py
Labels: review-ready :ok_hand:

#860 Adds handling of single-qubit Paulis and all-identity Pauli to PauliRot operation.
  .github/CHANGELOG.md
  codecov.yml
  pennylane/ops/qubit.py
  tests/ops/test_qubit_ops.py
Labels: bug :bug:, review-ready :ok_hand:

#863 Updating collections and VQECost to work in tape mode
  .github/CHANGELOG.md
  pennylane/__init__.py
  pennylane/collections/map.py
  pennylane/collections/qnode_collection.py
  pennylane/tape/__init__.py
  pennylane/tape/measure.py
  pennylane/tape/tapes/cv_param_shift.py
  pennylane/tape/tapes/qubit_param_shift.py
  tests/collections/test_collections.py
  tests/collections/test_qnode_collection.py
  tests/conftest.py
  tests/tape/test_tape_mode.py
  tests/test_vqe.py
Labels: review-ready :ok_hand:

#854 Build many-body observables in PL-QChem using FermionOperator data structure
  qchem/CHANGELOG.md
  qchem/pennylane_qchem/qchem/obs.py
  qchem/tests/test_observable.py
  qchem/tests/test_one_particle.py
  qchem/tests/test_two_particle.py
Labels: qchem :atom_symbol:, review-ready :ok_hand:

#862 Adds basic resource estimation to quantum tapes.
  .github/CHANGELOG.md
  pennylane/tape/circuit_graph.py
  pennylane/tape/tapes/tape.py
  tests/tape/tapes/test_tape.py
Labels: enhancement :sparkles:, review-ready :ok_hand:

#865 Updating qnn.TorchLayer to work in tape mode
  .github/CHANGELOG.md
  pennylane/qnn/torch.py
  pennylane/tape/qnode.py
  tests/qnn/test_qnn_torch.py
Labels: review-ready :ok_hand:

#851 Make caching compatible with batch execution
  .github/CHANGELOG.md
  pennylane/_qubit_device.py
  pennylane/devices/default_mixed.py
  pennylane/devices/default_qubit.py
  pennylane/devices/default_qubit_autograd.py
  pennylane/devices/default_qubit_tf.py
  pennylane/tape/qnode.py
  pennylane/tape/tapes/jacobian_tape.py
  pennylane/tape/tapes/tape.py
  tests/devices/test_caching.py
  tests/tape/tapes/test_caching.py
  tests/tape/tapes/test_tape.py
Labels: review-ready :ok_hand:

#880 Update the templates quickstart to emphasize the templates gallery
  doc/introduction/templates.rst
Labels: documentation :blue_book:, review-ready :ok_hand:

#872 default_qubit to use the hard-coded inverses
  .github/CHANGELOG.md
  pennylane/devices/default_qubit.py
Labels: merge-ready :heavy_check_mark:
