Repository PennyLaneAI/pennylane, pull requests merged in 2021-02, with the labels that each got.

#1058 Fix for #1056
  pennylane/templates/layers/cv_neural_net.py
Labels: bug :bug:

#1060 Fix bug in CV second order parameter-shift formula, where the incorrect parameter is being differentiated
  pennylane/tape/tapes/cv_param_shift.py
Labels: bug :bug:

#1055 Update the changelog for the next release, and bump the version number
  .github/CHANGELOG.md
  pennylane/_version.py
Labels: review-ready :ok_hand:

#1064 Adds the quantum fourier transform and controlled phase operations
  .github/CHANGELOG.md
  doc/introduction/operations.rst
  pennylane/devices/autograd_ops.py
  pennylane/devices/default_mixed.py
  pennylane/devices/default_qubit.py
  pennylane/devices/default_qubit_autograd.py
  pennylane/devices/default_qubit_jax.py
  pennylane/devices/default_qubit_tf.py
  pennylane/devices/jax_ops.py
  pennylane/devices/tests/test_gates.py
  pennylane/devices/tf_ops.py
  pennylane/ops/qubit.py
  tests/devices/test_default_qubit_tf.py
  tests/gate_data.py
  tests/ops/test_qubit_ops.py
  tests/tape/tapes/test_reversible.py
Labels: review-ready :ok_hand:

#1066 Add fixture to skip test if jax is not present
  tests/conftest.py
  tests/qnn/test_cost.py
Labels: review-ready :ok_hand:

#1062 Add support for broadcasting over multi-dimensional inputs in KerasLayer and TorchLayer
  .github/CHANGELOG.md
  pennylane/qnn/keras.py
  pennylane/qnn/torch.py
  tests/qnn/test_keras.py
  tests/qnn/test_qnn_torch.py
Labels: enhancement :sparkles:

#1067 Fix qml.grad so that the returned gradient always matches the cost function return type if only a single argument is differentiated
  .github/CHANGELOG.md
  pennylane/_grad.py
  pennylane/optimize/gradient_descent.py
  pennylane/optimize/nesterov_momentum.py
  tests/devices/test_default_qubit_autograd.py
  tests/interfaces/test_autograd.py
  tests/math/test_autograd_box.py
  tests/math/test_functions.py
  tests/tape/interfaces/test_qnode_autograd.py
  tests/test_classical_gradients.py
Labels: bug :bug:

#1076 Jax interface for all devices.
  .github/CHANGELOG.md
  pennylane/tape/interfaces/jax.py
  pennylane/tape/qnode.py
  tests/devices/test_default_qubit_jax.py
  tests/tape/interfaces/test_qnode_jax.py
  tests/tape/interfaces/test_tape_jax.py
Labels: merge-ready :heavy_check_mark:, review-ready :ok_hand:

#1072 Fixes a bug where inverse operations could not be differentiated using backprop
  .github/CHANGELOG.md
  pennylane/devices/default_qubit_autograd.py
  pennylane/devices/default_qubit_jax.py
  pennylane/devices/default_qubit_tf.py
  tests/devices/test_default_qubit_autograd.py
  tests/devices/test_default_qubit_jax.py
  tests/devices/test_default_qubit_tf.py
Labels: bug :bug:

#1082 Update Hamiltonian data storing and result of ExpvalCost for trivial Hamiltonians
  .github/CHANGELOG.md
  pennylane/vqe/vqe.py
  tests/test_vqe.py
Labels: bug :bug:

#1069 Add controlled unitary gate
  .github/CHANGELOG.md
  doc/introduction/operations.rst
  pennylane/devices/default_mixed.py
  pennylane/devices/default_qubit.py
  pennylane/devices/tests/test_gates.py
  pennylane/ops/qubit.py
  tests/ops/test_qubit_ops.py
  tests/test_operation.py
Labels: review-ready :ok_hand:

#1088 Micro-optimize basis state conversion
  .github/CHANGELOG.md
  pennylane/_qubit_device.py
Labels: review-ready :ok_hand:

#1103 [SHOTS] Allows a list of shots to be specified
  .github/CHANGELOG.md
  doc/introduction/circuits.rst
  pennylane/_device.py
  pennylane/_qubit_device.py
  tests/test_qubit_device.py
Labels: review-ready :ok_hand:
