Repository PennyLaneAI/pennylane, pull requests merged in 2021-03, with the labels that each got.

#1070 Added support for output_dim to be a tuple
  .github/CHANGELOG.md
  pennylane/qnn/keras.py
  tests/qnn/conftest.py
  tests/qnn/test_keras.py
Labels: enhancement :sparkles:

#1117 Fixes a bug where decompositions would reset the differentiation method of a QNode
  .github/CHANGELOG.md
  pennylane/tape/qnode.py
  tests/tape/tapes/test_qnode.py
Labels: bug :bug:

#1081 Fix qml.grad so that the returned gradient always matches the cost function return type if only a single argument is differentiated
  .github/CHANGELOG.md
  pennylane/_grad.py
  pennylane/optimize/gradient_descent.py
  pennylane/optimize/nesterov_momentum.py
  tests/devices/test_default_qubit_autograd.py
  tests/interfaces/test_autograd.py
  tests/math/test_autograd_box.py
  tests/math/test_functions.py
  tests/tape/interfaces/test_qnode_autograd.py
  tests/test_classical_gradients.py
Labels: merge-ready :heavy_check_mark:

#1114 Fix BasisEmbedding to allow only-1 bitstrings
  .github/CHANGELOG.md
  pennylane/templates/embeddings/basis.py
  tests/templates/test_embeddings.py
Labels: bug :bug:

#1078 Modify qchem functions to separately take the atomic symbols and coordinates
  qchem/CHANGELOG.md
  qchem/pennylane_qchem/qchem/structure.py
  qchem/tests/test_meanfield.py
  qchem/tests/test_molecular_hamiltonian.py
  qchem/tests/test_read_structure.py
Labels: qchem :atom_symbol:, review-ready :ok_hand:

#1087 Add details on gradient methods to the quickstart
  doc/introduction/interfaces.rst
  doc/introduction/interfaces/numpy.rst
Labels: documentation :blue_book:

#1126 Fix is_sampled and its test
  .github/CHANGELOG.md
  pennylane/tape/tapes/tape.py
  tests/tape/tapes/test_tape.py
Labels: bug :bug:

#1111 adjoint transform
  .github/CHANGELOG.md
  pennylane/__init__.py
  pennylane/operation.py
  pennylane/ops/qubit.py
  pennylane/tape/tapes/jacobian_tape.py
  pennylane/tape/tapes/tape.py
  pennylane/tape/transforms/adjoint.py
  tests/ops/test_qubit_ops.py
  tests/tape/transforms/test_adjoint.py
Labels: merge-ready :heavy_check_mark:, review-ready :ok_hand:

#1135 Added adjoints for some CV gates
  .github/CHANGELOG.md
  pennylane/ops/cv.py
  tests/ops/test_cv_ops.py
Labels: review-ready :ok_hand:

#1130 Add quantum Monte Carlo template
  .github/CHANGELOG.md
  doc/_static/templates/subroutines/qmc.pdf
  doc/_static/templates/subroutines/qmc.svg
  doc/_static/templates/subroutines/qmc.tex
  doc/code/qml_templates.rst
  doc/introduction/templates.rst
  pennylane/templates/subroutines/__init__.py
  pennylane/templates/subroutines/qmc.py
  tests/templates/test_subroutines_qmc.py
Labels: review-ready :ok_hand:

#1090 Add finite difference function to compute the gradient and second-order derivatives of parametrized observables
  .github/CHANGELOG.md
  pennylane/__init__.py
  pennylane/_grad.py
  qchem/tests/test_deriv_hamilt.py
  tests/test_finite_diff.py
Labels: qchem :atom_symbol:, review-ready :ok_hand:

#1121 Adds Single Excitation operations
  .github/CHANGELOG.md
  doc/introduction/operations.rst
  pennylane/devices/autograd_ops.py
  pennylane/devices/default_mixed.py
  pennylane/devices/default_qubit.py
  pennylane/devices/default_qubit_autograd.py
  pennylane/devices/default_qubit_jax.py
  pennylane/devices/default_qubit_tf.py
  pennylane/devices/jax_ops.py
  pennylane/devices/tests/test_gates.py
  pennylane/devices/tf_ops.py
  pennylane/ops/qubit.py
  tests/gate_data.py
  tests/ops/test_qubit_ops.py
  tests/tape/test_reversible.py
Labels: core :atom:, qchem :atom_symbol:

#1123 Adds Double Excitation operations
  .github/CHANGELOG.md
  doc/introduction/operations.rst
  pennylane/devices/autograd_ops.py
  pennylane/devices/default_mixed.py
  pennylane/devices/default_qubit.py
  pennylane/devices/default_qubit_autograd.py
  pennylane/devices/default_qubit_jax.py
  pennylane/devices/default_qubit_tf.py
  pennylane/devices/jax_ops.py
  pennylane/devices/tests/test_gates.py
  pennylane/devices/tf_ops.py
  pennylane/ops/qubit.py
  tests/gate_data.py
  tests/ops/test_qubit_ops.py
  tests/tape/test_reversible.py
Labels: core :atom:, qchem :atom_symbol:

#827 Correct typos in docstrings of the controlled rotation operations
  doc/_static/crx_circuit.png
  doc/_static/cry_circuit.png
  doc/_static/crz_circuit.png
  pennylane/ops/qubit.py
Labels: documentation :blue_book:

#1144 Mottonen state prep edit
  .github/CHANGELOG.md
  pennylane/templates/state_preparations/mottonen.py
  tests/templates/test_state_preparations.py
Labels: merge-ready :heavy_check_mark:
