Repository PennyLaneAI/pennylane, pull requests merged in 2021-06, with the labels that each got.

#1376 Fixes a bug where `qml.ctrl` would fail to transform gates that had no control defined and no decomposition defined.
  .github/CHANGELOG.md
  pennylane/transforms/control.py
  tests/transforms/test_control.py
Labels: bug :bug:, review-ready :ok_hand:

#1381 First-order finite-diff differentiation with float32 parameters
  .github/CHANGELOG.md
  pennylane/devices/tests/test_compare_default_qubit.py
  pennylane/tape/jacobian_tape.py
  tests/tape/test_qnode.py
Labels: review-ready :ok_hand:

#1315 Add convenience decorators for creating qfunc transforms
  .github/CHANGELOG.md
  pennylane/__init__.py
  pennylane/transforms/__init__.py
  pennylane/transforms/qfunc_transforms.py
  tests/transforms/test_qfunc_transform.py
Labels: review-ready :ok_hand:

#1380 add the jax interface to sum() and dot()
  .github/CHANGELOG.md
  pennylane/collections/dot.py
  pennylane/collections/qnode_collection.py
  pennylane/collections/sum.py
  tests/collections/conftest.py
  tests/collections/test_collections.py
Labels: bug :bug:

#1341 Adjoint differentation improvements
  .github/CHANGELOG.md
  pennylane/_qubit_device.py
  pennylane/interfaces/jax.py
  pennylane/interfaces/tf.py
  pennylane/interfaces/torch.py
  pennylane/qnode.py
  pennylane/tape/jacobian_tape.py
  tests/interfaces/test_qnode_autograd.py
  tests/interfaces/test_qnode_jax.py
  tests/interfaces/test_qnode_tf.py
  tests/interfaces/test_qnode_torch.py
  tests/test_qubit_device_adjoint_jacobian.py
Labels: review-ready :ok_hand:

#1371 Allow specifying a subset of parameters to estimate the jacobian by passing the `argnum` kwarg
  .github/CHANGELOG.md
  pennylane/qnode.py
  pennylane/tape/jacobian_tape.py
  tests/tape/test_jacobian_tape.py
  tests/tape/test_qnode.py
Labels: review-ready :ok_hand:

#1383 Add template to prepare quantum states of molecules using the excitation operations
  .github/CHANGELOG.md
  doc/_static/templates/subroutines/all_singles_doubles.png
  doc/introduction/templates.rst
  pennylane/templates/subroutines/__init__.py
  pennylane/templates/subroutines/all_singles_doubles.py
  tests/templates/test_subroutines/test_all_singles_doubles.py
Labels: qchem :atom_symbol:, review-ready :ok_hand:, templates :file_folder:

#1245 specs transform
  .github/CHANGELOG.md
  pennylane/__init__.py
  pennylane/qnode.py
  pennylane/tape/qubit_param_shift.py
  pennylane/tape/tape.py
  pennylane/transforms/__init__.py
  pennylane/transforms/draw.py
  pennylane/transforms/specs.py
  tests/tape/test_qnode.py
  tests/tape/test_qubit_param_shift.py
  tests/tape/test_tape.py
  tests/transforms/test_specs.py
Labels: review-ready :ok_hand:

#1394 Add function to compute sparse Hamiltonian matrix
  .github/CHANGELOG.md
  pennylane/utils.py
  tests/test_utils.py
Labels: review-ready :ok_hand:

#1358 [unitaryHACK] Add the YY gate
  .github/CHANGELOG.md
  doc/introduction/operations.rst
  pennylane/devices/default_qubit.py
  pennylane/devices/tests/test_gates.py
  pennylane/ops/qubit.py
  tests/devices/test_default_qubit.py
  tests/ops/test_qubit_ops.py
  tests/tape/test_reversible.py
Labels: unitaryhack

#1411 Copy for `ControlledQubitUnitary`
  .github/CHANGELOG.md
  pennylane/operation.py
  tests/ops/test_qubit_ops.py
Labels: review-ready :ok_hand:

#1430 Change `h5py` version to 3.2.1 due to failing `Qchem`tests
  qchem/CHANGELOG.md
  qchem/requirements.txt
  qchem/setup.py
Labels: bug :bug:, dependencies :pushpin:

#1426 Fix backward pass on GPU in PyTorch interface
  .github/CHANGELOG.md
  pennylane/interfaces/torch.py
Labels: bug :bug:

#1433 Add function to apply instantiated operations to queuing contexts
  .github/CHANGELOG.md
  pennylane/__init__.py
  pennylane/measure.py
  pennylane/operation.py
  pennylane/queuing.py
  pennylane/vqe/vqe.py
  tests/collections/test_collections.py
  tests/test_queuing.py
  tests/test_vqe.py
Labels: review-ready :ok_hand:
