Repository PennyLaneAI/pennylane, pull requests merged in 2021-05, with the labels that each got.

#1271 Update QNode docstring
  .github/CHANGELOG.md
  pennylane/qnode.py
Labels: documentation :blue_book:

#1277 Fix issue #1266: 'convert_observable' function raises an error for QubitOperators containing complex coefficients
  qchem/CHANGELOG.md
  qchem/pennylane_qchem/qchem/structure.py
  qchem/tests/test_convert_observable.py
Labels: qchem :atom_symbol:, review-ready :ok_hand:

#1297 Finalize max-weight-cycle qaoa addition
  .github/CHANGELOG.md
  doc/code/qml_qaoa.rst
Labels: review-ready :ok_hand:

#1287 Add decomposition for MultiControlledX gate
  .github/CHANGELOG.md
  pennylane/circuit_drawer/representation_resolver.py
  pennylane/ops/qubit.py
  tests/circuit_drawer/test_circuit_drawer.py
  tests/ops/test_qubit_ops.py
  tests/test_operation.py
Labels: review-ready :ok_hand:

#1298 Add the ISWAP operation to default_qubit device
  .github/CHANGELOG.md
  doc/introduction/operations.rst
  pennylane/devices/default_qubit.py
  pennylane/devices/tests/test_gates.py
  pennylane/ops/qubit.py
  tests/devices/test_default_qubit.py
  tests/gate_data.py
  tests/ops/test_qubit_ops.py
Labels: enhancement :sparkles:

#1329 [unitaryHACK] Added SWAP gate decomposition and related tests
  .github/CHANGELOG.md
  pennylane/ops/qubit.py
  tests/ops/test_qubit_ops.py
Labels: unitaryhack

#1325 [unitaryHACK] Deprecated qml.inv()
  .github/CHANGELOG.md
  pennylane/utils.py
  tests/test_utils.py
Labels: unitaryhack

#1320 [unitaryHACK] Toffoli Decomposition
  .github/CHANGELOG.md
  pennylane/ops/qubit.py
  tests/ops/test_qubit_ops.py
  tests/transforms/test_control.py
Labels: unitaryhack

#1319 [unitaryHACK] Add the CPhase operation
  .github/CHANGELOG.md
  pennylane/devices/default_qubit.py
  pennylane/devices/default_qubit_autograd.py
  pennylane/devices/default_qubit_jax.py
  pennylane/devices/default_qubit_tf.py
  pennylane/ops/qubit.py
  tests/ops/test_qubit_ops.py
  tests/tape/test_reversible.py
Labels: unitaryhack

#1194 [unitaryHACK] Add the XX operation
  .github/CHANGELOG.md
  pennylane/devices/default_qubit.py
  pennylane/devices/tests/test_gates.py
  pennylane/ops/qubit.py
  tests/devices/test_default_qubit.py
  tests/ops/test_qubit_ops.py
  tests/tape/test_reversible.py
Labels: unitaryhack

#1321 [unitaryHACK] Add reset error to noise channels
  .github/CHANGELOG.md
  pennylane/ops/channel.py
  tests/ops/test_channel_ops.py
Labels: unitaryhack

#1338 Fix ControlledPhaseShift
  .github/CHANGELOG.md
  pennylane/ops/qubit.py
  tests/ops/test_qubit_ops.py
Labels: bug :bug:

#1199 [unitaryhack] Adds a new ZZ operation
  .github/CHANGELOG.md
  doc/introduction/operations.rst
  pennylane/devices/default_qubit.py
  pennylane/devices/tests/test_gates.py
  pennylane/ops/qubit.py
  tests/devices/test_default_qubit.py
  tests/ops/test_qubit_ops.py
  tests/tape/test_reversible.py
Labels: unitaryhack

#1342 [unitaryhack] Add decomposition for qml.CSWAP #1306
  .github/CHANGELOG.md
  pennylane/ops/qubit.py
  tests/ops/test_qubit_ops.py
Labels: unitaryhack

#1333 [unitaryHACK] Update interface introduction
  .github/CHANGELOG.md
  doc/introduction/interfaces/tf.rst
  doc/introduction/interfaces/torch.rst
Labels: unitaryhack

#1353 Fix CircuitDrawer single wire multiple observables
  .github/CHANGELOG.md
  pennylane/circuit_graph.py
  tests/circuit_drawer/test_circuit_drawer.py
  tests/circuit_graph/test_circuit_graph.py
Labels: bug :bug:

#1359 [unitaryHACK] Added `__repr__` method for QNode
  .github/CHANGELOG.md
  pennylane/qnode.py
  tests/tape/test_qnode.py
Labels: unitaryhack

#1357 Add validation for noise channels parameters
  .github/CHANGELOG.md
  pennylane/ops/channel.py
  tests/ops/test_channel_ops.py
Labels: bug :bug:

#1367 Fixing a bug in the documentation of StronglyEntanglingLayers
  .github/CHANGELOG.md
  pennylane/templates/layers/strongly_entangling.py
Labels: bug :bug:

#1356 [unitaryhack] Add a projector observable
  .github/CHANGELOG.md
  doc/introduction/operations.rst
  pennylane/_qubit_device.py
  pennylane/devices/default_qubit.py
  pennylane/devices/tests/test_compare_default_qubit.py
  pennylane/devices/tests/test_measurements.py
  pennylane/ops/qubit.py
  tests/ops/test_qubit_ops.py
  tests/test_operation.py
Labels: unitaryhack
