Repository PennyLaneAI/pennylane, pull requests merged in 2021-08, with the labels that each got.

#1487 added grad_fn kwarg to QNGOptimizer.step_and_cost and .step
  .github/CHANGELOG.md
  pennylane/optimize/gradient_descent.py
  pennylane/optimize/qng.py
  tests/test_optimize_qng.py
Labels: enhancement :sparkles:

#1490 Add support for unwrapping of parameters, and determining trainability
  .github/CHANGELOG.md
  pennylane/math/__init__.py
  pennylane/math/multi_dispatch.py
  pennylane/math/single_dispatch.py
  pennylane/math/utils.py
  tests/math/test_functions.py
Labels: review-ready :ok_hand:

#1479 Differentiable parameter-shift gradient transform
  pennylane/gradients/__init__.py
  pennylane/gradients/finite_difference.py
  pennylane/gradients/parameter_shift.py
  tests/gradients/test_parameter_shift.py
Labels: review-ready :ok_hand:

#1491 Add a tape unwrapping context manager
  .github/CHANGELOG.md
  pennylane/math/single_dispatch.py
  pennylane/tape/__init__.py
  pennylane/tape/tape.py
  pennylane/tape/unwrap.py
  tests/math/test_functions.py
  tests/tape/test_unwrap.py
Labels: review-ready :ok_hand:

#1486 (non)Differentiable CV parameter-shift gradient transform
  .github/CHANGELOG.md
  pennylane/gradients/__init__.py
  pennylane/gradients/finite_difference.py
  pennylane/gradients/parameter_shift_cv.py
  pennylane/operation.py
  pennylane/tape/jacobian_tape.py
  tests/gradients/test_parameter_shift_cv.py
  tests/tape/test_jacobian_tape.py
Labels: review-ready :ok_hand:

#1525 Fix GitHub issue #1265
  qchem/CHANGELOG.md
  qchem/pennylane_qchem/qchem/structure.py
  qchem/tests/test_convert_observable.py
Labels: review-ready :ok_hand:

#1494 Adds a differentiable VJP transform
  .github/CHANGELOG.md
  pennylane/gradients/__init__.py
  pennylane/gradients/vjp.py
  pennylane/math/utils.py
  tests/gradients/test_vjp.py
Labels: review-ready :ok_hand:

#1501 Differentiable batch execute using autograd
  .github/CHANGELOG.md
  pennylane/_device.py
  pennylane/gradients/vjp.py
  pennylane/interfaces/batch/__init__.py
  pennylane/interfaces/batch/autograd.py
  tests/gradients/test_vjp.py
  tests/interfaces/test_batch_autograd.py
Labels: review-ready :ok_hand:

#1536 Update changelog entry for #1388
  .github/CHANGELOG.md
Labels: review-ready :ok_hand:

#1508 Add caching to the autograd batch interface
  .github/CHANGELOG.md
  pennylane/interfaces/batch/__init__.py
  pennylane/interfaces/batch/autograd.py
  pennylane/measure.py
  pennylane/operation.py
  pennylane/tape/tape.py
  requirements.txt
  setup.py
  tests/interfaces/test_batch_autograd.py
  tests/tape/test_tape.py
Labels: review-ready :ok_hand:

#1489 Generalize Rotosolve
  .github/CHANGELOG.md
  pennylane/optimize/rotosolve.py
  tests/optimize/test_optimize.py
  tests/optimize/test_qng.py
  tests/optimize/test_rotosolve.py
  tests/test_optimize_shot_adaptive.py
Labels: review-ready :ok_hand:

#1549 Differentiable batch execute using PyTorch
  .github/CHANGELOG.md
  pennylane/gradients/parameter_shift.py
  pennylane/gradients/vjp.py
  pennylane/interfaces/batch/__init__.py
  pennylane/interfaces/batch/torch.py
  pennylane/math/single_dispatch.py
  pennylane/math/utils.py
  tests/interfaces/test_batch_torch.py
Labels: review-ready :ok_hand:

#1596 Vectorize and remove for loop in sparse expvals
  .github/CHANGELOG.md
  pennylane/devices/default_qubit.py
  pennylane/utils.py
  tests/ops/test_sparse.py
Labels: review-ready :ok_hand:

#1589 Add a simple API for gradient transforms
  .github/CHANGELOG.md
  pennylane/_grad.py
  pennylane/gradients/__init__.py
  pennylane/gradients/finite_difference.py
  pennylane/gradients/gradient_transform.py
  pennylane/gradients/parameter_shift.py
  pennylane/gradients/parameter_shift_cv.py
  pennylane/interfaces/batch/autograd.py
  pennylane/interfaces/batch/torch.py
  pennylane/transforms/batch_transform.py
  tests/gradients/test_finite_difference.py
  tests/gradients/test_gradient_transform.py
  tests/gradients/test_parameter_shift.py
  tests/gradients/test_parameter_shift_cv.py
Labels: review-ready :ok_hand:

#1594 Adds the `qml.gradients` module to the documentation
  doc/code/qml_gradients.rst
  doc/index.rst
  pennylane/gradients/__init__.py
  pennylane/gradients/finite_difference.py
  pennylane/gradients/parameter_shift.py
  pennylane/gradients/parameter_shift_cv.py
Labels: review-ready :ok_hand:

#1582 Add basis set functions for HF solver
  .github/CHANGELOG.md
  pennylane/hf/basis_data.py
  pennylane/hf/basis_set.py
  tests/hf/test_basis_set.py
Labels: qchem :atom_symbol:

#1615 `qml.layer` support for tensorflow `Variable`
  .github/CHANGELOG.md
  pennylane/templates/layer.py
  tests/templates/test_layer.py
Labels: bug :bug:
