Repository PennyLaneAI/pennylane, pull requests merged in 2021-11, with the labels that each got.

#1827 Pin PySCF to version < 2.0
  doc/development/guide/installation.rst
  qchem/README.rst
  qchem/requirements.txt
  qchem/setup.py
Labels: review-ready :ok_hand:

#1766 Add noisy channel: thermal relaxation
  doc/releases/changelog-dev.md
  pennylane/devices/default_mixed.py
  pennylane/ops/channel.py
  tests/ops/test_channel_ops.py
Labels: hacktoberfest-accepted

#1842 Fix bug to ensure qml.math.dot works in autograph mode
  doc/releases/changelog-dev.md
  pennylane/math/multi_dispatch.py
  tests/math/test_functions.py
Labels: bug :bug:

#1854 Modify 'qchem.meanfield' function to avoid creating a directory tree
  qchem/CHANGELOG.md
  qchem/pennylane_qchem/qchem/structure.py
  qchem/tests/test_meanfield.py
Labels: review-ready :ok_hand:, qchem :atom_symbol:

#1863 Hide :orphan: from displaying in the release notes
  doc/xanadu_theme/layout.html
Labels: documentation :blue_book:

#1839 Add documentation for the hf module
  doc/code/qml_hf.rst
  doc/introduction/chemistry.rst
Labels: documentation :blue_book:, qchem :atom_symbol:

#1856 Fix for issue 1848. Pickling and unpickling a qml.numpy.tensor object does not preserve requires_grad attribute
  doc/releases/changelog-dev.md
  pennylane/numpy/tensor.py
  tests/numpy/test_pickling.py
Labels: bug :bug:

#1787 matplotlib circuit drawer integration (tape)
  doc/_static/draw_mpl/Solarize_Light2.png
  doc/_static/draw_mpl/decimals.png
  doc/_static/draw_mpl/default.png
  doc/_static/draw_mpl/draw_mpl_examples.py
  doc/_static/draw_mpl/postprocessing.png
  doc/_static/draw_mpl/rcparams.png
  doc/_static/draw_mpl/show_all_wires.png
  doc/_static/draw_mpl/wire_order.png
  doc/_static/draw_mpl/wires_labels.png
  doc/_static/drawer/example_Solarize_Light2.png
  doc/_static/drawer/example_basic.png
  doc/_static/drawer/example_rcParams.png
  doc/development/guide/tests.rst
  doc/releases/changelog-dev.md
  pennylane/circuit_drawer/__init__.py
  pennylane/circuit_drawer/draw_mpl.py
  pennylane/circuit_drawer/utils.py
  pennylane/operation.py
  tests/circuit_drawer/test_draw_mpl.py
  tests/circuit_drawer/test_mpldrawer.py
  tests/ops/qubit/test_parametric_ops.py
  tests/ops/test_cv_ops.py
Labels: review-ready :ok_hand:

#1899 Update matplotlib circuit drawing to work with matplotlib v3.5
  doc/releases/changelog-dev.md
  pennylane/circuit_drawer/mpldrawer.py
Labels: bug :bug:

#1892 Temporary fix for Issue #1841
  doc/releases/changelog-dev.md
  pennylane/circuit_drawer/circuit_drawer.py
  pennylane/circuit_graph.py
  pennylane/qnode.py
  pennylane/tape/tape.py
  pennylane/transforms/draw.py
  tests/circuit_drawer/test_circuit_drawer.py
  tests/transforms/test_draw.py
Labels: bug :bug:

#1896 Testing documentation
  doc/development/guide/tests.rst
  doc/releases/changelog-dev.md
Labels: documentation :blue_book:

#1807 Make the new QNode default
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/beta/__init__.py
  pennylane/beta/qnode.py
  pennylane/devices/tests/test_properties.py
  pennylane/gradients/hamiltonian_grad.py
  pennylane/interfaces/batch/autograd.py
  pennylane/interfaces/batch/tensorflow.py
  pennylane/interfaces/batch/torch.py
  pennylane/math/single_dispatch.py
  pennylane/measure.py
  pennylane/qnode.py
  pennylane/qnode_old.py
  pennylane/tape/unwrap.py
  pennylane/transforms/batch_transform.py
  pennylane/transforms/mitigate.py
  pennylane/transforms/specs.py
  tests/beta/test_default_tensor_tf.py
  tests/collections/test_collections.py
  tests/devices/test_default_qubit_autograd.py
  tests/devices/test_default_qubit_tf.py
  tests/devices/test_default_qubit_torch.py
  tests/gradients/test_gradient_transform.py
  tests/interfaces/test_batch_autograd_qnode.py
  tests/interfaces/test_batch_jax_qnode.py
  tests/interfaces/test_batch_tensorflow_qnode.py
  tests/interfaces/test_batch_torch_qnode.py
  tests/interfaces/test_qnode_autograd.py
  tests/interfaces/test_qnode_jax.py
  tests/interfaces/test_qnode_tf.py
  tests/interfaces/test_qnode_torch.py
  tests/interfaces/test_tape_torch.py
  tests/ops/qubit/test_hamiltonian.py
  tests/qnn/conftest.py
  tests/tape/test_jacobian_tape.py
  tests/tape/test_qnode_old.py
  tests/tape/test_reversible.py
  tests/tape/test_unwrap.py
  tests/test_measure.py
  tests/test_qnode.py
  tests/test_quantum_gradients.py
  tests/test_qubit_device_adjoint_jacobian.py
  tests/test_tensor_measurements.py
  tests/test_tracker.py
  tests/test_vqe.py
  tests/transforms/test_batch_params.py
  tests/transforms/test_batch_transform.py
  tests/transforms/test_draw.py
  tests/transforms/test_metric_tensor.py
  tests/transforms/test_mitigate.py
  tests/transforms/test_specs.py
Labels: review-ready :ok_hand:

#1917 Bugfix: draw template with matrix parameter
  doc/releases/changelog-dev.md
  pennylane/circuit_drawer/representation_resolver.py
  tests/transforms/test_draw.py
Labels: bug :bug:

#1934 Fixes a bug where batch transforms would mutate a QNodes execution options
  doc/releases/changelog-dev.md
  pennylane/transforms/batch_transform.py
  tests/transforms/test_batch_transform.py
Labels: bug :bug:
