Repository PennyLaneAI/pennylane, pull requests merged in 2021-01, with the labels that each got.

#961 Implement Hessian support to JacobianTape
  .github/CHANGELOG.md
  pennylane/tape/tapes/jacobian_tape.py
  pennylane/tape/tapes/qubit_param_shift.py
  tests/tape/tapes/test_jacobian_tape.py
  tests/tape/tapes/test_qubit_param_shift.py
Labels: review-ready :ok_hand:

#959 Allowing more flexible cost functions for optimizers
  .github/CHANGELOG.md
  pennylane/optimize/adagrad.py
  pennylane/optimize/adam.py
  pennylane/optimize/gradient_descent.py
  pennylane/optimize/momentum.py
  pennylane/optimize/nesterov_momentum.py
  pennylane/optimize/qng.py
  pennylane/optimize/rms_prop.py
  pennylane/optimize/rotoselect.py
  pennylane/optimize/rotosolve.py
  tests/test_optimize.py
Labels: review-ready :ok_hand:

#986 Run CI with TensorFlow 2.4
  .github/workflows/tests.yml
Labels: CI :wrench:

#985 Added JAX support to qml.math
  .github/CHANGELOG.md
  pennylane/math/fn.py
  pennylane/math/jax_box.py
  pennylane/math/tensorbox.py
  tests/devices/test_default_qubit_jax.py
  tests/math/test_functions.py
  tests/math/test_jax_box.py
Labels: review-ready :ok_hand:

#995 avoid redefining a build-in type
  doc/requirements.txt
  pennylane/circuit_graph.py
Labels: review-ready :ok_hand:

#984 Added JAX interface documentation to readthedocs
  doc/_static/jax.png
  doc/introduction/interfaces.rst
  doc/introduction/interfaces/jax.rst
Labels: documentation :blue_book:, merge-ready :heavy_check_mark:, review-ready :ok_hand:

#992 Run the circuit drawer tests in tape mode
  .github/CHANGELOG.md
  pennylane/circuit_graph.py
  pennylane/qnodes/base.py
  pennylane/tape/qnode.py
  pennylane/tape/tapes/tape.py
  pennylane/variable.py
  tests/circuit_drawer/test_circuit_drawer.py
  tests/circuit_drawer/test_grid.py
  tests/circuit_drawer/test_representation_resolver.py
Labels: review-ready :ok_hand:

#1007 Fix bug where a QNode with a single probability output was not correctly differentiated
  .github/CHANGELOG.md
  pennylane/tape/tapes/qubit_param_shift.py
  tests/tape/interfaces/test_qnode_autograd.py
Labels: bug :bug:

#1005 Faster wire combining.
  pennylane/wires.py
Labels: core :atom:, merge-ready :heavy_check_mark:, performance :timer_clock:, review-ready :ok_hand:

#1012 [Metric tensor tape] Covariance matrix support
  .github/CHANGELOG.md
  pennylane/math/__init__.py
  pennylane/math/autograd_box.py
  pennylane/math/fn.py
  pennylane/math/jax_box.py
  pennylane/math/numpy_box.py
  pennylane/math/tensorbox.py
  pennylane/math/tf_box.py
  pennylane/math/torch_box.py
  tests/math/test_functions.py
Labels: review-ready :ok_hand:

#1008 Change the default gradient method logic to prefer devices, and to allow backprop on child devices
  .github/CHANGELOG.md
  pennylane/devices/default_qubit.py
  pennylane/devices/default_qubit_autograd.py
  pennylane/tape/qnode.py
  tests/collections/test_collections.py
  tests/devices/test_default_qubit.py
  tests/devices/test_default_qubit_autograd.py
  tests/devices/test_default_qubit_jax.py
  tests/devices/test_default_qubit_tf.py
  tests/tape/interfaces/test_qnode_autograd.py
  tests/tape/interfaces/test_qnode_tf.py
  tests/tape/interfaces/test_qnode_torch.py
  tests/tape/tapes/test_qnode.py
  tests/tape/test_tape_measure.py
  tests/templates/test_embeddings.py
  tests/templates/test_integration.py
  tests/templates/test_layers.py
  tests/templates/test_state_preparations.py
  tests/test_vqe.py
Labels: review-ready :ok_hand:

#1025 Update default qubit so that _apply_operation is more functional
  .github/CHANGELOG.md
  pennylane/devices/default_qubit.py
Labels: review-ready :ok_hand:

#1014 [Metric tensor tape] Adds a metric tensor function
  .github/CHANGELOG.md
  doc/code/qml_tape.rst
  pennylane/__init__.py
  pennylane/math/__init__.py
  pennylane/math/autograd_box.py
  pennylane/math/fn.py
  pennylane/math/jax_box.py
  pennylane/math/numpy_box.py
  pennylane/math/tensorbox.py
  pennylane/math/tf_box.py
  pennylane/math/torch_box.py
  pennylane/tape/__init__.py
  pennylane/tape/qnode.py
  pennylane/tape/tapes/tape.py
  pennylane/tape/transforms/__init__.py
  pennylane/tape/transforms/metric_tensor.py
  tests/math/test_functions.py
  tests/tape/transforms/test_metric_tensor.py
Labels: review-ready :ok_hand:

#1034 Makes QNode integration tests more robust and fixes uncovered bugs
  pennylane/tape/tapes/qubit_param_shift.py
  tests/tape/interfaces/test_qnode_autograd.py
  tests/tape/interfaces/test_qnode_tf.py
  tests/tape/interfaces/test_qnode_torch.py
Labels: bug :bug:, tests :test_tube:

#1027 Tape expansion reserves value of the is_sampled attribute
  .github/CHANGELOG.md
  pennylane/tape/operation.py
  pennylane/tape/tapes/tape.py
  tests/tape/tapes/test_tape.py
Labels: bug :bug:

#1033 Add support for drawing unused wires
  .github/CHANGELOG.md
  pennylane/circuit_drawer/circuit_drawer.py
  pennylane/circuit_graph.py
  pennylane/qnodes/base.py
  pennylane/tape/qnode.py
  pennylane/tape/tapes/tape.py
  tests/circuit_drawer/test_circuit_drawer.py
Labels: bug :bug:, review-ready :ok_hand:

#1035 Move test monkeypatches to default.qubit.autograd and default.qubit.tf
  pennylane/devices/default_qubit_autograd.py
  pennylane/devices/default_qubit_tf.py
  pennylane/tape/qnode.py
  tests/tape/interfaces/test_qnode_autograd.py
  tests/tape/interfaces/test_qnode_tf.py
Labels: review-ready :ok_hand:

#1032 Add adjoint differentiation method
  .github/CHANGELOG.md
  pennylane/_qubit_device.py
  pennylane/operation.py
  pennylane/tape/qnode.py
  pennylane/tape/tapes/jacobian_tape.py
  tests/tape/interfaces/test_qnode_autograd.py
  tests/tape/interfaces/test_qnode_tf.py
  tests/tape/interfaces/test_qnode_torch.py
  tests/tape/tapes/test_qnode.py
  tests/test_operation.py
  tests/test_qubit_device_adjoint_jacobian.py
Labels: review-ready :ok_hand:

#1004 Specify the Mottonen state prep input vector must be normalized.
  pennylane/templates/state_preparations/mottonen.py
Labels: documentation :blue_book:

#1038 Fixes bug in queuing observables of tensors
  .github/CHANGELOG.md
  pennylane/tape/operation.py
  tests/tape/test_tape_measure.py
Labels: bug :bug:

#1039 Finish the introduction of the new wires logic
  .github/CHANGELOG.md
  doc/code/qml_wires.rst
  pennylane/devices/default_qubit.py
  pennylane/devices/default_qubit_autograd.py
  pennylane/devices/default_qubit_tf.py
  pennylane/templates/broadcast.py
  pennylane/wires.py
  tests/devices/test_default_qubit.py
  tests/interfaces/test_autograd.py
  tests/test_wires.py
Labels: bug :bug:

#1045 Bug fix in are_identical_pauli_words function to ensure observables are always pruned
  pennylane/grouping/utils.py
  tests/grouping/test_grouping_utils.py
Labels: bug :bug:, review-ready :ok_hand:

#1053 Fixes bugs in optimizer docstrings
  pennylane/optimize/gradient_descent.py
  pennylane/optimize/momentum.py
  pennylane/optimize/nesterov_momentum.py
  pennylane/optimize/qng.py
  pennylane/optimize/rotoselect.py
  pennylane/optimize/rotosolve.py
Labels: documentation :blue_book:
