Repository PennyLaneAI/pennylane, pull requests merged in 2021-07, with the labels that each got.

#1436 Fixes vector-Hessian product bug
  .github/CHANGELOG.md
  pennylane/interfaces/autograd.py
  pennylane/interfaces/tf.py
  pennylane/interfaces/torch.py
  tests/interfaces/test_qnode_autograd.py
  tests/interfaces/test_qnode_tf.py
  tests/interfaces/test_qnode_torch.py
Labels: bug :bug:

#1425 `IsingYY` differentiability
  .github/CHANGELOG.md
  pennylane/devices/autograd_ops.py
  pennylane/devices/default_qubit_autograd.py
  pennylane/devices/default_qubit_jax.py
  pennylane/devices/default_qubit_tf.py
  pennylane/devices/jax_ops.py
  pennylane/devices/tf_ops.py
  pennylane/ops/qubit.py
  tests/ops/test_qubit_ops.py
Labels: review-ready :ok_hand:

#1439 Add dimension checking to QubitUnitary.
  .github/CHANGELOG.md
  pennylane/ops/qubit.py
  tests/ops/test_qubit_ops.py
  tests/test_operation.py
Labels: bug :bug:

#1451 Add adjoint to the operation `QFT` and fix the `qml.adjoint()` function
  .github/CHANGELOG.md
  pennylane/ops/qubit.py
  pennylane/transforms/adjoint.py
  tests/ops/test_qubit_ops.py
Labels: bug :bug:

#1331 [unitaryhack] Change the order of the covariance matrix and the vector of means internally in `default.gaussian` for `gaussian_state`
  .github/CHANGELOG.md
  pennylane/devices/default_gaussian.py
  tests/devices/test_default_gaussian.py
Labels: unitaryhack

#1441 Added return raw sample functionality to qml.sample when observable is not provided.
  .github/CHANGELOG.md
  pennylane/_qubit_device.py
  pennylane/circuit_drawer/representation_resolver.py
  pennylane/circuit_graph.py
  pennylane/measure.py
  tests/circuit_drawer/test_representation_resolver.py
  tests/circuit_graph/test_circuit_graph.py
  tests/test_measure.py
  tests/test_qubit_device.py
Labels: enhancement :sparkles:, review-ready :ok_hand:

#1442 Adds the Grover Diffusion Operator Template
  .github/CHANGELOG.md
  doc/_static/templates/subroutines/grover.pdf
  doc/_static/templates/subroutines/grover.svg
  doc/_static/templates/subroutines/grover.tex
  doc/_static/templates/subroutines/grover2.pdf
  doc/_static/templates/subroutines/grover2.svg
  doc/_static/templates/subroutines/grover2.tex
  doc/introduction/templates.rst
  pennylane/templates/subroutines/__init__.py
  pennylane/templates/subroutines/grover.py
  tests/templates/test_subroutines/test_grover.py
Labels: merge-ready :heavy_check_mark:

#1472 Add example to FockStateVector docs.
  .github/CHANGELOG.md
  pennylane/ops/cv.py
Labels: documentation :blue_book:

#1476 Differentiable finite-difference gradient transform
  .github/CHANGELOG.md
  pennylane/__init__.py
  pennylane/gradients/__init__.py
  pennylane/gradients/finite_difference.py
  pennylane/math/single_dispatch.py
  tests/gradients/test_finite_difference.py
  tests/interfaces/test_qnode_jax.py
Labels: review-ready :ok_hand:

#1467 Break up qubit operations file
  .github/CHANGELOG.md
  pennylane/ops/__init__.py
  pennylane/ops/qubit.py
  pennylane/ops/qubit/__init__.py
  pennylane/ops/qubit/arithmetic_ops.py
  pennylane/ops/qubit/matrix_ops.py
  pennylane/ops/qubit/non_parametric_ops.py
  pennylane/ops/qubit/observables.py
  pennylane/ops/qubit/parametric_ops.py
  pennylane/ops/qubit/qchem_ops.py
  pennylane/ops/qubit/state_preparation.py
  tests/ops/test_qubit_ops.py
  tests/test_operation.py
Labels: code quality :mortar_board:, review-ready :ok_hand:

#1355 Tracking context
  .github/CHANGELOG.md
  doc/development/plugins.rst
  pennylane/__init__.py
  pennylane/_device.py
  pennylane/_qubit_device.py
  pennylane/devices/tests/test_tracker.py
  pennylane/tracker.py
  tests/test_tracker.py
Labels: merge-ready :heavy_check_mark:

#1485 make default precision equal to jax.config's jax_enable_x64
  .github/CHANGELOG.md
  pennylane/devices/default_qubit_jax.py
  tests/devices/test_default_qubit_jax.py
Labels: enhancement :sparkles:
