Repository PennyLaneAI/pennylane, pull requests merged in 2021-12, with the labels that each got.

#1952 Fix wire bug with the approx time evolution template
  doc/releases/changelog-dev.md
  pennylane/templates/subroutines/approx_time_evolution.py
  tests/templates/test_subroutines/test_approx_time_evolution.py
  tests/transforms/test_draw.py
Labels: bug :bug:

#1932 Adds utility functions for the general parameter-shift rule
  doc/releases/changelog-dev.md
  pennylane/gradients/__init__.py
  pennylane/gradients/general_shift_rules.py
  pennylane/math/single_dispatch.py
  pennylane/operation.py
  pennylane/templates/subroutines/commuting_evolution.py
  tests/gradients/test_general_shift_rules.py
  tests/interfaces/test_batch_autograd.py
  tests/interfaces/test_batch_tensorflow.py
  tests/interfaces/test_batch_torch.py
Labels: review-ready :ok_hand:

#1962 Ensure that qchem is imported lazily
  doc/releases/changelog-dev.md
  pennylane/__init__.py
Labels: review-ready :ok_hand:

#1867 Add orbital plot functions
  doc/releases/changelog-dev.md
  pennylane/hf/hartree_fock.py
  pennylane/hf/molecule.py
  tests/hf/test_molecule.py
Labels: qchem :atom_symbol:

#1954 Add active wire notches to matplotlib drawings
  doc/_static/draw_mpl/Solarize_Light2.png
  doc/_static/draw_mpl/draw_mpl_examples.py
  doc/_static/draw_mpl/main_example.png
  doc/_static/draw_mpl/postprocessing.png
  doc/_static/draw_mpl/rcparams.png
  doc/_static/draw_mpl/show_all_wires.png
  doc/_static/draw_mpl/wire_order.png
  doc/_static/draw_mpl/wires_labels.png
  doc/_static/drawer/SWAP.png
  doc/_static/drawer/example_Solarize_Light2.png
  doc/_static/drawer/example_basic.png
  doc/_static/drawer/measure.png
  doc/_static/drawer/mpldrawer_examples.py
  doc/_static/tape_mpl/Solarize_Light2.png
  doc/_static/tape_mpl/default.png
  doc/_static/tape_mpl/postprocessing.png
  doc/_static/tape_mpl/rcparams.png
  doc/_static/tape_mpl/show_all_wires.png
  doc/_static/tape_mpl/tape_mpl_examples.py
  doc/_static/tape_mpl/wire_order.png
  doc/_static/tape_mpl/wires_labels.png
  doc/releases/changelog-dev.md
  pennylane/drawer/mpldrawer.py
  pennylane/drawer/tape_mpl.py
  pennylane/transforms/draw.py
  tests/drawer/test_mpldrawer.py
  tests/drawer/test_tape_mpl.py
  tests/transforms/test_draw_mpl.py
Labels: review-ready :ok_hand:

#1781 Create `qml.PauliError`
  doc/introduction/operations.rst
  doc/releases/changelog-dev.md
  doc/requirements.txt
  pennylane/devices/default_mixed.py
  pennylane/ops/channel.py
  tests/devices/test_default_mixed.py
  tests/ops/test_channel_ops.py
Labels: hacktoberfest-accepted

#1979 Remove empty circuits and device tests to check supported operations
  doc/releases/changelog-dev.md
  pennylane/devices/tests/test_gates.py
  pennylane/devices/tests/test_gates_with_expval.py
  pennylane/devices/tests/test_measurements.py
  pennylane/devices/tests/test_properties.py
Labels: review-ready :ok_hand:

#2030 Update the `Operation.generator` property
  doc/releases/changelog-dev.md
  pennylane/fourier/utils.py
  pennylane/operation.py
  pennylane/ops/qubit/observables.py
  pennylane/ops/qubit/parametric_ops.py
  pennylane/ops/qubit/qchem_ops.py
  pennylane/tape/reversible.py
  pennylane/transforms/metric_tensor.py
  pennylane/utils.py
  tests/fourier/test_fourier_utils.py
  tests/ops/qubit/test_parametric_ops.py
  tests/ops/qubit/test_qchem_ops.py
  tests/test_operation.py
  tests/transforms/test_metric_tensor.py
  tests/transforms/test_tape_expand.py
Labels: review-ready :ok_hand:

#1974 Add symmetry generation functions for qubit tapering
  pennylane/hf/__init__.py
  pennylane/hf/tapering.py
  tests/hf/test_tapering.py
Labels: qchem :atom_symbol:

#1966 Add Hamiltonian transform functions for qubit tapering
  doc/releases/changelog-dev.md
  pennylane/hf/__init__.py
  pennylane/hf/tapering.py
  tests/hf/test_tapering.py
Labels: qchem :atom_symbol:

#2061 [OpRefactor] Update the generator to raise an exception if not defined
  doc/releases/changelog-dev.md
  doc/requirements.txt
  pennylane/operation.py
  pennylane/utils.py
  tests/fourier/test_fourier_utils.py
  tests/test_operation.py
  tests/transforms/test_tape_expand.py
Labels: review-ready :ok_hand:
