Repository PennyLaneAI/pennylane, pull requests merged in 2021-04, with the labels that each got.

#1175 Add methods for getting and stopping the currently recording tape
  .github/CHANGELOG.md
  pennylane/measure.py
  pennylane/operation.py
  pennylane/queuing.py
  pennylane/tape/__init__.py
  pennylane/tape/tape.py
  pennylane/transforms/__init__.py
  pennylane/transforms/invisible.py
  tests/tape/test_tape.py
  tests/test_queuing.py
  tests/transforms/test_invisible.py
Labels: review-ready :ok_hand:

#1197 Fixes a bug where the CV param-shift would error with more than one 2nd order observable
  .github/CHANGELOG.md
  pennylane/tape/cv_param_shift.py
  tests/tape/test_cv_param_shift.py
Labels: bug :bug:

#1223 Fixes bug where applying the Torch interface repeatedly after expansion caused an error
  .github/CHANGELOG.md
  pennylane/tape/tape.py
  tests/interfaces/test_tape_torch.py
Labels: bug :bug:

#1232 Fix using a shot_list with multiple shots for sampling
  .github/CHANGELOG.md
  pennylane/_device.py
  pennylane/_qubit_device.py
  pennylane/qnode.py
  tests/test_qubit_device.py
Labels: bug :bug:

#1169 Add Carry and Sum Operators
  .github/CHANGELOG.md
  doc/_static/ops/QubitCarry.pdf
  doc/_static/ops/QubitCarry.svg
  doc/_static/ops/QubitCarry.tex
  doc/_static/ops/QubitSum.pdf
  doc/_static/ops/QubitSum.svg
  doc/_static/ops/QubitSum.tex
  doc/introduction/operations.rst
  pennylane/devices/default_mixed.py
  pennylane/devices/default_qubit.py
  pennylane/devices/tests/test_gates.py
  pennylane/ops/qubit.py
  tests/ops/test_qubit_ops.py
Labels: merge-ready :heavy_check_mark:

#1207 QAOA cycle module
  .github/CHANGELOG.md
  doc/code/qml_qaoa.rst
  pennylane/qaoa/cycle.py
  tests/test_qaoa.py
Labels: merge-ready :heavy_check_mark:

#1212 Add unit tests for `DefaultQubit._apply_operation` and move gate integration tests to device test suite
  .github/CHANGELOG.md
  .github/workflows/tests.yml
  codecov.yml
  pennylane/devices/tests/test_gates.py
  pennylane/devices/tests/test_gates_with_expval.py
  tests/devices/test_default_qubit.py
Labels: merge-ready :heavy_check_mark:

#1243 Fix inversion of templates
  .github/CHANGELOG.md
  pennylane/tape/tape.py
  pennylane/templates/embeddings/amplitude.py
  pennylane/templates/layers/particle_conserving_u1.py
  pennylane/templates/layers/particle_conserving_u2.py
  pennylane/transforms/adjoint.py
  pennylane/utils.py
  tests/devices/test_default_qubit.py
  tests/tape/test_tape.py
  tests/templates/test_layers/test_particle_conserving_u1.py
  tests/templates/test_layers/test_particle_conserving_u2.py
  tests/test_utils.py
  tests/transforms/test_adjoint.py
Labels: review-ready :ok_hand:

#1260 Fixes two bugs in the parameter-shift Hessian
  .github/CHANGELOG.md
  pennylane/interfaces/autograd.py
  pennylane/tape/jacobian_tape.py
  tests/interfaces/test_qnode_autograd.py
  tests/tape/test_qubit_param_shift.py
Labels: bug :bug:
