Repository PennyLaneAI/pennylane, pull requests merged in 2021-10, with the labels that each got.

#1708 Ensure QNode execution options are used during batch transforms
  doc/releases/changelog-dev.md
  pennylane/gradients/gradient_transform.py
  pennylane/transforms/batch_transform.py
  pennylane/transforms/metric_tensor.py
  tests/transforms/test_batch_transform.py
Labels: bug :bug:, review-ready :ok_hand:

#1700 Add `is_independent` util
  doc/releases/changelog-dev.md
  pennylane/math/__init__.py
  pennylane/math/is_independent.py
  pennylane/math/utils.py
  tests/math/test_is_independent.py
Labels: review-ready :ok_hand:

#1698 Add function to construct the dipole moment observable
  qchem/CHANGELOG.md
  qchem/pennylane_qchem/qchem/obs.py
  qchem/tests/test_dipole.py
Labels: review-ready :ok_hand:, qchem :atom_symbol:

#1668 Add scf and energy functions for HF solver
  pennylane/hf/__init__.py
  pennylane/hf/hartree_fock.py
  tests/devices/test_default_qubit_jax.py
  tests/hf/test_hartree_fock.py
Labels: qchem :atom_symbol:

#1610 Create qchem hf feature branch
  doc/code/qml_hf.rst
  doc/index.rst
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/hf/__init__.py
  pennylane/hf/basis_data.py
  pennylane/hf/basis_set.py
  pennylane/hf/hamiltonian.py
  pennylane/hf/hartree_fock.py
  pennylane/hf/integrals.py
  pennylane/hf/matrices.py
  pennylane/hf/molecule.py
  tests/hf/test_basis_set.py
  tests/hf/test_hamiltonians.py
  tests/hf/test_hartree_fock.py
  tests/hf/test_integrals.py
  tests/hf/test_matrices.py
  tests/hf/test_molecule.py
Labels: qchem :atom_symbol:
