Repository PennyLaneAI/pennylane, pull requests merged in 2021-09, with the labels that each got.

#1585 [Code Together] Allow QNodes to support `diff_method=None` option (#1274)
  .github/CHANGELOG.md
  pennylane/qnode.py
  tests/tape/test_qnode.py
Labels: code together

#1617 relevant tests skip if cvxpy or dask is not installed
  .github/CHANGELOG.md
  tests/circuit_graph/test_circuit_graph_hash.py
  tests/collections/test_qnode_collection.py
  tests/conftest.py
  tests/kernels/test_kernels.py
  tests/tape/test_qnode.py
Labels: bug :bug:, review-ready :ok_hand:

#1592 Add molecule class for HF solver
  doc/code/qml_hf.rst
  doc/index.rst
  pennylane/__init__.py
  pennylane/hf/__init__.py
  pennylane/hf/molecule.py
  tests/hf/test_molecule.py
Labels: qchem :atom_symbol:

#1616 Add normalisation functions for HF solver
  pennylane/hf/__init__.py
  pennylane/hf/integrals.py
  pennylane/hf/molecule.py
  tests/hf/test_integrals.py
Labels: qchem :atom_symbol:

#1608 Add support for the new VQE workflows to the differentiable batch execution pipeline
  .github/CHANGELOG.md
  pennylane/_device.py
  pennylane/devices/default_qubit.py
  pennylane/gradients/__init__.py
  pennylane/gradients/hamiltonian_grad.py
  pennylane/gradients/parameter_shift.py
  pennylane/interfaces/batch/autograd.py
  pennylane/interfaces/batch/tensorflow.py
  pennylane/tape/tape.py
  pennylane/transforms/classical_jacobian.py
  tests/gradients/test_parameter_shift.py
  tests/interfaces/test_batch_autograd.py
  tests/interfaces/test_batch_tensorflow.py
  tests/interfaces/test_batch_torch.py
Labels: review-ready :ok_hand:

#1625 Improve consistency in treatment of optimizer hyperparameters
  .github/CHANGELOG.md
  pennylane/optimize/adagrad.py
  pennylane/optimize/adam.py
  pennylane/optimize/gradient_descent.py
  pennylane/optimize/momentum.py
  pennylane/optimize/qng.py
  pennylane/optimize/rms_prop.py
  pennylane/optimize/shot_adaptive.py
  tests/optimize/test_optimize.py
  tests/optimize/test_qng.py
  tests/optimize/test_shot_adaptive.py
Labels: code quality :mortar_board:

#1504 Updated resolution of qml.CY when drawn
  .github/CHANGELOG.md
  pennylane/circuit_drawer/representation_resolver.py
  tests/circuit_drawer/test_circuit_drawer.py
Labels: bug :bug:

#1618 Final touches to get `batch.execute` ready for QNode integration
  .github/CHANGELOG.md
  pennylane/__init__.py
  pennylane/gradients/__init__.py
  pennylane/gradients/finite_difference.py
  pennylane/gradients/parameter_shift.py
  pennylane/gradients/parameter_shift_cv.py
  pennylane/interfaces/batch/__init__.py
  pennylane/interfaces/batch/autograd.py
  pennylane/interfaces/batch/tensorflow.py
  pennylane/interfaces/batch/torch.py
  pennylane/transforms/batch_transform.py
  tests/interfaces/test_batch_autograd.py
  tests/interfaces/test_batch_tensorflow.py
  tests/interfaces/test_batch_torch.py
Labels: review-ready :ok_hand:

#1588 Error when creating qnode with backprop and finite-shots
  .github/CHANGELOG.md
  pennylane/qnode.py
  tests/devices/test_default_qubit_jax.py
  tests/devices/test_default_qubit_tf.py
  tests/devices/test_default_qubit_torch.py
  tests/tape/test_qnode.py
Labels: bug :bug:, review-ready :ok_hand:

#1621 Add overlap integral for HF solver
  pennylane/hf/__init__.py
  pennylane/hf/integrals.py
  tests/hf/test_integrals.py
Labels: qchem :atom_symbol:

#1637 Bug fixes for batch execution
  .github/CHANGELOG.md
  pennylane/devices/default_qubit_jax.py
  pennylane/gradients/gradient_transform.py
  pennylane/gradients/vjp.py
  pennylane/interfaces/batch/autograd.py
  pennylane/interfaces/batch/tensorflow.py
  pennylane/interfaces/batch/torch.py
  pennylane/transforms/batch_transform.py
  tests/devices/test_default_qubit_jax.py
  tests/interfaces/test_batch_autograd.py
  tests/interfaces/test_batch_tensorflow.py
  tests/interfaces/test_batch_torch.py
  tests/test_optimize_shot_adapative.py
  tests/transforms/test_batch_transform.py
Labels: review-ready :ok_hand:

#1640 Minor improvement to CircuitDrawer class interface
  .github/CHANGELOG.md
  pennylane/circuit_drawer/circuit_drawer.py
  pennylane/circuit_graph.py
  tests/circuit_drawer/test_circuit_drawer.py
Labels: code quality :mortar_board:, review-ready :ok_hand:

#1641 device suite passes in clean environment
  .github/CHANGELOG.md
  pennylane/devices/tests/test_measurements.py
Labels: review-ready :ok_hand:

#1638 Add support for batch execution to `qml.metric_tensor`
  .github/CHANGELOG.md
  pennylane/math/utils.py
  pennylane/qnode.py
  pennylane/transforms/__init__.py
  pennylane/transforms/classical_jacobian.py
  pennylane/transforms/metric_tensor.py
  tests/gradients/test_gradient_transform.py
  tests/interfaces/test_qnode_autograd.py
  tests/interfaces/test_qnode_tf.py
  tests/interfaces/test_qnode_torch.py
  tests/math/test_functions.py
  tests/tape/test_unwrap.py
  tests/transforms/test_classical_jacobian.py
  tests/transforms/test_metric_tensor.py
Labels: review-ready :ok_hand:

#1484 Matplotlib circuit drawing
  .github/CHANGELOG.md
  doc/_static/drawer/SWAP.png
  doc/_static/drawer/SWAP_formatted.png
  doc/_static/drawer/box_gates.png
  doc/_static/drawer/box_gates_formatted.png
  doc/_static/drawer/cnot.png
  doc/_static/drawer/ctrl.png
  doc/_static/drawer/example_Solarize_Light2.png
  doc/_static/drawer/example_basic.png
  doc/_static/drawer/example_formatted.png
  doc/_static/drawer/example_rcParams.png
  doc/_static/drawer/float_layer.png
  doc/_static/drawer/just_wires.png
  doc/_static/drawer/labels.png
  doc/_static/drawer/labels_formatted.png
  doc/_static/drawer/labels_test.png
  doc/_static/drawer/measure.png
  doc/_static/drawer/measure_formatted.png
  doc/_static/drawer/mpldrawer_examples.py
  doc/code/qml_circuit_drawer.rst
  doc/index.rst
  pennylane/circuit_drawer/__init__.py
  pennylane/circuit_drawer/mpldrawer.py
  tests/circuit_drawer/test_grid.py
  tests/circuit_drawer/test_mpldrawer.py
  tests/circuit_drawer/test_representation_resolver.py
Labels: merge-ready :heavy_check_mark:

#1644 Add kinetic integral for HF solver
  pennylane/hf/__init__.py
  pennylane/hf/integrals.py
  tests/hf/test_integrals.py
Labels: qchem :atom_symbol:

#1667 bugfix: raise mpl import error inside class initialization
  pennylane/circuit_drawer/mpldrawer.py
Labels: bug :bug:, review-ready :ok_hand:

#1666 bugfix for device shot list processing
  .github/CHANGELOG.md
  pennylane/_device.py
  tests/test_device.py
Labels: bug :bug:, review-ready :ok_hand:

#1642 Integrate batch execution into a QNode
  doc/code/qml_beta.rst
  doc/introduction/interfaces.rst
  doc/introduction/interfaces/numpy.rst
  doc/introduction/interfaces/tf.rst
  doc/introduction/interfaces/torch.rst
  doc/introduction/templates.rst
  doc/releases/changelog-dev.md
  pennylane/beta/__init__.py
  pennylane/beta/qnode.py
  pennylane/gradients/__init__.py
  pennylane/gradients/finite_difference.py
  pennylane/gradients/parameter_shift.py
  pennylane/gradients/parameter_shift_cv.py
  pennylane/templates/layers/simplified_two_design.py
  pennylane/transforms/batch_transform.py
  pennylane/transforms/classical_jacobian.py
  pennylane/transforms/metric_tensor.py
  tests/beta/test_beta_qnode.py
Labels: review-ready :ok_hand:

#1631 Add all attraction and repulsion integrals for HF solver
  pennylane/hf/__init__.py
  pennylane/hf/integrals.py
  tests/hf/test_integrals.py
Labels: qchem :atom_symbol:

#1646 Add autodiff integration tests for the new QNode pipeline
  doc/releases/changelog-dev.md
  pennylane/gradients/parameter_shift.py
  tests/interfaces/test_batch_autograd_qnode.py
  tests/interfaces/test_batch_tensorflow_qnode.py
  tests/interfaces/test_batch_torch_qnode.py
Labels: review-ready :ok_hand:

#1680 Fixes bug in default.mixed where probabilities could be non-negative
  doc/releases/changelog-dev.md
  pennylane/devices/default_mixed.py
  tests/devices/test_default_mixed.py
Labels: bug :bug:

#1651 Add device and gradient expansions to the new batch-execution pipeline
  doc/releases/changelog-dev.md
  pennylane/_device.py
  pennylane/beta/qnode.py
  pennylane/gradients/gradient_transform.py
  pennylane/interfaces/batch/__init__.py
  pennylane/interfaces/batch/autograd.py
  pennylane/interfaces/batch/torch.py
  pennylane/templates/embeddings/amplitude.py
  pennylane/templates/embeddings/angle.py
  pennylane/templates/layers/basic_entangler.py
  pennylane/templates/layers/cv_neural_net.py
  pennylane/templates/layers/particle_conserving_u1.py
  pennylane/templates/layers/particle_conserving_u2.py
  pennylane/templates/layers/random.py
  pennylane/templates/layers/simplified_two_design.py
  pennylane/templates/layers/strongly_entangling.py
  pennylane/templates/state_preparations/arbitrary_state_preparation.py
  pennylane/templates/state_preparations/basis.py
  pennylane/templates/state_preparations/mottonen.py
  pennylane/templates/subroutines/all_singles_doubles.py
  pennylane/templates/subroutines/approx_time_evolution.py
  pennylane/templates/subroutines/arbitrary_unitary.py
  pennylane/templates/subroutines/double_excitation_unitary.py
  pennylane/templates/subroutines/grover.py
  pennylane/templates/subroutines/permute.py
  pennylane/templates/subroutines/qmc.py
  pennylane/templates/subroutines/qpe.py
  pennylane/templates/subroutines/single_excitation_unitary.py
  pennylane/templates/subroutines/uccsd.py
  tests/beta/test_beta_qnode.py
  tests/gradients/test_gradient_transform.py
  tests/interfaces/test_batch_autograd_qnode.py
  tests/interfaces/test_batch_tensorflow_qnode.py
  tests/interfaces/test_batch_torch_qnode.py
Labels: review-ready :ok_hand:

#1657 Add all matrices for HF solver
  pennylane/hf/__init__.py
  pennylane/hf/matrices.py
  tests/hf/test_matrices.py
Labels: qchem :atom_symbol:

#1674 Allow for operations to have gradient recipes that depend on the operation state
  doc/releases/changelog-dev.md
  pennylane/operation.py
  tests/gradients/test_parameter_shift.py
  tests/test_operation.py
Labels: review-ready :ok_hand:

#1699 Fixes a bug where batch transforms wouldn't work with templates
  doc/releases/changelog-dev.md
  pennylane/gradients/gradient_transform.py
  pennylane/transforms/classical_jacobian.py
  pennylane/transforms/metric_tensor.py
  tests/gradients/test_gradient_transform.py
  tests/transforms/test_metric_tensor.py
Labels: bug :bug:, review-ready :ok_hand:

#1707 Allows shots to be passed to transforms at runtime
  doc/releases/changelog-dev.md
  pennylane/interfaces/batch/__init__.py
  pennylane/transforms/batch_transform.py
  pennylane/transforms/classical_jacobian.py
  tests/gradients/test_gradient_transform.py
Labels: review-ready :ok_hand:
