Repository PennyLaneAI/pennylane, pull requests merged in 2022-08, with the labels that each got.

#2876 Add qml.counts UI
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/measurements.py
  tests/ops/op_math/test_sprod.py
  tests/ops/op_math/test_sum.py
  tests/test_measurements.py
  tests/test_new_return_types.py
Labels: review-ready :ok_hand:

#2644 Add algorithm resource estimation
  doc/code/qml_resource.rst
  doc/index.rst
  doc/introduction/chemistry.rst
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/qchem/__init__.py
  pennylane/qchem/factorization.py
  pennylane/resource/__init__.py
  pennylane/resource/first_quantization.py
  pennylane/resource/second_quantization.py
  tests/qchem/test_factorization.py
  tests/resource/test_first_quantization.py
  tests/resource/test_second_quantization.py
Labels: WIP :construction:, do not merge :warning:

#2783 Default Qutrit
  doc/releases/changelog-dev.md
  pennylane/_qutrit_device.py
  pennylane/devices/__init__.py
  pennylane/devices/default_qutrit.py
  setup.py
  tests/conftest.py
  tests/devices/test_default_qutrit.py
  tests/test_qutrit_device.py
Labels: review-ready :ok_hand:

#2625 Operator Arithmetic `Prod` wrapper class implementation
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/_qubit_device.py
  pennylane/devices/default_qubit.py
  pennylane/measurements.py
  pennylane/ops/op_math/__init__.py
  pennylane/ops/op_math/prod.py
  pennylane/ops/op_math/sum.py
  tests/ops/op_math/test_prod.py
  tests/ops/op_math/test_sprod.py
  tests/ops/op_math/test_sum.py
Labels: op-arithmetic

#2873 `batch_input` works with the batched operation located anywhere in a circuit
  doc/releases/changelog-dev.md
  pennylane/tape/tape.py
  pennylane/transforms/batch_input.py
  tests/transforms/test_batch_input.py
  tests/transforms/test_batch_inputs.py
Labels: review-ready :ok_hand:

#2836 device support for anything with a matrix
  doc/releases/changelog-dev.md
  pennylane/_device.py
  pennylane/devices/default_qubit.py
  pennylane/interfaces/execution.py
  pennylane/ops/qubit/attributes.py
  tests/devices/test_default_qubit.py
  tests/drawer/test_draw_mpl.py
  tests/interfaces/test_tensorflow.py
  tests/interfaces/test_torch.py
  tests/ops/qubit/test_qchem_ops.py
  tests/transforms/test_batch_transform.py
  tests/transforms/test_tape_expand.py
Labels: op-arithmetic

#2891 Add __mul__ dunder method
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/operation.py
  pennylane/ops/qubit/hamiltonian.py
  tests/test_operation.py
Labels: op-arithmetic

#2835 Operator simplification #1: Class level simplify methods
  doc/releases/changelog-dev.md
  pennylane/operation.py
  pennylane/ops/op_math/adjoint_class.py
  pennylane/ops/op_math/controlled_class.py
  pennylane/ops/op_math/pow_class.py
  pennylane/ops/op_math/prod.py
  pennylane/ops/op_math/sprod.py
  pennylane/ops/op_math/sum.py
  pennylane/ops/op_math/symbolicop.py
  pennylane/ops/qubit/hamiltonian.py
  tests/ops/functions/test_equal.py
  tests/ops/op_math/test_adjoint_op.py
  tests/ops/op_math/test_controlled_op.py
  tests/ops/op_math/test_pow_op.py
  tests/ops/op_math/test_prod.py
  tests/ops/op_math/test_sprod.py
  tests/ops/op_math/test_sum.py
  tests/test_operation.py
Labels: review-ready :ok_hand:, op-arithmetic

#2854 Operator simplification #2: Simplify wrapper
  doc/releases/changelog-dev.md
  pennylane/ops/functions/__init__.py
  pennylane/ops/functions/simplify.py
  tests/ops/functions/test_simplify.py
Labels: merge-ready :heavy_check_mark:, op-arithmetic

#2913 Fixes a bug where kUpCCGSD wasn't working with the parameter-shift rule
  doc/releases/changelog-0.25.0.md
  pennylane/templates/subroutines/kupccgsd.py
  tests/templates/test_subroutines/test_kupccgsd.py
Labels: bug :bug:

#2730 Add module documentation for `ops`
  doc/code/qml_ops_op_math.rst
  doc/index.rst
  doc/introduction/operations.rst
  pennylane/ops/functions/__init__.py
  pennylane/ops/op_math/__init__.py
  pennylane/ops/op_math/control.py
  pennylane/ops/op_math/controlled_class.py
  pennylane/ops/op_math/prod.py
  pennylane/ops/op_math/sprod.py
  pennylane/ops/op_math/sum.py
Labels: review-ready :ok_hand:, op-arithmetic

#2784 Qutrit Hermitian
  doc/releases/changelog-dev.md
  pennylane/devices/default_qutrit.py
  pennylane/ops/qutrit/__init__.py
  pennylane/ops/qutrit/matrix_ops.py
  pennylane/ops/qutrit/observables.py
  tests/conftest.py
  tests/devices/test_default_qutrit.py
  tests/ops/qutrit/test_qutrit_observables.py
  tests/test_qutrit_device.py
Labels: review-ready :ok_hand:

#2973 Update `0.25.1`
  .github/workflows/tests-gpu.yml
  doc/releases/changelog-0.25.0.md
  pennylane/math/__init__.py
  pennylane/math/multi_dispatch.py
  pennylane/ops/qubit/parametric_ops.py
  tests/devices/test_default_qubit_torch.py
  tests/math/test_multi_dispatch.py
Labels: gpu

#2967 Update `qml.math.array` & `qml.math.eye` preserve Torch devices & fix Torch gpu errors
  doc/releases/changelog-dev.md
  pennylane/math/__init__.py
  pennylane/math/multi_dispatch.py
  pennylane/ops/qubit/parametric_ops.py
  tests/devices/test_default_qubit_torch.py
  tests/math/test_multi_dispatch.py
Labels: gpu

#2972 Updated GPU Tests workflow file to only run if the pull_request is in open state
  .github/workflows/tests-gpu.yml
  doc/releases/changelog-dev.md
Labels: gpu

#2821 [Classical Shadows 2] `ClassicalShadow` class
  doc/code/qml_shadows.rst
  doc/index.rst
  pennylane/__init__.py
  pennylane/_qubit_device.py
  pennylane/devices/default_qubit.py
  pennylane/math/single_dispatch.py
  pennylane/shadows/__init__.py
  pennylane/shadows/classical_shadow.py
  tests/shadow/test_shadow_class.py
  tests/shadow/test_shadow_measurement.py
Labels: review-ready :ok_hand:

#2841 Qutrit Non-Parametric Ops #1 (TShift, TClock)
  doc/releases/changelog-dev.md
  pennylane/_qutrit_device.py
  pennylane/devices/default_qutrit.py
  pennylane/ops/qutrit/__init__.py
  pennylane/ops/qutrit/non_parametric_ops.py
  tests/devices/test_default_qutrit.py
  tests/gate_data.py
  tests/ops/qutrit/test_qutrit_matrix_ops.py
  tests/ops/qutrit/test_qutrit_non_parametric_ops.py
  tests/test_operation.py
Labels: review-ready :ok_hand:

#2964 Support Sparse Matrix representation for Observables and Arithmetic Ops (1/3)
  doc/releases/changelog-dev.md
  pennylane/ops/identity.py
  pennylane/ops/qubit/non_parametric_ops.py
  tests/ops/op_math/test_sprod.py
  tests/ops/qubit/test_non_parametric_ops.py
Labels: review-ready :ok_hand:

#2938 Add decomposition to `Controlled`
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/controlled_class.py
  pennylane/ops/qubit/matrix_ops.py
  pennylane/ops/qubit/non_parametric_ops.py
  pennylane/ops/qubit/parametric_ops.py
  tests/ops/op_math/test_control.py
  tests/ops/op_math/test_controlled_op.py
  tests/ops/qubit/test_matrix_ops.py
  tests/ops/qubit/test_non_parametric_ops.py
  tests/ops/qubit/test_parametric_ops.py
Labels: review-ready :ok_hand:

#2991 Move `is_commuting` to `pennylane/ops/functions`
  doc/introduction/operations.rst
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/ops/functions/__init__.py
  pennylane/ops/functions/is_commuting.py
  pennylane/transforms/__init__.py
  pennylane/transforms/commutation_dag.py
  tests/ops/functions/test_is_commuting.py
  tests/transforms/test_commutation_dag.py
Labels: review-ready :ok_hand:

#2871 [ClassicalShadow 3] diffable `shadow_expval`
  doc/code/qml_shadows.rst
  doc/introduction/measurements.rst
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/_device.py
  pennylane/_qubit_device.py
  pennylane/devices/default_qubit.py
  pennylane/measurements.py
  pennylane/shadows/__init__.py
  pennylane/shadows/classical_shadow.py
  pennylane/tape/tape.py
  tests/shadow/test_shadow_class.py
  tests/shadow/test_shadow_expval.py
Labels: review-ready :ok_hand:

#2998 Create a `expand_matrix` method for Sparse matrices
  doc/releases/changelog-dev.md
  pennylane/math/matrix_manipulation.py
  tests/math/test_matrix_manipulation.py
  tests/test_operation.py
Labels: review-ready :ok_hand:, op-arithmetic
