Repository PennyLaneAI/pennylane, pull requests merged in 2022-06, with the labels that each got.

#2222 Adjoint operator modifiers
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/devices/default_qubit.py
  pennylane/devices/default_qubit_torch.py
  pennylane/math/single_dispatch.py
  pennylane/operation.py
  pennylane/ops/__init__.py
  pennylane/ops/op_math/__init__.py
  pennylane/ops/op_math/adjoint_class.py
  pennylane/ops/op_math/adjoint_constructor.py
  pennylane/ops/qubit/non_parametric_ops.py
  pennylane/ops/qubit/state_preparation.py
  pennylane/tape/tape.py
  pennylane/templates/embeddings/amplitude.py
  pennylane/templates/layers/cv_neural_net.py
  pennylane/templates/subroutines/hilbert_schmidt.py
  pennylane/templates/subroutines/interferometer.py
  pennylane/templates/subroutines/qft.py
  pennylane/templates/subroutines/qpe.py
  pennylane/transforms/__init__.py
  pennylane/transforms/adjoint.py
  pennylane/transforms/commutation_dag.py
  pennylane/transforms/control.py
  pennylane/transforms/op_transforms.py
  pennylane/transforms/optimization/cancel_inverses.py
  pennylane/transforms/optimization/merge_rotations.py
  pennylane/transforms/optimization/pattern_matching.py
  pennylane/transforms/qmc.py
  tests/devices/test_default_qubit_torch.py
  tests/ops/functions/test_eigvals.py
  tests/ops/functions/test_generator.py
  tests/ops/op_math/test_adjoint_op.py
  tests/ops/op_math/test_adjoint_transform.py
  tests/ops/qubit/test_arithmetic_ops.py
  tests/ops/qubit/test_non_parametric_ops.py
  tests/ops/qubit/test_parametric_ops.py
  tests/ops/qubit/test_state_prep.py
  tests/tape/test_tape.py
  tests/templates/test_subroutines/test_hilbert_schmidt.py
  tests/templates/test_subroutines/test_qft.py
  tests/test_operation.py
  tests/transforms/test_adjoint.py
  tests/transforms/test_condition.py
  tests/transforms/test_control.py
  tests/transforms/test_optimization/test_cancel_inverses.py
  tests/transforms/test_optimization/test_pattern_matching.py
  tests/transforms/test_qmc_transform.py
Labels: op-arithmetic

#2635 Add a `requirements_dev.txt` file [unitaryhack]
  .github/CONTRIBUTING.md
  doc/releases/changelog-dev.md
  requirements.txt
  requirements_dev.txt
Labels: unitaryhack-accepted

#2621 `Pow` Symbolic Operator
  doc/releases/changelog-dev.md
  pennylane/math/single_dispatch.py
  pennylane/ops/op_math/__init__.py
  pennylane/ops/op_math/pow_class.py
  tests/ops/op_math/test_pow_op.py
Labels: op-arithmetic

#2658 Add adjoint ops to device test suite
  doc/releases/changelog-dev.md
  pennylane/devices/tests/test_gates.py
Labels: op-arithmetic

#2630 Trial performance improvements to sparse Hamiltonian building
  doc/releases/changelog-dev.md
  pennylane/utils.py
Labels: review-ready :ok_hand:

#2649 Add IsingXY [unitaryhack]
  doc/introduction/operations.rst
  doc/releases/changelog-dev.md
  pennylane/devices/default_qubit.py
  pennylane/devices/tests/test_gates.py
  pennylane/ops/qubit/__init__.py
  pennylane/ops/qubit/parametric_ops.py
  tests/gate_data.py
  tests/ops/qubit/test_parametric_ops.py
Labels: unitaryhack-accepted

#2554 [QIM-1] Create a `qml.math.density_matrix` for state vectors
  doc/releases/changelog-dev.md
  pennylane/devices/default_qubit.py
  pennylane/math/__init__.py
  pennylane/math/quantum.py
  tests/devices/test_default_qubit_torch.py
  tests/math/test_density_matrices.py
  tests/math/test_functions.py
Labels: review-ready :ok_hand:

#2569 [QIM-2] Add a `qml.math.state_to_density_matrix` for matrices and `qml.math.partial_trace` to math module
  doc/releases/changelog-dev.md
  pennylane/_qubit_device.py
  pennylane/devices/default_mixed.py
  pennylane/devices/default_qubit.py
  pennylane/math/quantum.py
  tests/math/test_density_matrices.py
Labels: review-ready :ok_hand:

#2598 [QIM-3] Add function `density_matrix_transform`
  doc/code/qml_qinfo.rst
  doc/index.rst
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/qinfo/__init__.py
  pennylane/qinfo/transforms.py
  tests/qinfo/test_reduced_dm.py
Labels: review-ready :ok_hand:

#2617 [QIM-4] Von Neumann entropy
  doc/index.rst
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/_qubit_device.py
  pennylane/interfaces/jax_jit.py
  pennylane/math/__init__.py
  pennylane/math/quantum.py
  pennylane/math/single_dispatch.py
  pennylane/measurements.py
  pennylane/qinfo/transforms.py
  tests/math/test_entropies_math.py
  tests/qinfo/test_entropies.py
  tests/qinfo/test_reduced_dm.py
Labels: review-ready :ok_hand:

#2631 [QIM-5] Add mutual information function
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/_qubit_device.py
  pennylane/interfaces/jax_jit.py
  pennylane/math/__init__.py
  pennylane/math/quantum.py
  pennylane/measurements.py
  pennylane/qinfo/transforms.py
  tests/math/test_entropies_math.py
  tests/qinfo/test_entropies.py
Labels: review-ready :ok_hand:

#2640 [QIM-6] classical fisher information matrix (as a transform)
  doc/releases/changelog-dev.md
  pennylane/math/__init__.py
  pennylane/math/quantum.py
  pennylane/qinfo/__init__.py
  pennylane/qinfo/transforms.py
  tests/qinfo/test_fisher.py
  tests/qinfo/test_reduced_dm.py
  tests/transforms/test_split_non_commuting.py
Labels: review-ready :ok_hand:

#2661 [unitaryhack] Add SPSA optimization
  doc/introduction/interfaces.rst
  doc/releases/changelog-dev.md
  pennylane/optimize/__init__.py
  pennylane/optimize/spsa.py
  tests/optimize/test_spsa.py
Labels: unitaryhack-accepted

#2651 Add equal function [unitaryhack]
  doc/releases/changelog-dev.md
  pennylane/ops/functions/__init__.py
  pennylane/ops/functions/equal.py
  tests/ops/functions/test_equal.py
Labels: unitaryhack-accepted

#2688 Support classical fisher gradients when using Autograd
  doc/releases/changelog-dev.md
  pennylane/qinfo/transforms.py
  tests/qinfo/test_fisher.py
Labels: bug :bug:

#2709 Add pennylane drawer style [unitaryhack]
  doc/_static/style/black_white_dark_style.png
  doc/_static/style/black_white_style.png
  doc/_static/style/default_style.png
  doc/_static/style/sketch_dark_style.png
  doc/_static/style/sketch_style.png
  doc/_static/style/solarized_dark_style.png
  doc/_static/style/solarized_light_style.png
  doc/code/qml_drawer.rst
  doc/releases/changelog-dev.md
  pennylane/drawer/style.py
  tests/drawer/test_style.py
Labels: unitaryhack-accepted

#2646 Add two-electron tensor factorization
  doc/code/qml_resources.rst
  doc/index.rst
  pennylane/__init__.py
  pennylane/resources/__init__.py
  pennylane/resources/factorization.py
  tests/resources/test_factorization.py
Labels: qchem :atom_symbol:

#2665 Add cost functions for double-factorization method
  pennylane/resources/__init__.py
  pennylane/resources/second_quantization.py
  tests/resources/test_second_quantization.py
Labels: qchem :atom_symbol:

#2694 Add resource estimation class for second quantization algorithm
  pennylane/resources/__init__.py
  pennylane/resources/second_quantization.py
  tests/resources/test_second_quantization.py
Labels: qchem :atom_symbol:

#2723 Add cost functions for the first quantization algorithm
  pennylane/resources/__init__.py
  pennylane/resources/first_quantization.py
  tests/resources/test_first_quantization.py
Labels: qchem :atom_symbol:

#2746 Add resource estimation class for first quantization algorithm
  doc/code/qml_resources.rst
  pennylane/resources/__init__.py
  pennylane/resources/first_quantization.py
  pennylane/resources/second_quantization.py
  tests/resources/test_first_quantization.py
Labels: qchem :atom_symbol:
