Repository PennyLaneAI/pennylane, pull requests merged in 2022-01, with the labels that each got.

#2041 Add functions to find correct sector for qubit tapering
  doc/releases/changelog-dev.md
  pennylane/hf/__init__.py
  pennylane/hf/tapering.py
  tests/hf/test_tapering.py
Labels: qchem :atom_symbol:

#2060 Raise an error if `adjoint` is applied to a non-callable object.
  doc/releases/changelog-dev.md
  pennylane/transforms/adjoint.py
  tests/transforms/test_adjoint.py
Labels: bug :bug:

#2072 Fix sign errors in `qml.DoubleExcitation` documentation.
  doc/releases/changelog-dev.md
  pennylane/ops/qubit/qchem_ops.py
Labels: documentation :blue_book:

#2059 Remove the stacking (and transposing) behaviour of `qml.jacobian`
  doc/releases/changelog-dev.md
  pennylane/_grad.py
  pennylane/gradients/gradient_transform.py
  pennylane/math/__init__.py
  pennylane/math/multi_dispatch.py
  pennylane/optimize/qng.py
  pennylane/optimize/rotosolve.py
  pennylane/transforms/adjoint_metric_tensor.py
  pennylane/transforms/classical_jacobian.py
  pennylane/transforms/metric_tensor.py
  tests/fourier/test_reconstruct.py
  tests/gradients/test_gradient_transform.py
  tests/interfaces/test_batch_autograd.py
  tests/interfaces/test_batch_autograd_qnode.py
  tests/interfaces/test_qnode_autograd.py
  tests/interfaces/test_tape_autograd.py
  tests/math/test_functions.py
  tests/optimize/test_qng.py
  tests/test_classical_gradients.py
  tests/test_prob.py
  tests/test_qnode.py
  tests/test_quantum_gradients.py
  tests/test_qubit_device.py
  tests/transforms/test_adjoint_metric_tensor.py
  tests/transforms/test_classical_jacobian.py
  tests/transforms/test_decompositions.py
  tests/transforms/test_metric_tensor.py
  tests/transforms/test_optimization/test_commute_controlled.py
  tests/transforms/test_qfunc_transform.py
  tests/transforms/test_tape_expand.py
Labels: enhancement :sparkles:

#2108 Fix psi4 bug by converting atomic coordinates to a numpy array
  qchem/pennylane_qchem/qchem/structure.py
Labels: qchem :atom_symbol:

#2111 Moves the application of batch transforms out of the QNode and into `qml.execute`
  doc/releases/changelog-dev.md
  pennylane/interfaces/batch/__init__.py
  pennylane/qnode.py
  pennylane/transforms/__init__.py
  pennylane/transforms/batch_transform.py
  tests/interfaces/test_batch_autograd.py
  tests/transforms/test_batch_transform.py
Labels: bug :bug:

#2117 Fixes bug where VJPs tapes were not unwrapped when using the Torch interface
  doc/releases/changelog-dev.md
  pennylane/interfaces/batch/torch.py
  tests/qnn/test_qnn_torch.py
Labels: bug :bug:

#2042 Add function to taper Hartree Fock state for qubit tapering
  doc/releases/changelog-dev.md
  pennylane/grouping/utils.py
  pennylane/hf/__init__.py
  pennylane/hf/hamiltonian.py
  pennylane/hf/tapering.py
  tests/hf/test_tapering.py
Labels: WIP :construction:, qchem :atom_symbol:

#2103 Add a modified simplify function for building Hamiltonians
  doc/releases/changelog-dev.md
  pennylane/hf/hamiltonian.py
  pennylane/hf/tapering.py
  tests/hf/test_hamiltonians.py
  tests/hf/test_tapering.py
Labels: qchem :atom_symbol:
