Repository PennyLaneAI/pennylane, pull requests merged in 2022-03, with the labels that each got.

#2238 Fix bug to allow `qml.ctrl` to work with gradient transforms
  doc/releases/changelog-dev.md
  pennylane/transforms/control.py
  tests/transforms/test_control.py
Labels: bug :bug:

#1712 Commutation dag
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/operation.py
  pennylane/templates/subroutines/qpe.py
  pennylane/transforms/__init__.py
  pennylane/transforms/commutation_dag.py
  pennylane/transforms/control.py
  tests/test_device.py
  tests/transforms/test_commutation_dag.py
Labels: review-ready :ok_hand:

#2255 Fix parameter-shift bug in JAX interface
  doc/releases/changelog-dev.md
  pennylane/interfaces/batch/jax.py
  tests/interfaces/test_batch_jax_qnode.py
Labels: bug :bug:

#2240 Add operator transform functionality
  pennylane/__init__.py
  pennylane/transforms/__init__.py
  pennylane/transforms/op_transforms.py
  tests/transforms/test_op_transform.py
Labels: review-ready :ok_hand:

#2241 Add `qml.matrix(op)` function
  pennylane/__init__.py
  pennylane/operation.py
  pennylane/ops/functions/__init__.py
  pennylane/ops/functions/matrix.py
  tests/ops/functions/test_matrix.py
Labels: review-ready :ok_hand:

#2248 Add `qml.eigvals(op)` function
  doc/introduction/operations.rst
  doc/releases/changelog-dev.md
  pennylane/measurements.py
  pennylane/operation.py
  pennylane/ops/functions/__init__.py
  pennylane/ops/functions/eigvals.py
  pennylane/transforms/get_unitary_matrix.py
  tests/ops/functions/test_eigvals.py
Labels: review-ready :ok_hand:

#2230 Add functions for creating fermionic and qubit observables
  pennylane/hf/__init__.py
  pennylane/hf/dipole.py
  pennylane/hf/hamiltonian.py
  pennylane/hf/hartree_fock.py
  pennylane/hf/observable.py
  pennylane/hf/particle_number.py
  pennylane/hf/spin.py
  pennylane/hf/tapering.py
  tests/hf/test_dipole.py
  tests/hf/test_hamiltonians.py
  tests/hf/test_observable_qchem.py
Labels: qchem :atom_symbol:

#2271 add `expansion_strategy` keyword to `qml.draw_mpl`
  doc/releases/changelog-dev.md
  pennylane/transforms/draw.py
  tests/transforms/test_draw_mpl.py
Labels: review-ready :ok_hand:

#2252 Updated docstrings with new draw method
  doc/introduction/circuits.rst
  pennylane/__init__.py
  pennylane/fourier/circuit_spectrum.py
  pennylane/fourier/qnode_spectrum.py
  pennylane/gradients/param_shift_hessian.py
  pennylane/qaoa/layers.py
  pennylane/tape/stop_recording.py
  pennylane/templates/embeddings/angle.py
  pennylane/templates/embeddings/basis.py
  pennylane/templates/embeddings/displacement.py
  pennylane/templates/embeddings/squeezing.py
  pennylane/templates/layer.py
  pennylane/templates/layers/random.py
  pennylane/templates/layers/strongly_entangling.py
  pennylane/templates/state_preparations/mottonen.py
  pennylane/templates/subroutines/interferometer.py
  pennylane/templates/subroutines/permute.py
  pennylane/templates/tensornetworks/mps.py
  pennylane/templates/tensornetworks/ttn.py
  pennylane/transforms/adjoint.py
  pennylane/transforms/batch_transform.py
  pennylane/transforms/compile.py
  pennylane/transforms/insert_ops.py
  pennylane/transforms/qcut.py
  pennylane/transforms/qfunc_transforms.py
  pennylane/transforms/tape_expand.py
  pennylane/transforms/unitary_to_rot.py
Labels: review-ready :ok_hand:

#2266 `qml.RandomLayers` decomposes with list of lists weights
  doc/releases/changelog-dev.md
  pennylane/templates/layers/random.py
  tests/templates/test_layers/test_random.py
Labels: review-ready :ok_hand:

#2274 Fixes the operation derivative
  pennylane/operation.py
  tests/test_operation.py
Labels: bug :bug:

#2280 Fix bug when using `for` loops with custom decompositions
  pennylane/transforms/tape_expand.py
  tests/transforms/test_tape_expand.py
Labels: bug :bug:

#2278 Update `MultiControlledX` call in `GroverOperator`
  doc/releases/changelog-dev.md
  pennylane/templates/subroutines/grover.py
  tests/templates/test_subroutines/test_grover.py
Labels: review-ready :ok_hand:

#2286 Ensures that `@qfunc_transform` decorated functions display their signatures in the docs
  doc/releases/changelog-dev.md
  pennylane/transforms/qfunc_transforms.py
  tests/transforms/test_qfunc_transform.py
Labels: bug :bug:, documentation :blue_book:

#2199 Add functions to convert openfermion obs to PL obs
  .github/workflows/tests.yml
  pennylane/hf/convert.py
  tests/hf/conftest.py
  tests/hf/test_convert.py
Labels: qchem :atom_symbol:

#2272 Modify the differentiable HF solver function names
  pennylane/hf/__init__.py
  pennylane/hf/dipole.py
  pennylane/hf/hamiltonian.py
  pennylane/hf/hartree_fock.py
  pennylane/hf/integrals.py
  pennylane/hf/matrices.py
  pennylane/hf/molecule.py
  tests/hf/test_hamiltonians.py
  tests/hf/test_hartree_fock.py
  tests/hf/test_integrals.py
  tests/hf/test_matrices.py
  tests/hf/test_molecule.py
  tests/hf/test_tapering.py
Labels: qchem :atom_symbol:

#2306 Deprecate jacobian tape
  doc/releases/changelog-dev.md
  pennylane/gradients/__init__.py
  pennylane/gradients/finite_difference.py
  pennylane/gradients/gradient_transform.py
  pennylane/gradients/param_shift_hessian.py
  pennylane/gradients/parameter_shift.py
  pennylane/gradients/parameter_shift_cv.py
  pennylane/gradients/vjp.py
  pennylane/interfaces/batch/__init__.py
  pennylane/measurements.py
  pennylane/operation.py
  pennylane/optimize/lie_algebra.py
  pennylane/qnode.py
  pennylane/qnode_old.py
  pennylane/tape/cv_param_shift.py
  pennylane/tape/jacobian_tape.py
  pennylane/tape/qubit_param_shift.py
  pennylane/tape/reversible.py
  pennylane/tape/tape.py
  pennylane/transforms/batch_transform.py
  pennylane/transforms/qfunc_transforms.py
  pennylane/transforms/tape_expand.py
  tests/gradients/test_finite_difference.py
  tests/gradients/test_gradient_transform.py
  tests/gradients/test_hamiltonian_gradient.py
  tests/gradients/test_parameter_shift.py
  tests/gradients/test_parameter_shift_cv.py
  tests/gradients/test_vjp.py
  tests/interfaces/test_batch_autograd.py
  tests/interfaces/test_batch_autograd_qnode.py
  tests/interfaces/test_batch_jax.py
  tests/interfaces/test_batch_jax_qnode.py
  tests/interfaces/test_batch_tensorflow.py
  tests/interfaces/test_batch_tensorflow_qnode.py
  tests/interfaces/test_batch_torch.py
  tests/interfaces/test_batch_torch_qnode.py
  tests/qnn/test_keras.py
  tests/tape/test_qnode_old.py
  tests/templates/test_subroutines/test_approx_time_evolution.py
  tests/templates/test_subroutines/test_qpe.py
  tests/test_device.py
  tests/test_qnode.py
  tests/test_qubit_device.py
  tests/test_qubit_device_adjoint_jacobian.py
  tests/transforms/test_adjoint.py
  tests/transforms/test_adjoint_metric_tensor.py
  tests/transforms/test_batch_transform.py
  tests/transforms/test_hamiltonian_expand.py
  tests/transforms/test_metric_tensor.py
  tests/transforms/test_optimization/test_undo_swaps.py
  tests/transforms/test_tape_expand.py
Labels: review-ready :ok_hand:

#2305 Add `qml.generator(op)` backwards compatibility
  pennylane/operation.py
  pennylane/ops/functions/generator.py
  tests/ops/functions/test_generator.py
Labels: review-ready :ok_hand:

#2336 Remove tape subclasses and old QNode
  codecov.yml
  doc/code/qml_tape.rst
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/gradients/hamiltonian_grad.py
  pennylane/interfaces/autograd.py
  pennylane/interfaces/jax.py
  pennylane/interfaces/tf.py
  pennylane/interfaces/torch.py
  pennylane/qnn/keras.py
  pennylane/qnn/torch.py
  pennylane/qnode_old.py
  pennylane/tape/__init__.py
  pennylane/tape/cv_param_shift.py
  pennylane/tape/jacobian_tape.py
  pennylane/tape/qubit_param_shift.py
  pennylane/tape/reversible.py
  pennylane/tape/tape.py
  pennylane/transforms/batch_input.py
  pennylane/transforms/batch_transform.py
  pennylane/transforms/specs.py
  tests/interfaces/test_qnode_autograd.py
  tests/interfaces/test_qnode_jax.py
  tests/interfaces/test_qnode_tf.py
  tests/interfaces/test_qnode_torch.py
  tests/interfaces/test_tape_autograd.py
  tests/interfaces/test_tape_jax.py
  tests/interfaces/test_tape_tf.py
  tests/interfaces/test_tape_torch.py
  tests/tape/test_cv_param_shift.py
  tests/tape/test_jacobian_tape.py
  tests/tape/test_qnode_old.py
  tests/tape/test_qubit_param_shift.py
  tests/tape/test_reversible.py
  tests/tape/test_tape.py
  tests/transforms/test_specs.py
Labels: review-ready :ok_hand:

#2310 Remove all old circuit drawing stuff
  doc/releases/changelog-dev.md
  pennylane/circuit_graph.py
  pennylane/drawer/__init__.py
  pennylane/drawer/charsets.py
  pennylane/drawer/circuit_drawer.py
  pennylane/drawer/drawable_layers.py
  pennylane/drawer/grid.py
  pennylane/drawer/representation_resolver.py
  pennylane/tape/tape.py
  pennylane/transforms/__init__.py
  pennylane/transforms/draw.py
  tests/drawer/test_circuit_drawer.py
  tests/drawer/test_drawable_layers.py
  tests/drawer/test_grid.py
  tests/drawer/test_representation_resolver.py
  tests/tape/test_tape.py
  tests/transforms/test_draw_old.py
Labels: review-ready :ok_hand:

#2333 Support eigvals for sparse hamiltonians
  doc/releases/changelog-dev.md
  pennylane/ops/functions/eigvals.py
  tests/ops/functions/test_eigvals.py
Labels: enhancement :sparkles:

#2164 Create qchem refactoring feature branch
  .github/workflows/tests.yml
  doc/releases/changelog-dev.md
  qchem/pennylane_qchem/__init__.py
  qchem/pennylane_qchem/qchem/hf/__init__.py
  qchem/pennylane_qchem/qchem/hf/basis_data.py
  qchem/pennylane_qchem/qchem/hf/basis_set.py
  qchem/pennylane_qchem/qchem/hf/convert.py
  qchem/pennylane_qchem/qchem/hf/dipole.py
  qchem/pennylane_qchem/qchem/hf/hamiltonian.py
  qchem/pennylane_qchem/qchem/hf/hartree_fock.py
  qchem/pennylane_qchem/qchem/hf/integrals.py
  qchem/pennylane_qchem/qchem/hf/matrices.py
  qchem/pennylane_qchem/qchem/hf/molecule.py
  qchem/pennylane_qchem/qchem/hf/observable.py
  qchem/pennylane_qchem/qchem/hf/particle_number.py
  qchem/pennylane_qchem/qchem/hf/spin.py
  qchem/tests/hf/conftest.py
  qchem/tests/hf/test_basis_set.py
  qchem/tests/hf/test_convert.py
  qchem/tests/hf/test_dipole.py
  qchem/tests/hf/test_hamiltonians.py
  qchem/tests/hf/test_hartree_fock.py
  qchem/tests/hf/test_integrals.py
  qchem/tests/hf/test_matrices.py
  qchem/tests/hf/test_molecule.py
  qchem/tests/hf/test_observable_qchem.py
  qchem/tests/hf/test_particle_number.py
  qchem/tests/hf/test_spin.py
Labels: do not merge :warning:, qchem :atom_symbol:

#2215 Implement consistent output shapes for batch transforms
  doc/releases/changelog-dev.md
  pennylane/gradients/finite_difference.py
  pennylane/gradients/gradient_transform.py
  pennylane/gradients/hessian_transform.py
  pennylane/gradients/param_shift_hessian.py
  pennylane/gradients/parameter_shift.py
  pennylane/gradients/parameter_shift_cv.py
  pennylane/interfaces/batch/__init__.py
  pennylane/math/__init__.py
  pennylane/math/multi_dispatch.py
  pennylane/math/single_dispatch.py
  pennylane/qnode.py
  pennylane/tape/tape.py
  pennylane/transforms/batch_transform.py
  pennylane/transforms/mitigate.py
  tests/gradients/test_finite_difference.py
  tests/gradients/test_gradient_transform.py
  tests/gradients/test_param_shift_hessian.py
  tests/gradients/test_parameter_shift.py
  tests/math/test_functions.py
  tests/test_quantum_gradients.py
Labels: bug :bug:

#2337 Move interfaces and interface tests out of the batch folder
  pennylane/__init__.py
  pennylane/interfaces/__init__.py
  pennylane/interfaces/autograd.py
  pennylane/interfaces/batch/__init__.py
  pennylane/interfaces/jax.py
  pennylane/interfaces/jax_jit.py
  pennylane/interfaces/tensorflow.py
  pennylane/interfaces/tensorflow_autograph.py
  pennylane/interfaces/torch.py
  pennylane/qnode.py
  tests/gpu/test_gpu_torch.py
  tests/interfaces/test_autograd.py
  tests/interfaces/test_autograd_qnode.py
  tests/interfaces/test_jax.py
  tests/interfaces/test_jax_qnode.py
  tests/interfaces/test_tensorflow.py
  tests/interfaces/test_tensorflow_qnode.py
  tests/interfaces/test_torch.py
  tests/interfaces/test_torch_qnode.py
Labels: review-ready :ok_hand:

#2338 Reorganize interface source code and documentation
  doc/releases/changelog-dev.md
  pennylane/interfaces/__init__.py
  pennylane/interfaces/execution.py
  pennylane/interfaces/set_shots.py
  pennylane/interfaces/torch.py
  pennylane/tape/tape.py
Labels: review-ready :ok_hand:

#2339 Remove deprecated tape execution methods
  doc/releases/changelog-dev.md
  pennylane/tape/tape.py
  tests/tape/test_tape.py
Labels: review-ready :ok_hand:

#2316 Improve performance of computing molecular integrals and Hamiltonian
  doc/releases/changelog-dev.md
  pennylane/hf/hamiltonian.py
  pennylane/hf/integrals.py
  qchem/pennylane_qchem/qchem/hf/integrals.py
  qchem/tests/hf/test_integrals.py
  tests/hf/test_integrals.py
Labels: qchem :atom_symbol:

#2362 Remove openfermion dependency for spin and particle number obs
  doc/releases/changelog-dev.md
  qchem/pennylane_qchem/__init__.py
  qchem/pennylane_qchem/qchem/hf/__init__.py
  qchem/pennylane_qchem/qchem/obs.py
  qchem/pennylane_qchem/qchem/particle_number.py
  qchem/pennylane_qchem/qchem/spin.py
  qchem/tests/test_particle_number.py
  qchem/tests/test_particle_number_obs.py
  qchem/tests/test_s2_obs.py
  qchem/tests/test_spin.py
  qchem/tests/test_sz_obs.py
Labels: qchem :atom_symbol:

#2371 Add openfermion conversion module to qml.ops
  doc/releases/changelog-dev.md
  qchem/pennylane_qchem/__init__.py
  qchem/pennylane_qchem/qchem/__init__.py
  qchem/pennylane_qchem/qchem/convert.py
  qchem/pennylane_qchem/qchem/hf/__init__.py
  qchem/pennylane_qchem/qchem/obs.py
  qchem/pennylane_qchem/qchem/structure.py
  qchem/tests/test_convert.py
  qchem/tests/test_convert_observable.py
  qchem/tests/test_observable.py
Labels: qchem :atom_symbol:

#2385 Merge qchem and hf modules
  .gitignore
  doc/code/qml_qchem.rst
  qchem/pennylane_qchem/__init__.py
  qchem/pennylane_qchem/qchem/__init__.py
  qchem/pennylane_qchem/qchem/basis_data.py
  qchem/pennylane_qchem/qchem/basis_set.py
  qchem/pennylane_qchem/qchem/dipole.py
  qchem/pennylane_qchem/qchem/hamiltonian.py
  qchem/pennylane_qchem/qchem/hartree_fock.py
  qchem/pennylane_qchem/qchem/hf/__init__.py
  qchem/pennylane_qchem/qchem/integrals.py
  qchem/pennylane_qchem/qchem/matrices.py
  qchem/pennylane_qchem/qchem/molecule.py
  qchem/pennylane_qchem/qchem/obs.py
  qchem/pennylane_qchem/qchem/observable_hf.py
  qchem/pennylane_qchem/qchem/openfermion_obs.py
  qchem/pennylane_qchem/qchem/particle_number.py
  qchem/pennylane_qchem/qchem/spin.py
  qchem/tests/hf_tests/conftest.py
  qchem/tests/hf_tests/test_basis_set.py
  qchem/tests/hf_tests/test_dipole.py
  qchem/tests/hf_tests/test_hamiltonians.py
  qchem/tests/hf_tests/test_hartree_fock.py
  qchem/tests/hf_tests/test_integrals.py
  qchem/tests/hf_tests/test_matrices.py
  qchem/tests/hf_tests/test_molecule.py
  qchem/tests/hf_tests/test_observable_hf.py
  qchem/tests/hf_tests/test_particle_number.py
  qchem/tests/hf_tests/test_spin.py
  qchem/tests/qchem_tests/conftest.py
  qchem/tests/qchem_tests/test_active_space.py
  qchem/tests/qchem_tests/test_convert.py
  qchem/tests/qchem_tests/test_decompose.py
  qchem/tests/qchem_tests/test_deriv_hamilt.py
  qchem/tests/qchem_tests/test_dipole_of.py
  qchem/tests/qchem_tests/test_excitations.py
  qchem/tests/qchem_tests/test_excitations_to_wires.py
  qchem/tests/qchem_tests/test_hf_state.py
  qchem/tests/qchem_tests/test_meanfield.py
  qchem/tests/qchem_tests/test_molecular_hamiltonian.py
  qchem/tests/qchem_tests/test_observable.py
  qchem/tests/qchem_tests/test_one_particle.py
  qchem/tests/qchem_tests/test_read_structure.py
  qchem/tests/qchem_tests/test_ref_files/dummy_ansatz_parameters.npy
  qchem/tests/qchem_tests/test_ref_files/gdb3.hdf5
  qchem/tests/qchem_tests/test_ref_files/gdb3.mol5.PDB
  qchem/tests/qchem_tests/test_ref_files/gdb3.mol5.XYZ
  qchem/tests/qchem_tests/test_ref_files/gdb3.mol5_ref.xyz
  qchem/tests/qchem_tests/test_ref_files/h2.SDF
  qchem/tests/qchem_tests/test_ref_files/h2_pyscf.hdf5
  qchem/tests/qchem_tests/test_ref_files/h2_ref.xyz
  qchem/tests/qchem_tests/test_ref_files/h2o_psi4.hdf5
  qchem/tests/qchem_tests/test_ref_files/lih.hdf5
  qchem/tests/qchem_tests/test_ref_files/lih_anion.hdf5
  qchem/tests/qchem_tests/test_ref_files/lih_anion_2.hdf5
  qchem/tests/qchem_tests/test_two_particle.py
Labels: qchem :atom_symbol:
