Repository PennyLaneAI/pennylane, pull requests merged in 2022-10, with the labels that each got.

#3011 Add qchem basis rotation function
  doc/releases/changelog-dev.md
  pennylane/qchem/__init__.py
  pennylane/qchem/factorization.py
  tests/qchem/test_factorization.py
Labels: qchem :atom_symbol:

#3138 QNode improve code quality
  pennylane/qnode.py
Labels: review-ready :ok_hand:

#3140 Update usage details in the UCCSD template
  doc/releases/changelog-dev.md
  pennylane/templates/subroutines/uccsd.py
Labels: qchem :atom_symbol:

#3136 Support sequences of operations in `get_interface` function
  doc/releases/changelog-dev.md
  pennylane/_qubit_device.py
  pennylane/math/__init__.py
  pennylane/math/multi_dispatch.py
  pennylane/math/utils.py
  pennylane/ops/functions/matrix.py
  pennylane/ops/qubit/parametric_ops.py
  pennylane/transforms/optimization/optimization_utils.py
  tests/math/test_functions.py
  tests/templates/test_layers/test_gate_fabric.py
Labels: review-ready :ok_hand:

#3098 [Return-types Fix #3] Update `.shape` and `.numeric_type` attribute for `QuantumTape`
  pennylane/measurements.py
  pennylane/tape/tape.py
  tests/returntypes/test_new_tape.py
Labels: review-ready :ok_hand:

#2589 Implementation of no-op qubit device
  doc/releases/changelog-dev.md
  pennylane/devices/__init__.py
  pennylane/devices/null_qubit.py
  pennylane/tape/tape.py
  setup.py
  tests/devices/test_default_qubit.py
  tests/devices/test_null_qubit.py
Labels: review-ready :ok_hand:

#3049 Identity accepts multiple wires.
  doc/releases/changelog-dev.md
  pennylane/operation.py
  pennylane/ops/identity.py
  pennylane/ops/op_math/pow.py
  pennylane/ops/op_math/prod.py
  pennylane/ops/op_math/sum.py
  tests/ops/op_math/test_pow_op.py
  tests/ops/op_math/test_prod.py
  tests/ops/op_math/test_sprod.py
  tests/ops/op_math/test_sum.py
  tests/ops/qubit/test_non_parametric_ops.py
  tests/ops/test_identity.py
  tests/test_operation.py
Labels: review-ready :ok_hand:

#3134 Cache nonparametric matrices
  doc/releases/changelog-dev.md
  pennylane/ops/identity.py
  pennylane/ops/qubit/non_parametric_ops.py
Labels: performance :timer_clock:, op-arithmetic

#3145 Map wires #2: Add top-level `qml.map_wires` function
  doc/releases/changelog-dev.md
  pennylane/measurements.py
  pennylane/ops/functions/__init__.py
  pennylane/ops/functions/map_wires.py
  pennylane/tape/tape.py
  tests/ops/functions/test_map_wires.py
Labels: review-ready :ok_hand:

#3216 Switch from deprecated `set-output` GH actions usage
  .github/workflows/tests-gpu.yml
Labels: gpu

#3084 Compute matrix of only the operators that act on overlapping wires
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/composite.py
  pennylane/ops/op_math/prod.py
  pennylane/ops/op_math/sum.py
  tests/ops/op_math/test_composite.py
Labels: review-ready :ok_hand:

#3186 Stop using _wire setter and use map_wires instead.
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/controlled_class.py
  pennylane/ops/op_math/symbolicop.py
  pennylane/transforms/commutation_dag.py
  pennylane/transforms/optimization/pattern_matching.py
  pennylane/transforms/qcut.py
  tests/ops/op_math/test_adjoint_op.py
  tests/ops/op_math/test_controlled_op.py
  tests/ops/op_math/test_pow_op.py
  tests/ops/op_math/test_symbolic_op.py
  tests/transforms/test_qcut.py
Labels: review-ready :ok_hand:

#3209 Better integrating `QuantumScript`
  doc/releases/changelog-dev.md
  pennylane/ops/functions/simplify.py
  pennylane/transforms/batch_transform.py
  pennylane/transforms/hamiltonian_expand.py
  pennylane/transforms/op_transforms.py
  pennylane/transforms/split_non_commuting.py
  tests/ops/functions/test_matrix.py
  tests/transforms/test_batch_transform.py
  tests/transforms/test_hamiltonian_expand.py
  tests/transforms/test_op_transform.py
  tests/transforms/test_split_non_commuting.py
Labels: review-ready :ok_hand:

#3193 Favor decomposition and avoid matrix construction for large operations
  doc/releases/changelog-dev.md
  pennylane/_device.py
  pennylane/devices/default_qubit.py
  tests/devices/test_default_qubit.py
  tests/optimize/test_optimize_shot_adaptive.py
  tests/templates/test_subroutines/test_grover.py
  tests/templates/test_subroutines/test_qft.py
Labels: review-ready :ok_hand:

#2844 Controlled Qutrit Unitary
  doc/introduction/operations.rst
  doc/releases/changelog-dev.md
  pennylane/devices/default_qutrit.py
  pennylane/ops/qutrit/__init__.py
  pennylane/ops/qutrit/matrix_ops.py
  tests/ops/qutrit/test_qutrit_matrix_ops.py
Labels: review-ready :ok_hand:

#3212 Sort module documentation pages
  doc/index.rst
Labels: documentation :blue_book:

#3213 Make qchem differentiable parameters consistent with larger basis
  doc/releases/changelog-dev.md
  pennylane/qchem/matrices.py
  tests/qchem/test_dipole.py
  tests/qchem/test_hartree_fock.py
Labels: qchem :atom_symbol:
