Repository PennyLaneAI/pennylane, pull requests merged in 2022-07, with the labels that each got.

#2475 Operator Arithmetic `Sum` wrapper class implementation
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/_qubit_device.py
  pennylane/devices/default_qubit.py
  pennylane/math/__init__.py
  pennylane/math/multi_dispatch.py
  pennylane/measurements.py
  pennylane/ops/__init__.py
  pennylane/ops/identity.py
  pennylane/ops/op_math/__init__.py
  pennylane/ops/op_math/sum.py
  pennylane/ops/qubit/non_parametric_ops.py
  pennylane/ops/qubit/state_preparation.py
  tests/gate_data.py
  tests/ops/op_math/test_sum.py
Labels: op-arithmetic

#2757 Diffable ZNE error mitigation `mitigate_with_zne`
  doc/_static/fold_global_zne_by-hand.png
  doc/releases/changelog-dev.md
  pennylane/math/single_dispatch.py
  pennylane/transforms/__init__.py
  pennylane/transforms/mitigate.py
  tests/transforms/test_mitigate.py
Labels: review-ready :ok_hand:

#2622 Operator Arithmetic Scalar Product wrapper class implementation
  doc/releases/changelog-dev.md
  pennylane/_qubit_device.py
  pennylane/devices/default_qubit.py
  pennylane/math/__init__.py
  pennylane/math/multi_dispatch.py
  pennylane/measurements.py
  pennylane/ops/op_math/__init__.py
  pennylane/ops/op_math/sprod.py
  pennylane/ops/op_math/symbolicop.py
  tests/ops/op_math/test_sprod.py
  tests/optimize/test_optimize_shot_adapative.py
Labels: op-arithmetic

#2797 Modify resource estimation docs and methods
  pennylane/resource/__init__.py
  pennylane/resource/first_quantization.py
  pennylane/resource/second_quantization.py
  tests/resource/test_first_quantization.py
  tests/resource/test_second_quantization.py
Labels: WIP :construction:

#2857 Expectation values of grouped Hamiltonians is incompatible with noisy devices
  doc/releases/changelog-dev.md
  pennylane/tape/tape.py
  tests/transforms/test_insert_ops.py
Labels: bug :bug:

#2634 Add Controlled Operation Wrapper
  doc/releases/changelog-dev.md
  pennylane/drawer/tape_mpl.py
  pennylane/drawer/tape_text.py
  pennylane/ops/op_math/__init__.py
  pennylane/ops/op_math/controlled_class.py
  pennylane/ops/qubit/observables.py
  tests/drawer/test_tape_mpl.py
  tests/drawer/test_tape_text.py
  tests/ops/op_math/test_adjoint_op.py
  tests/ops/op_math/test_controlled_op.py
Labels: review-ready :ok_hand:, op-arithmetic

#2839 Fix cases for `qml.sample(..., counts=True)`
  doc/releases/changelog-dev.md
  pennylane/_qubit_device.py
  pennylane/interfaces/autograd.py
  pennylane/interfaces/jax.py
  pennylane/interfaces/tensorflow.py
  pennylane/interfaces/torch.py
  pennylane/measurements.py
  pennylane/qnode.py
  tests/test_measurements.py
Labels: bug :bug:

#2849 Addition of operators and scalars + extra dunder methods
  doc/releases/changelog-dev.md
  pennylane/operation.py
  pennylane/ops/qubit/hamiltonian.py
  tests/test_operation.py
Labels: review-ready :ok_hand:

#2865 Set requires_grad to false for nondiff Hamiltonian coeffs
  doc/releases/changelog-dev.md
  pennylane/qchem/convert.py
  pennylane/qchem/observable_hf.py
  pennylane/qchem/openfermion_obs.py
  tests/qchem/of_tests/test_molecular_hamiltonian.py
Labels: qchem :atom_symbol:

#2850 Remove excessive basis set normalisation
  doc/releases/changelog-dev.md
  pennylane/qchem/integrals.py
  pennylane/qchem/matrices.py
  pennylane/qchem/molecule.py
  tests/qchem/test_integrals.py
  tests/qchem/test_molecule.py
Labels: qchem :atom_symbol:
