Repository PennyLaneAI/pennylane, pull requests merged in 2022-12, with the labels that each got.

#3391 `hamiltonian()` and `operation()` methods to convert `PauliSentence` into native PL operators or Hamiltonians (PauliUtility #3)
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/exp.py
  pennylane/pauli/pauli_arithmetic.py
  tests/pauli/test_pauli_arithmetic.py
Labels: review-ready :ok_hand:

#3389 Add `pauli_sentence()` function which takes native PennyLane Ops to `PauliSentence` instance (PauliUtility #2)
  doc/releases/changelog-dev.md
  pennylane/pauli/__init__.py
  pennylane/pauli/conversion.py
  pennylane/pauli/utils.py
  tests/pauli/test_conversion.py
  tests/pauli/test_pauli_utils.py
Labels: review-ready :ok_hand:

#3384 Update `decompose` utility function and move into Pauli module (PauliUtility #1)
  doc/code/qml_utils.rst
  doc/development/deprecations.rst
  doc/introduction/operations.rst
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/ops/functions/generator.py
  pennylane/pauli/__init__.py
  pennylane/pauli/conversion.py
  pennylane/pauli/pauli_arithmetic.py
  pennylane/qchem/tapering.py
  pennylane/utils.py
  tests/ops/functions/test_generator.py
  tests/pauli/test_conversion.py
  tests/test_utils.py
Labels: review-ready :ok_hand:

#3346 [Return-types Fix] Update QCut transforms for new return types
  doc/releases/changelog-dev.md
  pennylane/transforms/qcut/processing.py
  tests/returntypes/transforms/test_qcut_new.py
Labels: review-ready :ok_hand:

#3477 Add support for broadcast `QubitUnitary` in `zyz_decomposition`
  doc/releases/changelog-dev.md
  pennylane/ops/qubit/matrix_ops.py
  pennylane/transforms/decompositions/single_qubit_unitary.py
  tests/ops/qubit/test_matrix_ops.py
  tests/transforms/test_decompositions.py
Labels: merge-ready :heavy_check_mark:

#3508 Fix `matrix` to support Qutrit Ops
  doc/releases/changelog-dev.md
  pennylane/ops/functions/matrix.py
  tests/ops/functions/test_matrix.py
Labels: merge-ready :heavy_check_mark:

#3375 Evolution operator
  doc/releases/changelog-dev.md
  pennylane/devices/default_qubit.py
  pennylane/operation.py
  pennylane/ops/op_math/__init__.py
  pennylane/ops/op_math/exp.py
  pennylane/ops/qubit/hamiltonian.py
  tests/ops/op_math/test_exp.py
  tests/test_operation.py
Labels: merge-ready :heavy_check_mark:

#3446 [ZX calculus] `to_zx`, `from_zx`
  .github/workflows/tests.yml
  doc/releases/changelog-dev.md
  pennylane/transforms/__init__.py
  pennylane/transforms/op_transforms.py
  pennylane/transforms/zx/__init__.py
  pennylane/transforms/zx/converter.py
  tests/transforms/test_zx.py
Labels: merge-ready :heavy_check_mark:

#3367 Modify qchem openfermion Hamiltonian complex coefficient tolerance
  doc/releases/changelog-dev.md
  pennylane/qchem/convert.py
  pennylane/qchem/openfermion_obs.py
  tests/qchem/of_tests/test_convert.py
Labels: merge-ready :heavy_check_mark:, qchem :atom_symbol:

#3356 Add documentation on broadcasting
  doc/introduction/circuits.rst
  doc/releases/changelog-dev.md
  pennylane/operation.py
  pennylane/qnode.py
Labels: merge-ready :heavy_check_mark:

#3340 Qutrit Hadamard
  doc/introduction/operations.rst
  doc/releases/changelog-dev.md
  pennylane/devices/default_qutrit.py
  pennylane/operation.py
  pennylane/ops/qutrit/__init__.py
  pennylane/ops/qutrit/non_parametric_ops.py
  tests/devices/test_default_qutrit.py
  tests/gate_data.py
  tests/ops/qutrit/test_qutrit_non_parametric_ops.py
Labels: merge-ready :heavy_check_mark:, review-ready :ok_hand:

#3443 Integration of PauliArithmetic with native PL classes (Pauli Integration #1)
  doc/releases/changelog-dev.md
  pennylane/operation.py
  pennylane/ops/identity.py
  pennylane/ops/op_math/composite.py
  pennylane/ops/op_math/pow.py
  pennylane/ops/op_math/prod.py
  pennylane/ops/op_math/sprod.py
  pennylane/ops/op_math/sum.py
  pennylane/ops/op_math/symbolicop.py
  pennylane/ops/qubit/non_parametric_ops.py
  pennylane/pauli/pauli_arithmetic.py
  tests/ops/op_math/test_composite.py
  tests/ops/op_math/test_pow_op.py
  tests/ops/op_math/test_prod.py
  tests/ops/op_math/test_sprod.py
  tests/ops/op_math/test_sum.py
  tests/ops/op_math/test_symbolic_op.py
  tests/ops/qubit/test_non_parametric_ops.py
  tests/pauli/test_pauli_arithmetic.py
  tests/test_operation.py
Labels: review-ready :ok_hand:

#3470 Pre release notes
  doc/releases/changelog-dev.md
Labels: merge-ready :heavy_check_mark:

#3373 Implement QPE for operators
  doc/releases/changelog-dev.md
  pennylane/operation.py
  pennylane/ops/op_math/symbolicop.py
  pennylane/templates/subroutines/qpe.py
  tests/templates/test_subroutines/test_qpe.py
Labels: merge-ready :heavy_check_mark:

#3483 Add lazy=True keyword argument to qml.s_prod, qml.prod, and qml.op_sum
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/prod.py
  pennylane/ops/op_math/sprod.py
  pennylane/ops/op_math/sum.py
  tests/ops/op_math/test_prod.py
  tests/ops/op_math/test_sprod.py
  tests/ops/op_math/test_sum.py
Labels: merge-ready :heavy_check_mark:

#3464 Add MPI, PPE and Ray support to new device API demonstrator
  pennylane/devices/experimental/python_device.py
  pennylane/interfaces/autograd.py
Labels: do not merge :warning:

#3501 preserve class type when using from_queue
  doc/releases/changelog-dev.md
  pennylane/tape/qscript.py
  tests/tape/test_qscript.py
Labels: review-ready :ok_hand:

#3462 Use qml math operations in qchem
  pennylane/math/__init__.py
  pennylane/math/multi_dispatch.py
  pennylane/math/single_dispatch.py
  pennylane/pauli/utils.py
  pennylane/qchem/dipole.py
  pennylane/qchem/hamiltonian.py
  pennylane/qchem/hartree_fock.py
  pennylane/qchem/integrals.py
  pennylane/qchem/matrices.py
  pennylane/qchem/observable_hf.py
  pennylane/qchem/tapering.py
  tests/math/test_multi_dispatch.py
  tests/qchem/test_dipole.py
  tests/qchem/test_hamiltonians.py
  tests/qchem/test_hartree_fock.py
  tests/qchem/test_integrals.py
  tests/qchem/test_matrices.py
Labels: qchem :atom_symbol:
