Repository PennyLaneAI/pennylane, pull requests merged in 2022-05, with the labels that each got.

#2500 Modify qchem imports and chemistry quickstart page
  doc/code/qml_qchem.rst
  doc/introduction/chemistry.rst
  doc/introduction/operations.rst
  pennylane/__init__.py
  pennylane/qchem/convert.py
  pennylane/qchem/hamiltonian.py
Labels: qchem :atom_symbol:

#2548 Fix PennyLane v0.23.1 to work with Autoray 0.3.1
  doc/development/release_notes.md
  doc/releases/changelog-0.23.0.md
  doc/releases/changelog-0.23.1.md
  pennylane/_version.py
  pennylane/math/multi_dispatch.py
  pennylane/math/single_dispatch.py
  pennylane/math/utils.py
  requirements.txt
  setup.py
  tests/math/test_functions.py
Labels: bug :bug:

#2225 add `pow` method to operators
  doc/releases/changelog-dev.md
  pennylane/operation.py
  pennylane/ops/identity.py
  pennylane/ops/qubit/matrix_ops.py
  pennylane/ops/qubit/non_parametric_ops.py
  pennylane/ops/qubit/observables.py
  pennylane/ops/qubit/parametric_ops.py
  pennylane/ops/qubit/qchem_ops.py
  tests/ops/qubit/test_matrix_ops.py
  tests/ops/qubit/test_non_parametric_ops.py
  tests/ops/qubit/test_observables.py
  tests/ops/qubit/test_parametric_ops.py
  tests/ops/qubit/test_qchem_ops.py
  tests/ops/test_identity.py
  tests/test_operation.py
Labels: review-ready :ok_hand:, op-arithmetic

#2561 Compressed Sparse Row (CSR) representation for Hamiltonians and Tensors
  doc/releases/changelog-dev.md
  pennylane/devices/default_qubit.py
  pennylane/devices/tests/test_measurements.py
  pennylane/operation.py
  pennylane/ops/qubit/observables.py
  pennylane/ops/qubit/qchem_ops.py
  pennylane/utils.py
  tests/ops/functions/test_eigvals.py
  tests/ops/functions/test_generator.py
  tests/ops/qubit/test_sparse.py
  tests/test_operation.py
  tests/test_qnode.py
  tests/test_utils.py
Labels: review-ready :ok_hand:

#2593 Localise and decrease openfermion-dependency in qchem tests
  doc/releases/changelog-dev.md
  tests/qchem/hf_tests/conftest.py
  tests/qchem/of_tests/test_active_space.py
  tests/qchem/of_tests/test_excitations.py
  tests/qchem/of_tests/test_excitations_to_wires.py
  tests/qchem/of_tests/test_hf_state.py
  tests/qchem/of_tests/test_molecular_hamiltonian.py
  tests/qchem/of_tests/test_read_structure.py
  tests/qchem/test_basis_set.py
  tests/qchem/test_dipole.py
  tests/qchem/test_hamiltonians.py
  tests/qchem/test_hartree_fock.py
  tests/qchem/test_integrals.py
  tests/qchem/test_matrices.py
  tests/qchem/test_molecule.py
  tests/qchem/test_observable_hf.py
  tests/qchem/test_particle_number.py
  tests/qchem/test_ref_files/gdb3.mol5.XYZ
  tests/qchem/test_spin.py
  tests/qchem/test_structure.py
  tests/qchem/test_tapering.py
Labels: WIP :construction:, qchem :atom_symbol:

#2629 [WIP] Add `is_hermitian` property to `Operator`
  doc/releases/changelog-dev.md
  pennylane/measurements.py
  pennylane/operation.py
  tests/test_operation.py
Labels: op-arithmetic
