Repository PennyLaneAI/pennylane, pull requests merged in 2023-10, with the labels that each got.

#4628 Track qpu executions and shots on default qubit
  doc/releases/changelog-dev.md
  pennylane/devices/default_qubit.py
  pennylane/devices/qubit/sampling.py
  tests/devices/experimental/test_default_qubit_2.py
  tests/devices/test_default_qubit_tracking.py
  tests/gradients/finite_diff/test_finite_difference.py
  tests/gradients/finite_diff/test_finite_difference_shot_vec.py
  tests/gradients/finite_diff/test_spsa_gradient.py
  tests/gradients/finite_diff/test_spsa_gradient_shot_vec.py
  tests/gradients/parameter_shift/test_parameter_shift.py
  tests/gradients/parameter_shift/test_parameter_shift_shot_vec.py
  tests/interfaces/default_qubit_2_integration/test_autograd_default_qubit_2.py
  tests/test_vqe.py
Labels: review-ready :ok_hand:

#4527 Add `DeviceDerivatives` jacobian product calculator
  doc/releases/changelog-dev.md
  pennylane/_device.py
  pennylane/gradients/hadamard_gradient.py
  pennylane/interfaces/__init__.py
  pennylane/interfaces/jacobian_products.py
  tests/gradients/core/test_hadamard_gradient.py
  tests/interfaces/test_jacobian_products.py
  tests/param_shift_dev.py
  tests/test_device.py
  tests/test_qubit_device.py
Labels: review-ready :ok_hand:

#4638 Lighten and Optimize Build CI
  .github/workflows/interface-unit-tests.yml
  .github/workflows/jax_tests_durations.json
  .github/workflows/tests.yml
  .github/workflows/tf_tests_durations.json
  .github/workflows/unit-test.yml
Labels: merge-ready :heavy_check_mark:

#4637 Add `DeviceJacobianProducts` jacobian product calculator
  doc/releases/changelog-dev.md
  pennylane/devices/device_api.py
  pennylane/devices/qubit/adjoint_jacobian.py
  pennylane/interfaces/__init__.py
  pennylane/interfaces/jacobian_products.py
  tests/devices/qubit/test_adjoint_jacobian.py
  tests/interfaces/test_jacobian_products.py
  tests/param_shift_dev.py
Labels: merge-ready :heavy_check_mark:, review-ready :ok_hand:

#4696 Small fix for transform program and previous device API + typo
  pennylane/qnode.py
Labels: merge-ready :heavy_check_mark:

#4690 Minor improvements to PL plot style
  doc/code/qml_drawer.rst
  doc/releases/changelog-dev.md
  pennylane/drawer/plot.mplstyle
Labels: merge-ready :heavy_check_mark:

#4674 Improve performance of qml.data.load() when partially loading a dataset
  doc/releases/changelog-dev.md
  pennylane/data/base/hdf5.py
  pennylane/data/data_manager/__init__.py
  tests/data/base/test_hdf5.py
  tests/data/data_manager/test_dataset_access.py
Labels: merge-ready :heavy_check_mark:

#4695 add logging call to default_qubit.execute
  pennylane/devices/default_qubit.py
  tests/logging/test_logging_autograd.py
Labels: merge-ready :heavy_check_mark:

#4669 Fix logging trace statement with empty gradient_fn
  doc/releases/changelog-dev.md
  pennylane/interfaces/autograd.py
  pennylane/interfaces/execution.py
  pennylane/interfaces/jacobian_products.py
  pennylane/interfaces/jax.py
  pennylane/interfaces/tensorflow.py
  pennylane/interfaces/torch.py
  pennylane/qnode.py
Labels: merge-ready :heavy_check_mark:

#4681 Fix full dataset download after partial
  doc/releases/changelog-dev.md
  pennylane/data/data_manager/__init__.py
  tests/data/data_manager/test_dataset_access.py
Labels: merge-ready :heavy_check_mark:

#4671 `qml.QDrift` template
  doc/_static/templates/subroutines/qdrift.png
  doc/introduction/templates.rst
  doc/releases/changelog-dev.md
  pennylane/templates/subroutines/__init__.py
  pennylane/templates/subroutines/qdrift.py
  tests/templates/test_subroutines/test_qdrift.py
Labels: merge-ready :heavy_check_mark:

#4679 Update docs for `ApproxTimeEvolution` to reference `TrotterProduct`
  pennylane/templates/subroutines/approx_time_evolution.py
Labels: merge-ready :heavy_check_mark:

#4683 `CosineWindow` StatePrep
  doc/_static/templates/state_preparations/cosine_window.png
  doc/_static/templates/state_preparations/thumbnail_cosine_window.png
  doc/introduction/templates.rst
  doc/releases/changelog-dev.md
  pennylane/templates/state_preparations/__init__.py
  pennylane/templates/state_preparations/cosine_window.py
  tests/templates/test_state_preparations/test_cosine_window.py
Labels: merge-ready :heavy_check_mark:

#4702 Compiler documentation
  doc/conf.py
  doc/introduction/compiling_circuits.rst
  pennylane/compiler/__init__.py
  pennylane/compiler/qjit_api.py
Labels: documentation :blue_book:

#4707 Recreate CtrlSequence PR
  doc/_static/templates/subroutines/big_ctrl.png
  doc/_static/templates/subroutines/small_ctrl.png
  doc/introduction/templates.rst
  pennylane/operation.py
  pennylane/ops/op_math/composite.py
  pennylane/ops/op_math/controlled.py
  pennylane/ops/op_math/pow.py
  pennylane/ops/op_math/symbolicop.py
  pennylane/templates/subroutines/__init__.py
  pennylane/templates/subroutines/controlled_sequence.py
  tests/templates/test_subroutines/test_controlled_sequence.py
Labels: merge-ready :heavy_check_mark:

#4701 `defer_measurements` raises errors for unsupported measurements
  doc/releases/changelog-dev.md
  pennylane/devices/default_qubit.py
  pennylane/transforms/defer_measurements.py
  tests/devices/default_qubit/test_default_qubit.py
  tests/transforms/test_defer_measurements.py
Labels: merge-ready :heavy_check_mark:

#4719 Fix `LocalHilbertSchmidt` template
  doc/releases/changelog-0.33.0.md
  pennylane/templates/subroutines/hilbert_schmidt.py
  tests/templates/test_subroutines/test_hilbert_schmidt.py
Labels: bug :bug:

#4732 fix transpile for state measurement
  doc/releases/changelog-0.33.0.md
  pennylane/transforms/transpile.py
  tests/transforms/test_transpile.py
Labels: bug :bug:

#4730 qml demo fixes: avoid queuing unneeded projectors
  pennylane/pulse/rydberg.py
  tests/pulse/test_rydberg.py
Labels: bug :bug:

#4735 Update docs to reflect difference in convention for Trotter decomposition
  pennylane/templates/subroutines/approx_time_evolution.py
  pennylane/templates/subroutines/trotter.py
  tests/templates/test_subroutines/test_trotter.py
Labels: merge-ready :heavy_check_mark:
