Repository PennyLaneAI/pennylane, pull requests merged in 2023-03, with the labels that each got.

#3789 [CHORE] Split parametric_ops.py into 3 files
  pennylane/ops/qubit/__init__.py
  pennylane/ops/qubit/attributes.py
  pennylane/ops/qubit/parametric_ops.py
  pennylane/ops/qubit/parametric_ops_controlled.py
  pennylane/ops/qubit/parametric_ops_multi_qubit.py
  pennylane/ops/qubit/parametric_ops_single_qubit.py
  pennylane/ops/qubit/special_unitary.py
Labels: code quality :mortar_board:

#3908 Add corrections to pyscf dipole coeffs
  doc/releases/changelog-dev.md
  tests/qchem/of_tests/test_dipole_of.py
Labels: qchem :atom_symbol:

#3005 Allow different degrees for different parameters in Fourier tools
  doc/releases/changelog-0.26.0.md
  doc/releases/changelog-dev.md
  pennylane/fourier/coefficients.py
  pennylane/fourier/utils.py
  pennylane/fourier/visualize.py
  tests/fourier/test_coefficients.py
  tests/fourier/test_visualize.py
  tests/tests_passing_pylint.txt
Labels: review-ready :ok_hand:

#3913 Torch QNN adapted for new return type
  .github/workflows/tests.yml
  doc/releases/changelog-dev.md
  pennylane/qnn/torch.py
  tests/returntypes/qnn/conftest.py
  tests/returntypes/qnn/test_qnn_torch_new.py
  tests/tests_passing_pylint.txt
Labels: gpu

#3932 Update to torch 2.0.0
  .github/workflows/tests.yml
Labels: gpu

#3885 Modify attribute types in qml.molecule
  doc/releases/changelog-dev.md
  pennylane/qchem/molecule.py
Labels: qchem :atom_symbol:

#3942 Improve efficiency of tapering hamiltonians
  doc/releases/changelog-dev.md
  pennylane/qchem/tapering.py
  tests/qchem/test_tapering.py
Labels: merge-ready :heavy_check_mark:
