Repository PennyLaneAI/pennylane, pull requests merged in 2023-08, with the labels that each got.

#4401 Update `default_expand_fn` to expand operations and measurements independently
  doc/releases/changelog-dev.md
  pennylane/_device.py
  tests/test_device.py
  tests/test_vqe.py
Labels: review-ready :ok_hand:

#4427 Add converter function for PySCF's CISD to PennyLane statevector
  doc/releases/changelog-dev.md
  pennylane/qchem/__init__.py
  pennylane/qchem/convert.py
  tests/qchem/of_tests/test_convert.py
Labels: qchem :atom_symbol:

#4433 Add converter function for PySCF's RCISD and CCSD/UCCSD to PennyLane statevector
  doc/releases/changelog-dev.md
  pennylane/qchem/convert.py
  tests/qchem/of_tests/test_convert.py
Labels: qchem :atom_symbol:

#4437 Support `StatePrep` mid-circuit for `default.qubit` device
  doc/releases/changelog-dev.md
  pennylane/_device.py
  pennylane/devices/qubit/preprocess.py
  pennylane/tape/__init__.py
  pennylane/tape/tape.py
  tests/devices/qubit/test_preprocess.py
  tests/tape/test_tape.py
  tests/test_device.py
Labels: review-ready :ok_hand:

#4456 Adjoint metric tensor uses `devices.qubit` instead of `DefaultQubit` private methods
  doc/releases/changelog-dev.md
  pennylane/ops/functions/map_wires.py
  pennylane/transforms/adjoint_metric_tensor.py
  tests/legacy/test_legacy_adjoint_metric_tensor_old.py
  tests/ops/functions/test_map_wires.py
  tests/transforms/test_adjoint_metric_tensor.py
Labels: merge-ready :heavy_check_mark:

#4458 Register `Operator` classes and pytrees
  doc/releases/changelog-dev.md
  pennylane/operation.py
  pennylane/ops/op_math/adjoint.py
  pennylane/pytrees.py
  tests/devices/experimental/test_default_qubit_2.py
  tests/ops/functions/test_matrix.py
  tests/ops/functions/test_simplify.py
  tests/ops/op_math/test_adjoint.py
  tests/ops/qubit/test_parametric_ops.py
  tests/test_operation.py
Labels: merge-ready :heavy_check_mark:

#4483 Fix `_flatten` for `Identity`
  doc/releases/changelog-dev.md
  pennylane/ops/identity.py
  tests/ops/qubit/test_parametric_ops.py
  tests/ops/test_identity.py
Labels: merge-ready :heavy_check_mark:

#4493 [BUGFIX] Fix `TF` shape computation for `pauli_decompose`
  doc/releases/changelog-dev.md
  pennylane/pauli/conversion.py
  tests/pauli/test_conversion.py
Labels: merge-ready :heavy_check_mark:

#4475 Use the `PauliSentence` representation to obtain sparse matrices
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/prod.py
  pennylane/ops/op_math/sprod.py
  pennylane/ops/op_math/sum.py
  pennylane/pauli/pauli_arithmetic.py
  tests/ops/op_math/test_controlled.py
  tests/ops/op_math/test_sprod.py
Labels: merge-ready :heavy_check_mark:

#4489 avoid op hashing in param-shift-cv and metric-tensor
  doc/releases/changelog-dev.md
  pennylane/gradients/parameter_shift_cv.py
  pennylane/transforms/metric_tensor.py
Labels: merge-ready :heavy_check_mark:

#4494 [BUGFIX] Fix `math.get_dtype_name` for `ArrayBox`
  doc/releases/changelog-dev.md
  pennylane/math/__init__.py
  pennylane/math/single_dispatch.py
  tests/math/test_functions.py
Labels: merge-ready :heavy_check_mark:

#4521 Use fermi sentence in qchem spin functions
  pennylane/qchem/spin.py
Labels: qchem :atom_symbol:

#4506 Change how Select is displayed in circuit drawer
  doc/releases/changelog-0.32.0.md
  pennylane/templates/subroutines/select.py
  tests/templates/test_subroutines/test_select.py
Labels: merge-ready :heavy_check_mark:

#4517 little fixups from timmysilv for the 0.32 release
  pennylane/drawer/style.py
  pennylane/math/fidelity.py
  pennylane/measurements/mid_measure.py
  pennylane/operation.py
  pennylane/pauli/pauli_arithmetic.py
  pennylane/qchem/hamiltonian.py
  pennylane/qchem/observable_hf.py
Labels: merge-ready :heavy_check_mark:

#4525 Update PySCF link in chemistry doc
  doc/introduction/chemistry.rst
Labels: merge-ready :heavy_check_mark:, qchem :atom_symbol:

#4520 More 0.32 related fixes
  doc/code/qml_measurements.rst
  pennylane/measurements/__init__.py
  pennylane/measurements/mid_measure.py
  pennylane/optimize/adaptive.py
Labels: merge-ready :heavy_check_mark:

#4518 bugfixes to unblock teleportation tutorial
  pennylane/transforms/defer_measurements.py
  tests/transforms/test_defer_measurements.py
Labels: merge-ready :heavy_check_mark:

#4491 Update Dataset links to match new website
  doc/introduction/data.rst
  pennylane/data/__init__.py
  pennylane/data/data_manager/__init__.py
Labels: merge-ready :heavy_check_mark:

#4516 Put `defer_measurements` back in QNode construction
  doc/releases/changelog-0.32.0.md
  pennylane/_device.py
  pennylane/qnode.py
  tests/devices/experimental/test_default_qubit_2.py
  tests/test_device.py
  tests/test_qnode.py
Labels: merge-ready :heavy_check_mark:

#4526 Fix incorrect gradient in qml.Select
  pennylane/templates/subroutines/select.py
  tests/templates/test_subroutines/test_select.py
Labels: merge-ready :heavy_check_mark:

#4542 Minor documentation updates to experimental device docstrings
  doc/releases/changelog-dev.md
  pennylane/devices/experimental/device_api.py
  tests/devices/experimental/test_device_api.py
Labels: merge-ready :heavy_check_mark:
