Repository PennyLaneAI/pennylane, pull requests merged in 2023-04, with the labels that each got.

#3926 Amend PCPhase operator to support RZ convention
  pennylane/ops/qubit/parametric_ops_multi_qubit.py
  tests/ops/qubit/test_attributes.py
  tests/ops/qubit/test_parametric_ops.py
Labels: review-ready :ok_hand:

#3790 Add function for adjoint differentiation to `devices.qubit`
  doc/releases/changelog-dev.md
  pennylane/devices/qubit/__init__.py
  pennylane/devices/qubit/adjoint_jacobian.py
  pennylane/devices/qubit/preprocess.py
  tests/devices/qubit/test_adjoint_jacobian.py
  tests/devices/qubit/test_preprocess.py
  tests/legacy/qnn/test_keras_old.py
  tests/legacy/qnn/test_qnn_torch_old.py
Labels: review-ready :ok_hand:

#3955 Make load basis data work in Molecule
  doc/releases/changelog-dev.md
  pennylane/qchem/molecule.py
  tests/qchem/test_molecule.py
Labels: qchem :atom_symbol:

#4002 Ensure PyTorch tensors support CUDA when using `qml.ctrl`
  doc/releases/changelog-dev.md
  pennylane/math/single_dispatch.py
  pennylane/ops/op_math/controlled.py
  tests/devices/test_default_qubit_torch.py
Labels: gpu

#3981 Add `Resources` base class
  doc/releases/changelog-dev.md
  pennylane/resource/__init__.py
  pennylane/resource/resource.py
  tests/resource/test_resource.py
  tests/tests_passing_pylint.txt
Labels: review-ready :ok_hand:

#4018 Update ExpvalCost removal to v0.31
  doc/development/deprecations.rst
Labels: review-ready :ok_hand:

#4020 Remove `seed_recipes` argument from `classical_shadow` and `shadow_expval`
  doc/development/deprecations.rst
  doc/releases/changelog-dev.md
  pennylane/measurements/classical_shadow.py
  tests/measurements/test_classical_shadow.py
Labels: review-ready :ok_hand:, deprecation :wastebasket:

#3977 Make `tapering` workflow memory efficient for larger observables
  doc/releases/changelog-dev.md
  pennylane/qchem/tapering.py
  tests/qchem/test_tapering.py
Labels: qchem :atom_symbol:

#4022 `Operator` converts `tuple` to `np.ndarray`
  doc/releases/changelog-dev.md
  pennylane/operation.py
  tests/test_operation.py
Labels: gpu

#4015 `qml.specs` now uses `Resources` class
  doc/releases/changelog-dev.md
  pennylane/resource/resource.py
  pennylane/tape/qscript.py
  tests/legacy/test_qscript_old.py
  tests/resource/test_resource.py
  tests/tape/test_qscript.py
  tests/tape/test_tape.py
  tests/templates/test_state_preparations/test_mottonen_state_prep.py
  tests/transforms/test_optimization/test_pattern_matching.py
  tests/transforms/test_specs.py
Labels: merge-ready :heavy_check_mark:, review-ready :ok_hand:

#4021 Make `drive` non user-facing
  doc/releases/changelog-dev.md
  pennylane/pulse/__init__.py
  pennylane/pulse/transmon.py
Labels: merge-ready :heavy_check_mark:

#4023 Reverse operation order in QSVT compute_matrix, update tests
  pennylane/templates/subroutines/qsvt.py
  tests/templates/test_subroutines/test_qsvt.py
Labels: merge-ready :heavy_check_mark:

#4024 Update `Evolution` to have -1 factor
  doc/development/deprecations.rst
  doc/releases/changelog-dev.md
  pennylane/ops/functions/evolve.py
  pennylane/ops/op_math/evolution.py
  pennylane/ops/op_math/exp.py
  tests/ops/op_math/test_evolution.py
Labels: merge-ready :heavy_check_mark:

#4012 Update `MeasurementProcess.shape` for new return types and `Shots` class
  doc/releases/changelog-dev.md
  pennylane/measurements/classical_shadow.py
  pennylane/measurements/expval.py
  pennylane/measurements/measurements.py
  pennylane/measurements/mutual_info.py
  pennylane/measurements/probs.py
  pennylane/measurements/purity.py
  pennylane/measurements/sample.py
  pennylane/measurements/state.py
  pennylane/measurements/var.py
  pennylane/measurements/vn_entropy.py
  pennylane/optimize/spsa.py
  pennylane/tape/qscript.py
  tests/legacy/test_classical_shadows_old.py
  tests/legacy/test_measurements_old.py
  tests/legacy/test_qscript_old.py
  tests/measurements/test_classical_shadow.py
  tests/measurements/test_expval.py
  tests/measurements/test_measurements.py
  tests/measurements/test_mid_measure.py
  tests/measurements/test_mutual_info.py
  tests/measurements/test_probs.py
  tests/measurements/test_purity_measurement.py
  tests/measurements/test_sample.py
  tests/measurements/test_state.py
  tests/measurements/test_var.py
  tests/measurements/test_vn_entropy.py
  tests/tape/test_qscript.py
  tests/tests_passing_pylint.txt
Labels: review-ready :ok_hand:

#4036 Fix tensors multiplying Hamiltonians
  doc/releases/changelog-0.30.0.md
  pennylane/operation.py
  pennylane/ops/qubit/hamiltonian.py
  tests/ops/qubit/test_hamiltonian.py
  tests/test_operation.py
Labels: bug :bug:

#4030 Add catalyst to the documentation
  README.md
  doc/_static/header-tall.png
  doc/index.rst
  doc/introduction/compiling_circuits.rst
Labels: documentation :blue_book:, review-ready :ok_hand:
