Repository PennyLaneAI/pennylane, pull requests merged in 2023-05, with the labels that each got.

#4033 Support variable depth in user defined `ResourceOperations`
  doc/releases/changelog-dev.md
  pennylane/circuit_graph.py
  pennylane/resource/resource.py
  tests/circuit_graph/test_circuit_graph.py
  tests/resource/test_resource.py
Labels: review-ready :ok_hand:

#4080 Change Torch version for GPU tests
  .github/workflows/tests-gpu.yml
Labels: gpu

#4011 allow creating a prod op with a qfunc
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/prod.py
  tests/ops/op_math/test_prod.py
Labels: review-ready :ok_hand:

#4083 Add sample measurement function for new device API
  doc/releases/changelog-dev.md
  pennylane/devices/qubit/__init__.py
  pennylane/devices/qubit/sampling.py
  tests/devices/qubit/test_sampling.py
Labels: review-ready :ok_hand:

#4081 Add a `repr` and `str` to the `Shots` class
  doc/releases/changelog-dev.md
  pennylane/measurements/shots.py
  tests/measurements/test_shots.py
Labels: review-ready :ok_hand:

#4082 Add hash and equality support to `Shots`
  doc/releases/changelog-dev.md
  pennylane/measurements/shots.py
  tests/measurements/test_shots.py
Labels: review-ready :ok_hand:

#4093 Add shot vector support to sample measurements
  doc/releases/changelog-dev.md
  pennylane/devices/qubit/sampling.py
  pennylane/measurements/shots.py
  tests/devices/qubit/test_sampling.py
  tests/measurements/test_shots.py
Labels: review-ready :ok_hand:

#4007 `experimental.Device.preprocess` also returns an execution config
  doc/releases/changelog-dev.md
  pennylane/devices/experimental/device_api.py
Labels: discussion :speech_balloon:

#4103 Additional changes for `QuantumScript.shots`
  doc/releases/changelog-dev.md
  pennylane/tape/qscript.py
  pennylane/tape/tape.py
  tests/tape/test_qscript.py
  tests/tape/test_tape.py
Labels: review-ready :ok_hand:

#4087 Wrap objects before adding them to `AnnotatedQueue`
  doc/releases/changelog-dev.md
  pennylane/queuing.py
  tests/test_queuing.py
Labels: review-ready :ok_hand:

#4105 Integrate sample-based measurement with `simulate`
  doc/releases/changelog-dev.md
  pennylane/devices/qubit/sampling.py
  pennylane/devices/qubit/simulate.py
  tests/devices/experimental/test_default_qubit_2.py
  tests/devices/qubit/test_sampling.py
  tests/devices/qubit/test_simulate.py
Labels: review-ready :ok_hand:

#4112 Update tape transforms to copy `shots` attribute
  doc/releases/changelog-dev.md
  pennylane/devices/qubit/preprocess.py
  pennylane/gradients/hadamard_gradient.py
  pennylane/gradients/pulse_gradient.py
  pennylane/ops/functions/simplify.py
  pennylane/qinfo/transforms.py
  pennylane/shadows/transforms.py
  pennylane/transforms/convert_to_numpy_parameters.py
  pennylane/transforms/hamiltonian_expand.py
  pennylane/transforms/qfunc_transforms.py
  pennylane/transforms/sign_expand/sign_expand.py
  tests/devices/qubit/test_preprocess.py
  tests/gradients/core/test_hadamard_gradient.py
  tests/gradients/core/test_pulse_gradient.py
  tests/ops/functions/test_simplify.py
  tests/qinfo/test_fisher.py
  tests/transforms/test_convert_to_numpy_parameters.py
  tests/transforms/test_hamiltonian_expand.py
  tests/transforms/test_qfunc_transform.py
  tests/transforms/test_sign_expand.py
Labels: review-ready :ok_hand:

#4114 Add measurement validation to `preprocess.py`
  doc/releases/changelog-dev.md
  pennylane/devices/qubit/preprocess.py
  tests/devices/qubit/test_preprocess.py
Labels: review-ready :ok_hand:

#4045 Allow `qml.Tracker` to track `Resources` on the `null.qubit` device
  doc/code/qml_resource.rst
  doc/releases/changelog-dev.md
  pennylane/_qubit_device.py
  pennylane/devices/experimental/default_qubit_2.py
  pennylane/devices/null_qubit.py
  pennylane/measurements/shots.py
  pennylane/resource/__init__.py
  pennylane/resource/resource.py
  pennylane/tape/qscript.py
  pennylane/tracker.py
  pennylane/transforms/specs.py
  tests/devices/experimental/test_default_qubit_2.py
  tests/devices/test_null_qubit.py
  tests/measurements/test_shots.py
  tests/resource/test_resource.py
  tests/test_qnode.py
  tests/test_qubit_device.py
Labels: review-ready :ok_hand:

#4120 Allow `DefaultQubit2` to be initialized with a random seed
  doc/releases/changelog-dev.md
  pennylane/devices/experimental/default_qubit_2.py
  tests/devices/experimental/test_default_qubit_2.py
Labels: review-ready :ok_hand:

#4141 Deprecate `QuantumScript.name`
  doc/development/deprecations.rst
  doc/releases/changelog-dev.md
  pennylane/optimize/lie_algebra.py
  pennylane/tape/qscript.py
  pennylane/tape/tape.py
  tests/tape/test_qscript.py
  tests/tape/test_tape.py
Labels: review-ready :ok_hand:

#4117 CZ inherits from Controlled
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/__init__.py
  pennylane/ops/op_math/controlled.py
  pennylane/ops/op_math/controlled_ops.py
  pennylane/ops/qubit/__init__.py
  pennylane/ops/qubit/non_parametric_ops.py
  tests/ops/op_math/test_controlled.py
  tests/ops/op_math/test_controlled_ops.py
  tests/ops/qubit/test_non_parametric_ops.py
Labels: review-ready :ok_hand:

#4173 [QInfo broadcasting (1/3)] Support for `qml.math` density matrix functions
  doc/development/deprecations.rst
  doc/releases/changelog-dev.md
  pennylane/_qubit_device.py
  pennylane/devices/default_mixed.py
  pennylane/math/__init__.py
  pennylane/math/quantum.py
  pennylane/measurements/state.py
  pennylane/qinfo/transforms.py
  tests/math/test_density_matrices.py
  tests/math/test_fidelity_math.py
  tests/measurements/test_state.py
Labels: review-ready :ok_hand:

#4131 Use parameter broadcasting in `KerasLayer` and `TorchLayer`
  doc/releases/changelog-dev.md
  pennylane/qnn/keras.py
  pennylane/qnn/torch.py
  tests/legacy/qnn/test_keras_old.py
  tests/qnn/test_keras.py
  tests/qnn/test_qnn_torch.py
Labels: review-ready :ok_hand:, gpu
