Repository PennyLaneAI/pennylane, pull requests merged in 2023-02, with the labels that each got.

#3704 Bugfix for `qml.draw_mpl` to work with `qml.Snapshot`
  doc/releases/changelog-dev.md
  pennylane/drawer/drawable_layers.py
  pennylane/drawer/tape_mpl.py
  pennylane/ops/snapshot.py
  tests/drawer/test_tape_mpl.py
  tests/drawer/test_tape_text.py
  tests/ops/test_snapshot.py
  tests/tests_passing_pylint.txt
Labels: bug :bug:

#3685 Implement state_vector method on QubitStateVector
  doc/releases/changelog-dev.md
  pennylane/devices/default_qubit.py
  pennylane/ops/qubit/state_preparation.py
  tests/devices/test_default_qubit_tf.py
  tests/devices/test_default_qubit_torch.py
  tests/drawer/test_draw.py
  tests/drawer/test_tape_text.py
  tests/ops/qubit/test_state_prep.py
  tests/tape/test_tape.py
Labels: review-ready :ok_hand:

#1440 Add `fft` submodule to `qml.math`
  doc/releases/changelog-dev.md
  pennylane/math/__init__.py
  pennylane/math/single_dispatch.py
  tests/math/test_functions.py
  tests/math/test_init.py
  tests/tests_passing_pylint.txt
Labels: interface :electric_plug:

#3747 Update sphinx action
  .github/workflows/docs.yml
Labels: gpu

#3745 Fix bug related to labeling of nested controlled operations in drawer
  doc/releases/changelog-dev.md
  pennylane/drawer/tape_mpl.py
  pennylane/drawer/tape_text.py
  pennylane/drawer/utils.py
  tests/drawer/test_drawer_utils.py
  tests/drawer/test_tape_mpl.py
  tests/drawer/test_tape_text.py
Labels: review-ready :ok_hand:

#3748 Add openshell error to qchem
  doc/releases/changelog-dev.md
  pennylane/qchem/molecule.py
  tests/qchem/test_molecule.py
Labels: qchem :atom_symbol:

#3584 Add `tensordot`-based method to `default.mixed` device
  doc/releases/changelog-dev.md
  pennylane/devices/default_mixed.py
  pennylane/ops/channel.py
  tests/devices/test_default_mixed.py
  tests/devices/test_default_mixed_autograd.py
  tests/devices/test_default_mixed_jax.py
  tests/devices/test_default_mixed_tf.py
  tests/devices/test_default_mixed_torch.py
  tests/tests_passing_pylint.txt
Labels: review-ready :ok_hand:, performance :timer_clock:

#3481 Update operator simplify() to use _pauli_rep (Pauli Integration #3)
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/pow.py
  pennylane/ops/op_math/prod.py
  pennylane/ops/op_math/sprod.py
  pennylane/ops/op_math/sum.py
  pennylane/pauli/pauli_arithmetic.py
  tests/ops/op_math/test_prod.py
  tests/ops/op_math/test_sprod.py
  tests/ops/op_math/test_sum.py
  tests/pauli/test_pauli_arithmetic.py
Labels: merge-ready :heavy_check_mark:

#3602 Next generation device interface
  doc/development/guide/architecture.rst
  doc/development/plugins.rst
  doc/releases/changelog-dev.md
  pennylane/_device.py
  pennylane/devices/__init__.py
  pennylane/devices/experimental/__init__.py
  pennylane/devices/experimental/device_api.py
  pennylane/devices/experimental/execution_config.py
  pennylane/gradients/parameter_shift_cv.py
  pennylane/interfaces/autograd.py
  pennylane/interfaces/execution.py
  pennylane/interfaces/jax.py
  pennylane/interfaces/jax_jit.py
  pennylane/interfaces/jax_jit_tuple.py
  pennylane/interfaces/tensorflow.py
  pennylane/interfaces/tensorflow_autograph.py
  pennylane/interfaces/torch.py
  pennylane/measurements/classical_shadow.py
  pennylane/measurements/measurements.py
  pennylane/tape/qscript.py
  pennylane/transforms/insert_ops.py
  pennylane/transforms/qcut/utils.py
  pennylane/transforms/tape_expand.py
Labels: devices :computer:

#3792 Incrementing version number to `v0.30.0-dev`
  doc/development/release_notes.md
  doc/releases/changelog-dev.md
  pennylane/_version.py
Labels: do not merge :warning:

#3754 Support chemist fermionic operator notation in qchem
  doc/releases/changelog-dev.md
  pennylane/qchem/observable_hf.py
  tests/qchem/test_observable_hf.py
Labels: qchem :atom_symbol:

#3819 Device api doc typo fixes
  pennylane/devices/experimental/device_api.py
Labels: merge-ready :heavy_check_mark:

#3825 Update exp.py
  pennylane/ops/op_math/exp.py
Labels: merge-ready :heavy_check_mark:

#3814 Fix sign expand
  pennylane/transforms/sign_expand/sign_expand.py
Labels: merge-ready :heavy_check_mark:

#3828 Fix hadamard grad
  pennylane/gradients/hadamard_gradient.py
  tests/returntypes/gradients/test_hadamard_grad.py
Labels: merge-ready :heavy_check_mark:

#3829 Remove auto warning and swtich tracker
  pennylane/qnode.py
  tests/test_qnode.py
Labels: merge-ready :heavy_check_mark:

#3827 Update header images
  doc/_static/header-dark-mode.png
  doc/_static/header.png
Labels: merge-ready :heavy_check_mark:
