Repository PennyLaneAI/pennylane, pull requests merged in 2023-01, with the labels that each got.

#3363 Add function to load qchem basis sets
  .github/workflows/tests.yml
  doc/releases/changelog-dev.md
  pennylane/qchem/__init__.py
  pennylane/qchem/basis_data.py
  pennylane/qchem/basis_set.py
  pennylane/qchem/molecule.py
  pennylane/qchem/openfermion_obs.py
  tests/qchem/test_basis_set.py
  tests/qchem/test_molecule.py
Labels: qchem :atom_symbol:

#3282 Remove components ops from queue instead of updating metadata
  doc/releases/changelog-dev.md
  pennylane/measurements/classical_shadow.py
  pennylane/measurements/measurements.py
  pennylane/operation.py
  pennylane/ops/functions/map_wires.py
  pennylane/ops/functions/simplify.py
  pennylane/ops/op_math/adjoint.py
  pennylane/ops/op_math/composite.py
  pennylane/ops/op_math/pow.py
  pennylane/ops/op_math/prod.py
  pennylane/ops/op_math/sprod.py
  pennylane/ops/op_math/sum.py
  pennylane/ops/op_math/symbolicop.py
  pennylane/ops/qubit/hamiltonian.py
  pennylane/qchem/tapering.py
  pennylane/queuing.py
  pennylane/templates/subroutines/qpe.py
  tests/measurements/test_measurements.py
  tests/ops/functions/test_map_wires.py
  tests/ops/functions/test_simplify.py
  tests/ops/op_math/test_adjoint.py
  tests/ops/op_math/test_controlled.py
  tests/ops/op_math/test_pow_op.py
  tests/ops/op_math/test_prod.py
  tests/ops/op_math/test_sprod.py
  tests/ops/op_math/test_sum.py
  tests/ops/op_math/test_symbolic_op.py
  tests/ops/qubit/test_hamiltonian.py
  tests/qchem/test_tapering.py
  tests/tape/test_tape.py
  tests/test_operation.py
  tests/test_queuing.py
Labels: review-ready :ok_hand:

#3578 Reduce warnings in test suite for new return type system
  tests/returntypes/autograd/test_autograd_new.py
  tests/returntypes/autograd/test_autograd_qnode_new.py
  tests/returntypes/core/test_new_qscript.py
  tests/returntypes/core/test_new_return_types_qnode.py
  tests/returntypes/gradients/test_jvp.py
  tests/returntypes/gradients/test_vjp_new.py
  tests/returntypes/jax/test_jax_jit_qnode_new.py
  tests/returntypes/jax/test_jax_qnode_new.py
  tests/returntypes/paramshift/test_parameter_shift_new.py
  tests/returntypes/paramshift/test_parameter_shift_shot_vec_new.py
  tests/returntypes/transforms/test_metric_tensor_new.py
  tests/returntypes/transforms/test_qcut_new.py
  tests/transforms/test_metric_tensor.py
Labels: review-ready :ok_hand:, tests :test_tube:

#3579 Fix `metric_tensor` with non-standard operations
  doc/releases/changelog-dev.md
  pennylane/transforms/metric_tensor.py
  tests/returntypes/transforms/test_metric_tensor_new.py
  tests/transforms/test_metric_tensor.py
Labels: autodiff :chart_with_upwards_trend:, review-ready :ok_hand:

#3566 Remove qutrit ops use of in-place inversion
  doc/releases/changelog-dev.md
  pennylane/ops/qutrit/matrix_ops.py
  pennylane/ops/qutrit/non_parametric_ops.py
  tests/ops/qutrit/test_qutrit_matrix_ops.py
  tests/ops/qutrit/test_qutrit_non_parametric_ops.py
Labels: review-ready :ok_hand:

#3664 Organize the operation module documentation page
  doc/code/qml_operation.rst
  doc/releases/changelog-dev.md
  pennylane/operation.py
Labels: review-ready :ok_hand:
