Repository PennyLaneAI/pennylane, pull requests merged in 2024-11, with the labels that each got.

#6497 update neighbour_order error in Lattice
  pennylane/spin/lattice.py
  tests/spin/test_lattice.py
Labels: merge-ready :heavy_check_mark:

#6511 Run data-tests with Python 3.12 when running for CI suite
  .github/workflows/interface-unit-tests.yml
Labels: ci:run-full-test-suite

#6533 Change Torch wheel install variants for CI
  .github/stable/all_interfaces.txt
  .github/stable/torch.txt
  .github/workflows/docs.yml
  .github/workflows/interface-dependency-versions.yml
  .github/workflows/unit-test.yml
  doc/requirements.txt
  pennylane/workflow/__init__.py
Labels: ci:run-full-test-suite, urgent

#6349 Enabling `jax.vmap` for program capture
  doc/releases/changelog-dev.md
  pennylane/capture/capture_diff.py
  pennylane/capture/capture_operators.py
  pennylane/capture/capture_qnode.py
  pennylane/compiler/qjit_api.py
  pennylane/math/utils.py
  pennylane/operation.py
  pennylane/ops/op_math/adjoint.py
  pennylane/ops/op_math/condition.py
  pennylane/ops/op_math/controlled.py
  tests/capture/test_capture_qnode.py
Labels: merge-ready :heavy_check_mark:

#6486 Adding new feature wire_options to draw_mpl function
  doc/_static/draw_mpl/per_wire_options.png
  doc/_static/tape_mpl/per_wire_options.png
  doc/code/qml_drawer.rst
  doc/releases/changelog-dev.md
  pennylane/drawer/draw.py
  pennylane/drawer/mpldrawer.py
  pennylane/drawer/tape_mpl.py
  tests/drawer/test_draw_mpl.py
Labels: merge-ready :heavy_check_mark:

#6544 Remove redundant measurement in `qml.AmplitudeEmbedding` docstring examples
  pennylane/templates/embeddings/amplitude.py
Labels: merge-ready :heavy_check_mark:

#6503 init_state part0: dumb StatePrep
  doc/releases/changelog-dev.md
  pennylane/devices/qubit_mixed/__init__.py
  pennylane/devices/qubit_mixed/initialize_state.py
  tests/devices/qubit_mixed/test_qubit_mixed_initialize_state.py
Labels: merge-ready :heavy_check_mark:, urgent

#6506 Fix `Identity.__repr__` bug
  doc/releases/changelog-dev.md
  pennylane/ops/identity.py
  tests/ops/test_identity.py
Labels: merge-ready :heavy_check_mark:, urgent

#6545 fix docs rendering wrongly in changelog
  doc/releases/changelog-dev.md
Labels: merge-ready :heavy_check_mark:

#6521 [Capture] higher order primitives store slices instead of integers
  doc/releases/changelog-dev.md
  pennylane/capture/flatfn.py
  pennylane/compiler/qjit_api.py
  pennylane/ops/op_math/condition.py
Labels: merge-ready :heavy_check_mark:, urgent

#6530 Remove `shadow_expval` transform from `qml.shadows`
  doc/development/deprecations.rst
  doc/releases/changelog-dev.md
  pennylane/shadows/__init__.py
  pennylane/shadows/transforms.py
  tests/shadow/test_shadow_transforms.py
Labels: merge-ready :heavy_check_mark:, urgent

#6411 Update README positioning for researchers
  README.md
  doc/_static/readme/demos.png
  doc/_static/readme/getting-started.png
  doc/_static/readme/pl-logo.png
  doc/_static/readme/research.png
Labels: merge-ready :heavy_check_mark:, urgent

#6480 Add performance warning for `default.tensor`
  pennylane/devices/default_tensor.py
Labels: merge-ready :heavy_check_mark:

#6442 Resource constructor class
  pennylane/labs/__init__.py
  pennylane/labs/resource_estimation/__init__.py
  pennylane/labs/resource_estimation/resource_container.py
  pennylane/labs/resource_estimation/resource_operator.py
  pennylane/labs/tests/resource_estimation/test_resource_constructor.py
Labels: review-ready :ok_hand:

#6542 Adding string representation for some operators
  doc/development/adding_operators.rst
  doc/introduction/inspecting_circuits.rst
  doc/introduction/operations.rst
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/controlled.py
  pennylane/ops/op_math/controlled_ops.py
  pennylane/ops/op_math/linear_combination.py
  pennylane/ops/op_math/pow.py
  pennylane/ops/qubit/hamiltonian.py
  pennylane/ops/qubit/non_parametric_ops.py
  pennylane/ops/qubit/parametric_ops_multi_qubit.py
  pennylane/ops/qubit/parametric_ops_single_qubit.py
  pennylane/ops/qubit/qchem_ops.py
  pennylane/queuing.py
  pennylane/tape/qscript.py
  pennylane/tape/tape.py
  pennylane/templates/embeddings/iqp.py
  pennylane/templates/subroutines/aqft.py
  pennylane/transforms/convert_to_numpy_parameters.py
  pennylane/transforms/zx/converter.py
  tests/ops/op_math/test_adjoint.py
  tests/ops/op_math/test_controlled.py
  tests/ops/op_math/test_evolution.py
  tests/ops/op_math/test_exp.py
  tests/ops/op_math/test_pow_op.py
  tests/ops/qubit/test_non_parametric_ops.py
Labels: merge-ready :heavy_check_mark:

#6531 Remove `expand_depth` in `compile` transform and `max_expansion` in `clifford_t_decomposition` transform
  doc/development/deprecations.rst
  doc/releases/changelog-dev.md
  pennylane/transforms/compile.py
  pennylane/transforms/decompositions/clifford_t_transform.py
  tests/transforms/core/test_transform_dispatcher.py
  tests/transforms/core/test_transform_program.py
  tests/transforms/test_cliffordt_transform.py
  tests/transforms/test_compile.py
Labels: do not merge :warning:

#6217 Enable warnings as errors for weekly run in test suite
  .github/workflows/interface-unit-tests.yml
  .github/workflows/package_warnings_as_errors.yml
  doc/releases/changelog-dev.md
  pennylane/devices/tests/pytest.ini
  requirements-ci.txt
Labels: urgent

#6558 Combined Removals for PL-v0.40 (Yushao)
  doc/development/deprecations.rst
  doc/introduction/templates.rst
  doc/releases/changelog-dev.md
  pennylane/devices/legacy_facade.py
  pennylane/devices/tests/test_templates.py
  pennylane/ops/functions/is_commuting.py
  pennylane/ops/functions/iterative_qpe.py
  pennylane/templates/state_preparations/__init__.py
  pennylane/templates/state_preparations/basis.py
  pennylane/templates/state_preparations/basis_qutrit.py
  pennylane/workflow/__init__.py
  pennylane/workflow/qnode.py
  pennylane/workflow/set_shots.py
  tests/capture/test_templates.py
  tests/interfaces/legacy_devices_integration/test_set_shots_legacy.py
  tests/interfaces/test_autograd_qnode.py
  tests/interfaces/test_jax_jit_qnode.py
  tests/interfaces/test_jax_qnode.py
  tests/interfaces/test_set_shots.py
  tests/interfaces/test_tensorflow_qnode.py
  tests/interfaces/test_torch_qnode.py
  tests/ops/functions/test_iterative_qpe.py
  tests/templates/test_state_preparations/test_basis_state_prep.py
  tests/test_qnode.py
  tests/transforms/test_batch_input.py
  tests/transforms/test_batch_params.py
  tests/transforms/test_defer_measurements.py
Labels: do not merge :warning:

#6525 Remove `QubitStateVector` class
  .github/workflows/interface-unit-tests.yml
  doc/development/deprecations.rst
  doc/releases/changelog-dev.md
  pennylane/data/attributes/operator/operator.py
  pennylane/devices/_qubit_device.py
  pennylane/devices/default_mixed.py
  pennylane/devices/tests/test_gates.py
  pennylane/ops/functions/is_commuting.py
  pennylane/ops/qubit/__init__.py
  pennylane/ops/qubit/attributes.py
  pennylane/ops/qubit/state_preparation.py
  tests/default_qubit_legacy.py
  tests/ops/functions/conftest.py
  tests/ops/qubit/test_attributes.py
  tests/ops/qubit/test_state_prep.py
Labels: do not merge :warning:

#6447 Resource classes for QFT
  doc/releases/changelog-dev.md
  pennylane/labs/resource_estimation/__init__.py
  pennylane/labs/resource_estimation/ops/__init__.py
  pennylane/labs/resource_estimation/ops/op_math/__init__.py
  pennylane/labs/resource_estimation/ops/op_math/controlled_ops.py
  pennylane/labs/resource_estimation/ops/qubit/__init__.py
  pennylane/labs/resource_estimation/ops/qubit/non_parametric_ops.py
  pennylane/labs/resource_estimation/ops/qubit/parametric_ops_single_qubit.py
  pennylane/labs/resource_estimation/resource_operator.py
  pennylane/labs/resource_estimation/templates/__init__.py
  pennylane/labs/resource_estimation/templates/subroutines.py
  pennylane/labs/tests/resource_estimation/ops/op_math/test_controlled_ops.py
  pennylane/labs/tests/resource_estimation/ops/qubit/test_non_parametric_ops.py
  pennylane/labs/tests/resource_estimation/ops/qubit/test_parametric_ops_single_qubit.py
  pennylane/labs/tests/resource_estimation/templates/test_resource_qft.py
  pennylane/labs/tests/resource_estimation/test_resource_operator.py
Labels: review-ready :ok_hand:

#6612 Pinning quimb in CI
  .github/workflows/interface-unit-tests.yml
Labels: urgent

#6478 Single qubit resource operators
  pennylane/labs/resource_estimation/__init__.py
  pennylane/labs/resource_estimation/ops/__init__.py
  pennylane/labs/resource_estimation/ops/identity.py
  pennylane/labs/resource_estimation/ops/qubit/__init__.py
  pennylane/labs/resource_estimation/ops/qubit/non_parametric_ops.py
  pennylane/labs/resource_estimation/ops/qubit/parametric_ops_single_qubit.py
  pennylane/labs/resource_estimation/resource_operator.py
  pennylane/labs/resource_estimation/templates/subroutines.py
  pennylane/labs/tests/resource_estimation/ops/qubit/test_non_parametric_ops.py
  pennylane/labs/tests/resource_estimation/ops/qubit/test_parametric_ops_single_qubit.py
  pennylane/labs/tests/resource_estimation/ops/test_identity.py
Labels: review-ready :ok_hand:

#6433 [New Device Capabilities] Add `capabilities` to the device API
  doc/development/plugins.rst
  doc/releases/changelog-dev.md
  pennylane/devices/__init__.py
  pennylane/devices/capabilities.py
  pennylane/devices/device_api.py
  pennylane/devices/legacy_facade.py
  pennylane/devices/preprocess.py
  pennylane/devices/tests/conftest.py
  pennylane/devices/tests/test_compare_default_qubit.py
  pennylane/devices/tests/test_measurements.py
  pennylane/devices/tests/test_properties.py
  pennylane/devices/tests/test_tracker.py
  pennylane/devices/toml_check.py
  pennylane/labs/tests/conftest.py
  pennylane/qcut/cutcircuit_mc.py
  pennylane/transforms/__init__.py
  pennylane/transforms/dynamic_one_shot.py
  tests/devices/conftest.py
  tests/devices/test_capabilities.py
  tests/devices/test_default_gaussian.py
  tests/devices/test_default_mixed_autograd.py
  tests/devices/test_default_mixed_jax.py
  tests/devices/test_default_mixed_tf.py
  tests/devices/test_default_mixed_torch.py
  tests/devices/test_default_qutrit.py
  tests/devices/test_device_api.py
  tests/devices/test_execution_config.py
  tests/measurements/test_expval.py
  tests/measurements/test_state.py
  tests/test_qnode.py
  tests/transforms/test_dynamic_one_shot.py
  tests/transforms/test_qcut.py
Labels: do not merge :warning:

#6518 Support the construction of bosonic operators
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/bose/__init__.py
  pennylane/bose/bosonic.py
  tests/bose/test_bosonic.py
Labels: merge-ready :heavy_check_mark:

#6622 Fix `qnode_spectrum` with `interface="auto"`
  doc/releases/changelog-dev.md
  pennylane/fourier/circuit_spectrum.py
  pennylane/fourier/qnode_spectrum.py
  pennylane/math/is_independent.py
  tests/fourier/test_qnode_spectrum.py
  tests/math/test_is_independent.py
Labels: merge-ready :heavy_check_mark:

#6500 Adding `get_resources` for resource tracking
  doc/releases/changelog-dev.md
  pennylane/labs/resource_estimation/__init__.py
  pennylane/labs/resource_estimation/resource_tracking.py
  pennylane/labs/tests/resource_estimation/test_resource_tracking.py
Labels: review-ready :ok_hand:
