Repository PennyLaneAI/pennylane, pull requests merged in 2024-10, with the labels that each got.

#6354 `sample_probs` is extracted out of `sample_state`
  doc/releases/changelog-dev.md
  pennylane/devices/qubit/__init__.py
  pennylane/devices/qubit/sampling.py
  pennylane/devices/qutrit_mixed/__init__.py
  pennylane/devices/qutrit_mixed/sampling.py
  tests/devices/qubit/test_sampling.py
  tests/devices/qutrit_mixed/test_qutrit_mixed_sampling.py
Labels: enhancement :sparkles:

#6317 Attempt to tidy up CI workflows by reducing number of inputs and conditional branches
  .github/durations/core_tests_durations.json
  .github/durations/jax_tests_durations.json
  .github/durations/tf_tests_durations.json
  .github/workflows/benchmarks.yml
  .github/workflows/check_in_artifact.yml
  .github/workflows/docker.yml
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/install_deps/action.yml
  .github/workflows/interface-unit-tests.yml
  .github/workflows/numpy_1_tests.yml
  .github/workflows/numpy_1_unit-tests.yml
  .github/workflows/test_numpy_1_compat.yml
  .github/workflows/tests.yml
  .github/workflows/unit-test.yml
Labels: urgent

#6273 Added ability to run linux workflows on large runners
  .github/workflows/determine-workflow-runner.yml
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/interface-unit-tests.yml
  .github/workflows/unit-test.yml
  .github/workflows/upload.yml
Labels: urgent

#6437 Warnings for `two_qubit_unitary`
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/decompositions/two_qubit_unitary.py
  tests/ops/op_math/test_decompositions.py
Labels: bug :bug:
