Repository PennyLaneAI/pennylane, pull requests merged in 2024-08, with the labels that each got.

#6033 Fix derivatives of `merge_rotations` and `single_qubit_fusion`
  doc/releases/changelog-dev.md
  pennylane/transforms/optimization/merge_rotations.py
  pennylane/transforms/optimization/single_qubit_fusion.py
  tests/transforms/test_optimization/test_merge_rotations.py
Labels: merge-ready :heavy_check_mark:

#6155 [BUGFIX] Pytrees: Handle empty shot vector
  doc/releases/changelog-dev.md
  pennylane/pytrees/serialization.py
  tests/data/attributes/test_pytree.py
  tests/pytrees/test_serialization.py
Labels: bug :bug:

#6159 [BUGFIX] Loading basis set data for larger elements
  doc/releases/changelog-0.38.0.md
  pennylane/qchem/basis_data.py
  tests/qchem/test_basis_set.py
Labels: bug :bug:

#6146 QA for PL 0.38
  pennylane/gradients/fisher.py
  pennylane/pytrees/pytrees.py
  pennylane/registers.py
  pennylane/spin/lattice.py
  pennylane/spin/spin_hamiltonian.py
  tests/pytrees/test_pytrees.py
Labels: merge-ready :heavy_check_mark:

#6176 Fix broken example in mitigate_with_zne docstring
  pennylane/transforms/mitigate.py
Labels: merge-ready :heavy_check_mark:

#6149 Patch dynamic_one_shot for single shot case
  doc/releases/changelog-0.38.0.md
  pennylane/transforms/dynamic_one_shot.py
  tests/transforms/test_dynamic_one_shot.py
Labels: merge-ready :heavy_check_mark:

#6187 Cherry pick datasets bugfix into RC branch
  doc/releases/changelog-0.38.0.md
  pennylane/pytrees/serialization.py
  tests/data/attributes/test_pytree.py
  tests/pytrees/test_serialization.py
Labels: merge-ready :heavy_check_mark:

#6154 Documentation Fix for Spin hamiltonians module
  doc/code/qml_spin.rst
  doc/index.rst
  pennylane/spin/lattice.py
  pennylane/spin/spin_hamiltonian.py
Labels: merge-ready :heavy_check_mark:

#6195 fix assert valid pickling test
  tests/ops/functions/test_assert_valid.py
Labels: ci:run-full-test-suite

#6179 Documentation for Quantum Arithmetic
  doc/_static/templates/arithmetic/adder.png
  doc/_static/templates/arithmetic/integercomparator.png
  doc/_static/templates/arithmetic/modexp.png
  doc/_static/templates/arithmetic/multiplier.png
  doc/_static/templates/arithmetic/outadder.png
  doc/_static/templates/arithmetic/outmultiplier.png
  doc/_static/templates/arithmetic/phaseadder.png
  doc/introduction/templates.rst
  pennylane/templates/subroutines/adder.py
  pennylane/templates/subroutines/mod_exp.py
  pennylane/templates/subroutines/multiplier.py
  pennylane/templates/subroutines/out_adder.py
  pennylane/templates/subroutines/out_multiplier.py
  pennylane/templates/subroutines/phase_adder.py
Labels: merge-ready :heavy_check_mark:

#6194 Update validation checks on quantum arithmetic templates
  pennylane/templates/subroutines/adder.py
  pennylane/templates/subroutines/mod_exp.py
  pennylane/templates/subroutines/multiplier.py
  pennylane/templates/subroutines/out_adder.py
  pennylane/templates/subroutines/out_multiplier.py
  pennylane/templates/subroutines/phase_adder.py
  tests/capture/test_templates.py
  tests/templates/test_subroutines/test_adder.py
  tests/templates/test_subroutines/test_mod_exp.py
  tests/templates/test_subroutines/test_multiplier.py
  tests/templates/test_subroutines/test_out_adder.py
  tests/templates/test_subroutines/test_out_multiplier.py
  tests/templates/test_subroutines/test_phase_adder.py
Labels: merge-ready :heavy_check_mark:

#6143 v0.38 changelog
  doc/releases/changelog-0.38.0.md
Labels: merge-ready :heavy_check_mark:
