Repository PennyLaneAI/pennylane, pull requests merged in 2024-06, with the labels that each got.

#5748 Test supported gradient kwargs and raise error for `shots` kwarg
  doc/releases/changelog-dev.md
  pennylane/gradients/gradient_transform.py
  pennylane/workflow/qnode.py
  tests/gradients/core/test_gradient_transform.py
  tests/test_debugging.py
  tests/test_qnode.py
Labels: merge-ready :heavy_check_mark:

#5798 Update `ExecutionConfig`'s `mcm_config` default value
  pennylane/devices/execution_config.py
Labels: ci:run-full-test-suite

#5600 Implement `qml.breakpoint()` and initial integration with `Pdb`
  pennylane/__init__.py
  pennylane/debugging.py
  pennylane/workflow/qnode.py
  tests/test_debugging.py
Labels: review-ready :ok_hand:

#5804 adjusting documentation typesetting
  doc/releases/changelog-dev.md
  pennylane/ops/identity.py
  pennylane/ops/qubit/non_parametric_ops.py
  pennylane/ops/qubit/parametric_ops_multi_qubit.py
Labels: merge-ready :heavy_check_mark:

#5749 Support dynamic measurements with debugger
  pennylane/debugging.py
  tests/test_debugging.py
Labels: review-ready :ok_hand:

#5835 Disallow taking the adjoint of fractional power operations
  doc/releases/changelog-dev.md
  pennylane/ops/identity.py
  pennylane/ops/op_math/pow.py
  tests/ops/op_math/test_pow_op.py
Labels: merge-ready :heavy_check_mark:

#5774 Fix the derivative of `MottonenStatePreparation` where possible
  doc/releases/changelog-dev.md
  pennylane/templates/state_preparations/mottonen.py
  tests/templates/test_state_preparations/test_mottonen_state_prep.py
  tests/templates/test_subroutines/test_qubitization.py
Labels: merge-ready :heavy_check_mark:

#5856 Fix wire handling on special control wires
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/controlled_ops.py
  tests/ops/op_math/test_controlled_ops.py
Labels: merge-ready :heavy_check_mark:

#5857 transform callables wrap original qfunc
  doc/releases/changelog-dev.md
  pennylane/transforms/core/transform_dispatcher.py
  tests/transforms/core/test_transform_dispatcher.py
Labels: merge-ready :heavy_check_mark:

#5763 Fix a few docs examples in `qnn`, `fermi` and `math`
  doc/code/qml_fermi.rst
  pennylane/fermi/conversion.py
  pennylane/kernels/cost_functions.py
  pennylane/kernels/utils.py
  pennylane/math/multi_dispatch.py
  pennylane/math/quantum.py
  pennylane/math/utils.py
  pennylane/qnn/torch.py
Labels: review-ready :ok_hand:

#4484 Compute expectation value
  doc/releases/changelog-dev.md
  pennylane/math/__init__.py
  pennylane/math/quantum.py
  tests/math/test_expectation_value.py
Labels: WIP :construction:

#5860 Fix `hadamard_grad` with wires-broadcasted measurements
  doc/releases/changelog-dev.md
  pennylane/gradients/hadamard_gradient.py
  tests/gradients/core/test_hadamard_gradient.py
Labels: review-ready :ok_hand:

#5789 Adding documentation for `qml.breakpoint()` and `qml.PLDB`
  doc/code/qml_debugging.rst
  doc/index.rst
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/debugging/__init__.py
  pennylane/debugging/debugger.py
  tests/test_debugging.py
Labels: review-ready :ok_hand:

#5889 Minor program capture fixes
  doc/releases/changelog-dev.md
  pennylane/capture/__init__.py
  pennylane/capture/capture_qnode.py
  pennylane/measurements/sample.py
  tests/capture/test_capture_qnode.py
  tests/capture/test_measurements_capture.py
  tests/capture/test_operators.py
  tests/capture/test_templates.py
Labels: merge-ready :heavy_check_mark:
