Repository PennyLaneAI/pennylane, pull requests merged in 2024-02, with the labels that each got.

#5073 Fix TrotterProduct fail for a Hamiltonian with identical coefficients
  doc/releases/changelog-dev.md
  pennylane/templates/subroutines/trotter.py
  tests/templates/test_subroutines/test_trotter.py
Labels: bug :bug:

#5166 Add global phase to `MottonenStatePreparation`
  doc/releases/changelog-dev.md
  pennylane/templates/state_preparations/mottonen.py
  tests/templates/test_state_preparations/test_mottonen_state_prep.py
Labels: bug :bug:

#5140 Change naming convention for compilers' entry points.
  doc/releases/changelog-dev.md
  pennylane/compiler/__init__.py
  pennylane/compiler/compiler.py
Labels: compiler :factory:

#5115 Add abstract `AlgorithmicError` class
  doc/releases/changelog-dev.md
  pennylane/resource/__init__.py
  pennylane/resource/error.py
  tests/resource/test_error.py
Labels: review-ready :ok_hand:

#5248 Override `__copy__` method for QSVT instances
  doc/releases/changelog-dev.md
  pennylane/templates/subroutines/qsvt.py
  tests/templates/test_subroutines/test_qsvt.py
Labels: bug :bug:

#5243 Turn caching off by default when `max_diff==1`
  doc/releases/changelog-dev.md
  pennylane/workflow/qnode.py
  tests/test_qnode.py
Labels: merge-ready :heavy_check_mark:

#5251 Add function to load Qiskit operators
  doc/releases/changelog-dev.md
  pennylane/io.py
  tests/test_io.py
Labels: merge-ready :heavy_check_mark:

#5247 Split `qml.ctrl` into the API entry-point and the default implementation
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/controlled.py
Labels: merge-ready :heavy_check_mark:

#5246 Remove dtype promotion in pauli rep of scalar products with tensorflow
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/sprod.py
  tests/ops/op_math/test_prod.py
  tests/ops/op_math/test_sprod.py
Labels: bug :bug:, merge-ready :heavy_check_mark:

#5277 Apply all user transforms before drawing
  doc/releases/changelog-0.35.0.md
  pennylane/drawer/draw.py
  tests/drawer/test_draw.py
  tests/drawer/test_draw_mpl.py
  tests/drawer/test_tape_mpl.py
Labels: bug :bug:
