Repository PennyLaneAI/pennylane, pull requests merged in 2024-04, with the labels that each got.

#5446 Fix tensorflow for when device returns float 32 results
  doc/releases/changelog-dev.md
  pennylane/workflow/interfaces/tensorflow.py
  tests/interfaces/default_qubit_2_integration/test_tensorflow_default_qubit_2.py
Labels: merge-ready :heavy_check_mark:

#5286 add vmap support for devices that do not support parameter broadcasting
  pennylane/tape/qscript.py
  pennylane/workflow/interfaces/jax_jit.py
  tests/interfaces/default_qubit_2_integration/test_jax_jit_qnode_default_qubit_2.py
  tests/interfaces/default_qubit_2_integration/test_jax_qnode_default_qubit_2.py
  tests/interfaces/test_jax_jit.py
Labels: merge-ready :heavy_check_mark:

#5390 Add Bravyi-Kitaev mapping
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/fermi/__init__.py
  pennylane/fermi/conversion.py
  tests/fermi/test_bravyi_kitaev.py
Labels: qchem :atom_symbol:

#5473 `dynamic_one_shot` supports broadcasting; `broadcast_expand` supports shot vectors
  .github/workflows/core_tests_durations.json
  doc/releases/changelog-dev.md
  pennylane/devices/preprocess.py
  pennylane/ops/functions/bind_new_parameters.py
  pennylane/ops/op_math/condition.py
  pennylane/transforms/broadcast_expand.py
  pennylane/transforms/defer_measurements.py
  pennylane/transforms/dynamic_one_shot.py
  tests/devices/default_qubit/test_default_qubit_native_mcm.py
  tests/ops/functions/test_bind_new_parameters.py
  tests/ops/op_math/test_condition.py
  tests/transforms/test_broadcast_expand.py
  tests/transforms/test_defer_measurements.py
Labels: do not merge :warning:

#5472 Upgrade HF state for different mappings
  doc/releases/changelog-dev.md
  pennylane/qchem/structure.py
  tests/qchem/test_structure.py
Labels: qchem :atom_symbol:

#5570 Improved handling for Identities on no wires
  doc/releases/changelog-dev.md
  pennylane/devices/tests/test_measurements.py
  pennylane/measurements/expval.py
  pennylane/measurements/measurements.py
  pennylane/pauli/grouping/group_observables.py
  pennylane/utils.py
  tests/devices/qubit/test_measure.py
  tests/devices/qubit/test_sampling.py
  tests/ops/op_math/test_prod.py
  tests/ops/op_math/test_sum.py
  tests/pauli/grouping/test_pauli_group_observables.py
Labels: merge-ready :heavy_check_mark:

#5576 Draw sorts wires
  doc/releases/changelog-dev.md
  pennylane/drawer/draw.py
  tests/drawer/test_draw.py
  tests/drawer/test_draw_mpl.py
Labels: merge-ready :heavy_check_mark:

#5530 Improving support for `jax-jit` interface with `default.mixed`
  doc/releases/changelog-dev.md
  pennylane/_qubit_device.py
  tests/devices/test_default_mixed_jax.py
Labels: merge-ready :heavy_check_mark:

#5552 Improve support for `snapshot` on `default.mixed`
  doc/releases/changelog-dev.md
  pennylane/devices/default_mixed.py
  tests/devices/test_default_mixed.py
Labels: merge-ready :heavy_check_mark:

#5500 `qml.Qubitization` template
  doc/_static/templates/qubitization/thumbnail_qubitization.png
  doc/introduction/templates.rst
  doc/releases/changelog-dev.md
  pennylane/templates/subroutines/__init__.py
  pennylane/templates/subroutines/qubitization.py
  tests/templates/test_subroutines/test_amplitude_amplification.py
  tests/templates/test_subroutines/test_qubitization.py
Labels: merge-ready :heavy_check_mark:

#5569 [new opmath] UserWarning when opmath is manually disabled/re-enabled
  pennylane/devices/tests/conftest.py
  pennylane/operation.py
  pennylane/ops/op_math/linear_combination.py
  pennylane/ops/op_math/prod.py
  pennylane/ops/op_math/sum.py
  pennylane/ops/qubit/hamiltonian.py
  pennylane/pauli/grouping/group_observables.py
  pennylane/qchem/convert.py
  pennylane/qchem/observable_hf.py
  tests/conftest.py
  tests/test_operation.py
Labels: merge-ready :heavy_check_mark:

#5495 Default qutrit mixed execute
  doc/releases/changelog-dev.md
  pennylane/devices/default_qutrit_mixed.py
  pennylane/devices/qutrit_mixed/apply_operation.py
  pennylane/devices/qutrit_mixed/measure.py
  setup.py
  tests/devices/qutrit_mixed/test_qutrit_mixed_preprocessing.py
  tests/devices/qutrit_mixed/test_qutrit_mixed_tracking.py
  tests/devices/test_default_qutrit_mixed.py
Labels: merge-ready :heavy_check_mark:

#5582 Null qubit supports any operation without a decomposition
  doc/releases/changelog-dev.md
  pennylane/devices/null_qubit.py
  tests/devices/test_null_qubit.py
Labels: merge-ready :heavy_check_mark:

#5578 Improve performance of differentiable matrix calculations for Pauli Sentences
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/prod.py
  pennylane/ops/op_math/sum.py
  pennylane/pauli/pauli_arithmetic.py
  tests/devices/qubit/test_apply_operation.py
  tests/pauli/test_pauli_arithmetic.py
Labels: merge-ready :heavy_check_mark:

#5579 Pin numpy in setup.py to pre 2.0
  setup.py
Labels: merge-ready :heavy_check_mark:

#5580 Update device test for `Sum` to explicitly use `sum`
  pennylane/devices/tests/test_measurements.py
Labels: merge-ready :heavy_check_mark:

#5563 Add a Release News section to the table of contents
  doc/index.rst
  doc/introduction/returns.rst
  doc/news/new_opmath.rst
  doc/releases/changelog-dev.md
  pennylane/devices/tests/conftest.py
  pennylane/operation.py
  pennylane/ops/op_math/linear_combination.py
  pennylane/ops/op_math/prod.py
  pennylane/ops/op_math/sum.py
  pennylane/ops/qubit/hamiltonian.py
  pennylane/pauli/grouping/group_observables.py
  pennylane/qchem/convert.py
  pennylane/qchem/observable_hf.py
  tests/conftest.py
  tests/test_operation.py
Labels: merge-ready :heavy_check_mark:

#5596 Fix `qml.gradients` docs examples
  pennylane/gradients/__init__.py
  pennylane/gradients/classical_jacobian.py
  pennylane/gradients/finite_difference.py
  pennylane/gradients/general_shift_rules.py
  pennylane/gradients/hadamard_gradient.py
  pennylane/gradients/jvp.py
  pennylane/gradients/parameter_shift.py
  pennylane/gradients/parameter_shift_cv.py
  pennylane/gradients/parameter_shift_hessian.py
  pennylane/gradients/pulse_gradient.py
  pennylane/gradients/pulse_gradient_odegen.py
  pennylane/gradients/spsa_gradient.py
  pennylane/gradients/vjp.py
  pennylane/kernels/cost_functions.py
  pennylane/kernels/postprocessing.py
  pennylane/kernels/utils.py
Labels: merge-ready :heavy_check_mark:
