Repository PennyLaneAI/pennylane, pull requests merged in 2024-03, with the labels that each got.

#5295 Address spelling/formatting errors in docs
  doc/development/guide/architecture.rst
  pennylane/math/fidelity.py
  pennylane/math/quantum.py
  pennylane/math/utils.py
  pennylane/measurements/probs.py
  pennylane/ops/op_math/controlled.py
  pennylane/ops/qubit/special_unitary.py
  pennylane/qcut/cutcircuit_mc.py
  pennylane/transforms/batch_partial.py
  pennylane/transforms/optimization/pattern_matching.py
  pennylane/workflow/execution.py
  pennylane/workflow/interfaces/jax.py
  pennylane/workflow/interfaces/tensorflow.py
Labels: merge-ready :heavy_check_mark:

#5290 Compiler documentation updates
  doc/introduction/compiling_workflows.rst
  pennylane/compiler/__init__.py
  pennylane/compiler/qjit_api.py
Labels: merge-ready :heavy_check_mark:

#5296 Revert #5287
  doc/development/deprecations.rst
  doc/releases/changelog-0.35.0.md
  pennylane/ops/op_math/sprod.py
  tests/ops/op_math/test_sprod.py
Labels: merge-ready :heavy_check_mark:

#5281 Add quick start page for importing workflows
  doc/index.rst
  doc/introduction/circuits.rst
  doc/introduction/importing_workflows.rst
  doc/releases/changelog-0.35.0.md
  pennylane/io.py
Labels: merge-ready :heavy_check_mark:

#5118 Add direct call to pyscf in qchem
  doc/releases/changelog-dev.md
  pennylane/qchem/openfermion_obs.py
  tests/qchem/of_tests/test_molecular_hamiltonian.py
  tests/qchem/of_tests/test_observable_of.py
Labels: qchem :atom_symbol:

#5315 update-deprecated-pennylane-website-urls
  doc/introduction/chemistry.rst
Labels: do not merge :warning:

#5320 Update minimum catalyst version
  pennylane/compiler/compiler.py
  tests/test_compiler.py
Labels: compiler :factory:

#5375 Update tests in top-level of tests folder for new op-math
  tests/test_device.py
  tests/test_qubit_device.py
  tests/test_queuing.py
  tests/test_vqe.py
Labels: do not merge :warning:

#5384 Add support for error tracking with `TrotterProduct` template
  doc/releases/changelog-dev.md
  pennylane/resource/error/__init__.py
  pennylane/resource/error/error.py
  pennylane/resource/error/trotter_error.py
  pennylane/templates/subroutines/trotter.py
  tests/resource/test_error/test_error.py
  tests/resource/test_error/test_trotter_error.py
  tests/templates/test_subroutines/test_trotter.py
Labels: review-ready :ok_hand:

#5419 [new opmath] Simplify `LinearCombination(coeffs, ops, simplify=True)`
  pennylane/ops/op_math/linear_combination.py
  pennylane/ops/qubit/hamiltonian.py
  tests/ops/op_math/test_linear_combination.py
Labels: merge-ready :heavy_check_mark:

#5429 Remove usage of `qml.Hamiltonian` from `hamiltonian.py`
  pennylane/ops/qubit/hamiltonian.py
Labels: merge-ready :heavy_check_mark:

#5426 Replace qml.Hamiltonian from isinstance checks for qml.ops.Hamiltonian
  pennylane/_device.py
  pennylane/data/attributes/operator/operator.py
  pennylane/devices/qubit/measure.py
  pennylane/devices/qubit/sampling.py
  pennylane/devices/qutrit_mixed/measure.py
  pennylane/ops/op_math/exp.py
  pennylane/ops/op_math/sprod.py
  pennylane/optimize/riemannian_gradient.py
  pennylane/optimize/shot_adaptive.py
  pennylane/pauli/utils.py
  pennylane/pulse/hardware_hamiltonian.py
  pennylane/pulse/parametrized_evolution.py
  pennylane/pulse/parametrized_hamiltonian.py
  pennylane/qaoa/layers.py
  pennylane/qchem/tapering.py
  pennylane/qcut/cutcircuit.py
  pennylane/shadows/classical_shadow.py
  pennylane/templates/subroutines/qdrift.py
  pennylane/templates/subroutines/trotter.py
  tests/ops/op_math/test_exp.py
  tests/pauli/test_pauli_utils.py
  tests/shadow/test_shadow_class.py
Labels: merge-ready :heavy_check_mark:

#5395 Implement process_counts in SampleMP
  doc/releases/changelog-dev.md
  pennylane/devices/tests/test_measurements.py
  pennylane/measurements/measurements.py
  pennylane/measurements/sample.py
  tests/measurements/legacy/test_measurements_legacy.py
  tests/measurements/test_measurements.py
  tests/measurements/test_sample.py
Labels: merge-ready :heavy_check_mark:

#5438 Fix Torch tensor locality with autoray-registered `coerce` method
  doc/releases/changelog-dev.md
  pennylane/math/multi_dispatch.py
  pennylane/math/single_dispatch.py
Labels: gpu
