Repository PennyLaneAI/pennylane, pull requests merged in 2024-07, with the labels that each got.

#5935 Update docstring of various functions
  doc/releases/changelog-0.37.0.md
  pennylane/capture/capture_meta.py
  pennylane/capture/capture_qnode.py
  pennylane/devices/preprocess.py
  pennylane/transforms/convert_to_numpy_parameters.py
Labels: merge-ready :heavy_check_mark:

#5932 Quality check for PRs related to `PennyLane 0.37`
  doc/releases/changelog-0.37.0.md
  pennylane/capture/explanations.md
  pennylane/io.py
  pennylane/ops/qutrit/channel.py
  pennylane/transforms/split_non_commuting.py
Labels: merge-ready :heavy_check_mark:

#5947 Minor doc/code fixes for 0.37 release
  doc/development/guide/installation.rst
  pennylane/debugging/snapshot.py
  pennylane/devices/__init__.py
  pennylane/devices/default_tensor.py
  pennylane/noise/noise_model.py
  pennylane/ops/meta.py
  pennylane/ops/qutrit/channel.py
  tests/devices/default_tensor/test_default_tensor.py
  tests/test_debugging.py
Labels: merge-ready :heavy_check_mark:

#5951 Fix `test_return_system`
  doc/releases/changelog-0.37.0.md
  pennylane/devices/tests/test_return_system.py
Labels: merge-ready :heavy_check_mark:

#5946 Documentation fixes
  doc/code/qml_pytrees.rst
  doc/index.rst
  doc/releases/changelog-0.37.0.md
  pennylane/pytrees/pytrees.py
  pennylane/templates/subroutines/qrom.py
Labels: merge-ready :heavy_check_mark:

#5945 Fixes `split_non_commuting` with non-trainable autograd coefficients
  doc/releases/changelog-0.37.0.md
  pennylane/transforms/split_non_commuting.py
  tests/transforms/test_split_non_commuting.py
Labels: merge-ready :heavy_check_mark:

#5928 [sc-59665] v0.37 changelog
  doc/releases/changelog-0.37.0.md
Labels: merge-ready :heavy_check_mark:

#5934 QA release fixes
  doc/code/qml_noise.rst
  pennylane/boolean_fn.py
  pennylane/devices/default_tensor.py
  pennylane/drawer/draw.py
  pennylane/gradients/parameter_shift.py
  pennylane/noise/conditionals.py
  pennylane/noise/noise_model.py
  pennylane/ops/op_math/pow.py
  pennylane/qaoa/layers.py
  pennylane/qchem/convert_openfermion.py
  pennylane/queuing.py
  pennylane/resource/specs.py
  pennylane/transforms/add_noise.py
  pennylane/transforms/dynamic_one_shot.py
  pennylane/workflow/construct_batch.py
Labels: merge-ready :heavy_check_mark:

#5952 Doc fixes
  doc/code/qml_noise.rst
  doc/code/qml_qchem.rst
  doc/introduction/dynamic_quantum_circuits.rst
  doc/introduction/operations.rst
  pennylane/noise/noise_model.py
  pennylane/ops/functions/equal.py
  pennylane/qchem/hamiltonian.py
  pennylane/qchem/observable_hf.py
  pennylane/transforms/add_noise.py
Labels: merge-ready :heavy_check_mark:

#5931 FF Fixes
  doc/code/qml_debugging.rst
  doc/code/qml_qchem.rst
  doc/introduction/data.rst
  doc/introduction/inspecting_circuits.rst
  pennylane/debugging/debugger.py
  pennylane/io.py
  pennylane/math/quantum.py
  pennylane/ops/op_math/controlled_decompositions.py
  pennylane/ops/op_math/decompositions/single_qubit_unitary.py
  pennylane/pauli/conversion.py
  pennylane/qchem/__init__.py
  pennylane/qchem/convert_openfermion.py
  pennylane/transforms/transpile.py
  pennylane/typing.py
  pennylane/workflow/qnode.py
  tests/ops/op_math/test_controlled_decompositions.py
  tests/test_debugging.py
Labels: merge-ready :heavy_check_mark:

#5960 Fix jax enable x64
  doc/releases/changelog-0.37.0.md
  pennylane/compiler/compiler.py
  tests/test_compiler.py
Labels: merge-ready :heavy_check_mark:

#5950 Update orbital order in qubit observable
  doc/releases/changelog-dev.md
  pennylane/qchem/observable_hf.py
  tests/qchem/test_hamiltonians.py
Labels: qchem :atom_symbol:

#5923 Support parameter broadcasting with `GlobalPhase`
  doc/releases/changelog-dev.md
  pennylane/ops/identity.py
  pennylane/ops/op_math/decompositions/single_qubit_unitary.py
  pennylane/ops/qubit/parametric_ops_multi_qubit.py
  tests/ops/qubit/test_parametric_ops.py
Labels: review-ready :ok_hand:
