Repository PennyLaneAI/pennylane, pull requests merged in 2025-04, with the labels that each got.

#7147 [BUG] Fix `qml.matrix` apply on sparse operators
  doc/releases/changelog-dev.md
  pennylane/ops/functions/matrix.py
  tests/ops/functions/test_matrix.py
  tests/ops/qubit/test_parametric_ops.py
  tests/resource/test_error/test_error.py
Labels: bug :bug:, review-ready :ok_hand:, do not merge :warning:

#7129 qml.liealg doc fixes
  doc/releases/changelog-dev.md
  pennylane/liealg/horizontal_cartan_subalgebra.py
  pennylane/liealg/involutions.py
Labels: documentation :blue_book:

#7140 Fix misc issues involving sparse related dispatches
  doc/releases/changelog-dev.md
  pennylane/math/multi_dispatch.py
  pennylane/math/utils.py
  tests/math/test_functions.py
Labels: merge-ready :heavy_check_mark:, review-ready :ok_hand:

#7179 Make `PSWAP` support parameter broadcasting
  doc/releases/changelog-dev.md
  pennylane/ops/qubit/parametric_ops_multi_qubit.py
  tests/ops/qubit/test_parametric_ops.py
Labels: merge-ready :heavy_check_mark:

#7163 Reuse lines for classical wires if possible
  doc/releases/changelog-dev.md
  pennylane/devices/preprocess.py
  pennylane/drawer/_add_obj.py
  pennylane/drawer/drawable_layers.py
  pennylane/drawer/tape_mpl.py
  pennylane/drawer/tape_text.py
  pennylane/drawer/utils.py
  tests/drawer/test_draw.py
  tests/drawer/test_drawable_layers.py
  tests/drawer/test_drawer_utils.py
  tests/drawer/test_tape_text.py
Labels: review-ready :ok_hand:

#7195 Mock shot vectors test cases with an analytic simulation
  tests/device_shots_to_analytic.py
  tests/gradients/parameter_shift/test_parameter_shift_shot_vec.py
Labels: merge-ready :heavy_check_mark:, urgent

#7203 Force usage of large runners on merge queue
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/tests-labs.yml
  .github/workflows/tests.yml
Labels: urgent

#7148 Qualtran-PL Interoperability v2
  .github/workflows/interface-unit-tests.yml
  doc/code/qml.rst
  doc/code/qml_io.rst
  doc/code/qml_spin.rst
  doc/index.rst
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/devices/default_qubit.py
  pennylane/io/__init__.py
  pennylane/io/io.py
  pennylane/io/qualtran_io.py
  tests/io/test_io.py
  tests/io/test_qualtran_io.py
  tests/ops/functions/conftest.py
Labels: merge-ready :heavy_check_mark:

#7216 0.42.0 setup
  doc/development/release_notes.md
  doc/releases/changelog-dev.md
  pennylane/_version.py
Labels: urgent

#7223 [Decomposition] fix error when resource params contain uncomparable dict keys
  doc/releases/changelog-0.41.0.md
  pennylane/decomposition/resources.py
  pennylane/labs/tests/resource_estimation/test_resource_container.py
  tests/decomposition/test_resources.py
Labels: labs :scientist:

#7228 Fix `PSWAP` eigvals axis ordering with broadcasting
  doc/releases/changelog-0.41.0.md
  pennylane/ops/qubit/parametric_ops_multi_qubit.py
  tests/ops/qubit/test_parametric_ops.py
Labels: review-ready :ok_hand:

#7257 Bump minimum Lightning and Catalyst versions
  .github/stable/external.txt
  pennylane/compiler/compiler.py
  setup.py
Labels: urgent

#7200 fix problematic `__init__.py` imports
  doc/releases/changelog-dev.md
  pennylane/math/__init__.py
  pennylane/ops/__init__.py
  pennylane/ops/qubit/__init__.py
  pennylane/ops/qutrit/__init__.py
  pennylane/qaoa/__init__.py
  pennylane/qaoa/cost.py
  pennylane/tape/qscript.py
  pennylane/templates/__init__.py
  pennylane/templates/layer.py
  tests/ops/functions/conftest.py
Labels: merge-ready :heavy_check_mark:, ci:run-full-test-suite

#7280 Fix single-batch issue of `StatePrep` in `default.mixed`
  doc/releases/changelog-dev.md
  pennylane/devices/qubit_mixed/initialize_state.py
  tests/devices/qubit_mixed/test_qubit_mixed_simulate.py
Labels: review-ready :ok_hand:

#7323 Deprecate `get_gradient_fn`
  doc/development/deprecations.rst
  doc/releases/changelog-dev.md
  pennylane/workflow/qnode.py
  tests/test_qnode.py
Labels: merge-ready :heavy_check_mark:, deprecation :wastebasket:, urgent

#7329 Convert finite shots to analytic wrapped mocker in `tests/transform/test_defer_measurement.py`
  doc/releases/changelog-dev.md
  tests/transforms/test_defer_measurements.py
Labels: tests :test_tube:

#7320 Remove keras layer
  doc/development/deprecations.rst
  doc/introduction/interfaces.rst
  doc/introduction/interfaces/tf.rst
  doc/releases/changelog-dev.md
  pennylane/qnn/__init__.py
  pennylane/qnn/keras.py
  pennylane/workflow/construct_batch.py
  tests/qnn/test_keras.py
Labels: review-ready :ok_hand:

#7285 Fix sparse `BlockEncode` bug
  doc/releases/changelog-dev.md
  pennylane/ops/qubit/matrix_ops.py
  tests/ops/qubit/test_matrix_ops.py
Labels: bug :bug:

#7326 Allow overwriting shots on snapshots
  doc/releases/changelog-dev.md
  pennylane/debugging/snapshot.py
  pennylane/devices/preprocess.py
  pennylane/devices/qubit/apply_operation.py
  pennylane/devices/qubit_mixed/apply_operation.py
  pennylane/devices/qutrit_mixed/apply_operation.py
  pennylane/ops/meta.py
  tests/devices/qubit/test_apply_operation.py
  tests/devices/qubit_mixed/test_qubit_mixed_apply_operation.py
  tests/ops/test_meta.py
  tests/test_debugging.py
Labels: merge-ready :heavy_check_mark:
