Repository PennyLaneAI/pennylane, pull requests merged in 2025-01, with the labels that each got.

#6787 [v0.40.0 QA] Qchem doc Improvements
  pennylane/devices/default_tensor.py
  pennylane/qchem/molecule.py
  pennylane/qchem/vibrational/taylor_ham.py
  pennylane/qchem/vibrational/vscf.py
Labels: review-ready :ok_hand:

#6823 Remove `get_best_method` and `best_method_str` from `QNode`
  doc/development/deprecations.rst
  doc/releases/changelog-dev.md
  pennylane/workflow/qnode.py
  tests/test_qnode.py
  tests/test_qnode_legacy.py
Labels: merge-ready :heavy_check_mark:

#6830 Remove `gradient_fn` argument from `qml.execute`
  doc/development/deprecations.rst
  doc/releases/changelog-dev.md
  pennylane/workflow/execution.py
  tests/workflow/interfaces/execute/test_execute.py
Labels: merge-ready :heavy_check_mark:

#6825 Remove `qtape`/`tape` property from `QNode`
  doc/development/deprecations.rst
  doc/releases/changelog-dev.md
  pennylane/workflow/qnode.py
  tests/devices/test_default_clifford.py
  tests/ops/functions/test_map_wires.py
  tests/test_qnode.py
  tests/test_qnode_legacy.py
Labels: merge-ready :heavy_check_mark:

#6803 Add `QNode.update` method
  doc/introduction/circuits.rst
  doc/releases/changelog-dev.md
  pennylane/workflow/qnode.py
  tests/test_qnode.py
Labels: merge-ready :heavy_check_mark:

#6832 Remove input arg `control wires` of `MultiControlledX`
  doc/development/deprecations.rst
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/controlled_ops.py
  tests/ops/qubit/test_non_parametric_ops.py
Labels: merge-ready :heavy_check_mark:

#6807 `qml.execute` no longer accepts `mcm_config` argument
  doc/development/deprecations.rst
  doc/releases/changelog-dev.md
  pennylane/workflow/_capture_qnode.py
  pennylane/workflow/execution.py
  pennylane/workflow/qnode.py
  tests/capture/test_capture_qnode.py
  tests/ops/functions/test_matrix.py
  tests/ops/op_math/test_exp.py
  tests/test_compiler.py
  tests/test_qnode.py
  tests/transforms/core/test_transform_dispatcher.py
  tests/workflow/interfaces/execute/test_execute.py
Labels: merge-ready :heavy_check_mark:

#6840 Deprecate `QubitUnitary` as a valid input to `ControlledQubitUnitary`
  doc/development/deprecations.rst
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/controlled.py
  pennylane/ops/op_math/controlled_ops.py
  tests/ops/op_math/test_controlled_ops.py
Labels: deprecation :wastebasket:, ci:run-full-test-suite

#6841 Deprecate `MeasurementProcess.return_type` and `ObservableReturnTypes`
  pennylane/circuit_graph.py
  pennylane/devices/_legacy_device.py
  pennylane/devices/_qubit_device.py
  pennylane/devices/default_mixed.py
  pennylane/drawer/tape_text.py
  pennylane/gradients/parameter_shift.py
  pennylane/measurements/classical_shadow.py
  pennylane/measurements/counts.py
  pennylane/measurements/expval.py
  pennylane/measurements/measurements.py
  pennylane/measurements/mid_measure.py
  pennylane/measurements/mutual_info.py
  pennylane/measurements/probs.py
  pennylane/measurements/purity.py
  pennylane/measurements/sample.py
  pennylane/measurements/state.py
  pennylane/measurements/var.py
  pennylane/measurements/vn_entropy.py
  pennylane/transforms/sign_expand/sign_expand.py
  pennylane/workflow/interfaces/jax_jit.py
  tests/circuit_graph/test_circuit_graph_hash.py
  tests/devices/test_qubit_device.py
  tests/devices/test_qutrit_device.py
  tests/measurements/test_classical_shadow.py
  tests/measurements/test_counts.py
  tests/measurements/test_expval.py
  tests/measurements/test_measurements.py
  tests/measurements/test_measurements_legacy.py
  tests/measurements/test_mutual_info.py
  tests/measurements/test_probs.py
  tests/measurements/test_purity_measurement.py
  tests/measurements/test_sample.py
  tests/measurements/test_state.py
  tests/measurements/test_var.py
  tests/measurements/test_vn_entropy.py
  tests/ops/op_math/test_condition.py
  tests/tape/test_qscript.py
  tests/tape/test_tape.py
  tests/test_return_types.py
  tests/test_return_types_legacy.py
  tests/test_return_types_qnode.py
  tests/transforms/test_add_noise.py
  tests/transforms/test_insert_ops.py
  tests/transforms/test_mitigate.py
  tests/transforms/test_qcut.py
  tests/workflow/interfaces/execute/test_jax_jit.py
Labels: deprecation :wastebasket:

#6906 Fix return type
  doc/development/deprecations.rst
  doc/releases/changelog-dev.md
  pennylane/noise/conditionals.py
Labels: bug :bug:, gpu, ci:run-full-test-suite, urgent

#6908 Pin `pyzx==0.8.0` in CI
  .github/workflows/interface-unit-tests.yml
Labels: urgent

#6895 Clean up `MultiControlledX` docstring
  pennylane/ops/op_math/controlled_ops.py
Labels: documentation :blue_book:

#6839 Deprecate `control_wires` in `ControlledQubitUnitary`
  doc/development/deprecations.rst
  doc/releases/changelog-dev.md
  pennylane/devices/tests/test_gates.py
  pennylane/devices/tests/test_templates.py
  pennylane/gradients/metric_tensor.py
  pennylane/ops/functions/bind_new_parameters.py
  pennylane/ops/op_math/controlled.py
  pennylane/ops/op_math/controlled_ops.py
  pennylane/ops/qubit/matrix_ops.py
  tests/devices/default_tensor/test_default_tensor.py
  tests/ops/functions/conftest.py
  tests/ops/functions/test_bind_new_parameters.py
  tests/ops/functions/test_equal.py
  tests/ops/op_math/test_controlled.py
  tests/ops/op_math/test_controlled_decompositions.py
  tests/ops/op_math/test_controlled_ops.py
  tests/ops/qubit/test_attributes.py
  tests/ops/qubit/test_matrix_ops.py
  tests/ops/qubit/test_non_parametric_ops.py
  tests/ops/qubit/test_parametric_ops.py
  tests/transforms/test_optimization/test_commute_controlled.py
  tests/transforms/test_qmc_transform.py
Labels: deprecation :wastebasket:
