Repository PennyLaneAI/pennylane, pull requests merged in 2025-06, with the labels that each got.

#7626 No more NP2 `xfail`'s for `OpenFermion` tests
  doc/releases/changelog-dev.md
  tests/qchem/openfermion_pyscf_tests/conftest.py
  tests/qchem/openfermion_pyscf_tests/test_dipole_of.py
  tests/qchem/openfermion_pyscf_tests/test_meanfield.py
  tests/qchem/openfermion_pyscf_tests/test_molecular_dipole.py
  tests/qchem/openfermion_pyscf_tests/test_molecular_hamiltonian.py
Labels: tests :test_tube:, qchem :atom_symbol:, urgent

#7399 Update the `ResourceOperator` class in labs
  doc/releases/changelog-dev.md
  pennylane/labs/resource_estimation/__init__.py
  pennylane/labs/resource_estimation/resource_operator.py
  pennylane/labs/resource_estimation/resources_base.py
  pennylane/labs/tests/resource_estimation/test_resource_operator.py
Labels: review-ready :ok_hand:

#7650 Restrict `labs` dependencies to the functions that introduce them
  doc/releases/changelog-dev.md
  pennylane/labs/dla/variational_kak.py
  pennylane/labs/intermediate_reps/rowcol.py
  pennylane/labs/vibrational/christiansen_utils.py
  pennylane/labs/zxopt/basic_optimization.py
  pennylane/labs/zxopt/full_optimize.py
  pennylane/labs/zxopt/full_reduce.py
  pennylane/labs/zxopt/todd.py
  pennylane/labs/zxopt/util.py
Labels: labs :scientist:

#7674 Add missing lightning devices to program capture docs
  doc/news/program_capture_sharp_bits.rst
  doc/releases/changelog-dev.md
Labels: documentation :blue_book:

#7691 MCM-TT documentation update
  doc/introduction/dynamic_quantum_circuits.rst
  doc/releases/changelog-dev.md
Labels: documentation :blue_book:

#7345 Fix trainability of classical preprocessing in transform programs
  doc/releases/changelog-dev.md
  pennylane/transforms/core/transform_program.py
  tests/devices/test_preprocess.py
  tests/gradients/core/test_metric_tensor.py
  tests/gradients/parameter_shift/test_parameter_shift.py
Labels: review-ready :ok_hand:

#7388 [Feature Branch] Upgrading the resource estimation capabilities in Labs
  doc/releases/changelog-dev.md
  pennylane/labs/resource_estimation/__init__.py
  pennylane/labs/resource_estimation/ops/__init__.py
  pennylane/labs/resource_estimation/ops/identity.py
  pennylane/labs/resource_estimation/ops/op_math/__init__.py
  pennylane/labs/resource_estimation/ops/op_math/controlled_ops.py
  pennylane/labs/resource_estimation/ops/op_math/symbolic.py
  pennylane/labs/resource_estimation/ops/qubit/__init__.py
  pennylane/labs/resource_estimation/ops/qubit/non_parametric_ops.py
  pennylane/labs/resource_estimation/ops/qubit/parametric_ops_multi_qubit.py
  pennylane/labs/resource_estimation/ops/qubit/parametric_ops_single_qubit.py
  pennylane/labs/resource_estimation/ops/qubit/qchem_ops.py
  pennylane/labs/resource_estimation/qubit_manager.py
  pennylane/labs/resource_estimation/resource_container.py
  pennylane/labs/resource_estimation/resource_mapping.py
  pennylane/labs/resource_estimation/resource_operator.py
  pennylane/labs/resource_estimation/resource_tracking.py
  pennylane/labs/resource_estimation/resources_base.py
  pennylane/labs/resource_estimation/templates/__init__.py
  pennylane/labs/resource_estimation/templates/stateprep.py
  pennylane/labs/resource_estimation/templates/subroutines.py
  pennylane/labs/resource_estimation/templates/trotter.py
  pennylane/labs/tests/resource_estimation/ops/op_math/test_controlled_ops.py
  pennylane/labs/tests/resource_estimation/ops/op_math/test_symbolic.py
  pennylane/labs/tests/resource_estimation/ops/op_math/test_symbolic_ops.py
  pennylane/labs/tests/resource_estimation/ops/qubit/test_non_parametric_ops.py
  pennylane/labs/tests/resource_estimation/ops/qubit/test_parametric_ops_multi_qubit.py
  pennylane/labs/tests/resource_estimation/ops/qubit/test_parametric_ops_single_qubit.py
  pennylane/labs/tests/resource_estimation/ops/qubit/test_qchem_ops.py
  pennylane/labs/tests/resource_estimation/ops/test_identity.py
  pennylane/labs/tests/resource_estimation/templates/test_resource_basisrotation.py
  pennylane/labs/tests/resource_estimation/templates/test_resource_prepselprep.py
  pennylane/labs/tests/resource_estimation/templates/test_resource_qpe.py
  pennylane/labs/tests/resource_estimation/templates/test_resource_qubitization.py
  pennylane/labs/tests/resource_estimation/templates/test_resource_reflection.py
  pennylane/labs/tests/resource_estimation/templates/test_resource_select.py
  pennylane/labs/tests/resource_estimation/templates/test_resource_stateprep.py
  pennylane/labs/tests/resource_estimation/templates/test_resource_trotter.py
  pennylane/labs/tests/resource_estimation/templates/test_subroutines.py
  pennylane/labs/tests/resource_estimation/test_qubit_manager.py
  pennylane/labs/tests/resource_estimation/test_resource_container.py
  pennylane/labs/tests/resource_estimation/test_resource_mapping.py
  pennylane/labs/tests/resource_estimation/test_resource_operator.py
  pennylane/labs/tests/resource_estimation/test_resource_tracking.py
  pennylane/labs/tests/resource_estimation/test_resources_base.py
Labels: WIP :construction:, do not merge :warning:

#7749 Create prototype THC optimization using optax and jax
  pennylane/labs/resource_estimation/templates/optimization.py
  pennylane/labs/resource_estimation/templates/subroutines.py
  pennylane/labs/resource_estimation/templates/test.py
Labels: do not merge :warning:
