Repository PennyLaneAI/pennylane, pull requests merged in 2025-05, with the labels that each got.

#7369 Raising a warning if latest JAX is installed
  .github/workflows/docs.yml
  .github/workflows/interface-dependency-versions.yml
  doc/development/release_notes.md
  doc/releases/changelog-0.41.0.md
  doc/releases/changelog-0.41.1.md
  pennylane/capture/capture_operators.py
  pennylane/qnn/__init__.py
Labels: urgent

#7384 [BUG] `default.mixed` np to math
  doc/releases/changelog-dev.md
  pennylane/devices/default_mixed.py
  pennylane/devices/qubit_mixed/apply_operation.py
  pennylane/devices/qubit_mixed/einsum_manpulation.py
  pennylane/devices/qubit_mixed/initialize_state.py
  pennylane/devices/qubit_mixed/sampling.py
  pennylane/measurements/probs.py
  tests/devices/test_default_mixed.py
Labels: bug :bug:, review-ready :ok_hand:

#7332 fix(openfermion): Use identity qubit map when none is provided
  doc/releases/changelog-dev.md
  pennylane/qchem/convert.py
  tests/qchem/openfermion_pyscf_tests/test_convert_openfermion.py
Labels: external

#7397 Potential fix for code scanning alert no. 204: Code injection
  .github/workflows/trigger_benchmarks.yml
Labels: bug :bug:, CI :wrench:

#7417 Adding install build to wheel build workflows
  doc/releases/changelog-dev.md
  pyproject.toml
  requirements-ci.txt
  requirements-dev.txt
Labels: gpu, ci:run-full-test-suite

#7427 Fix IsingXY doc `\theta` -> `\phi`
  doc/releases/changelog-dev.md
  pennylane/ops/qubit/parametric_ops_multi_qubit.py
Labels: merge-ready :heavy_check_mark:, review-ready :ok_hand:

#7393 Add `qml.to_openqasm` transform
  doc/releases/changelog-dev.md
  pennylane/__init__.py
  pennylane/io/__init__.py
  pennylane/io/io.py
  tests/io/test_io.py
Labels: merge-ready :heavy_check_mark:

#7370 Improved decomposition of `DiagonalQubitUnitary`
  doc/releases/changelog-dev.md
  pennylane/ops/qubit/matrix_ops.py
  tests/ops/qubit/test_matrix_ops.py
Labels: review-ready :ok_hand:

#7166 Add new decomposition to `PCPhase`
  doc/releases/changelog-dev.md
  pennylane/math/decomp_int_to_powers_of_two.md
  pennylane/math/decomposition.py
  pennylane/operation.py
  pennylane/ops/qubit/parametric_ops_multi_qubit.py
  pennylane/ops/qubit/pcphase_decomposition.md
  tests/math/test_decomposition_math.py
  tests/ops/qubit/test_parametric_ops.py
Labels: review-ready :ok_hand:

#7389 Support for weighted gates in graph decomposition algorithm
  doc/releases/changelog-dev.md
  pennylane/decomposition/decomposition_graph.py
  pennylane/decomposition/resources.py
  pennylane/transforms/decompose.py
  tests/decomposition/conftest.py
  tests/decomposition/test_controlled_decomposition.py
  tests/decomposition/test_decomposition_graph.py
  tests/decomposition/test_decomposition_rule.py
  tests/decomposition/test_resources.py
  tests/transforms/test_decompose_transform.py
  tests/transforms/test_decompose_transform_graph.py
Labels: merge-ready :heavy_check_mark:

#7358 Make the pipeline compatible with shots decoupling
  doc/releases/changelog-dev.md
  pennylane/workflow/_setup_transform_program.py
  pennylane/workflow/construct_execution_config.py
  pennylane/workflow/execution.py
  pennylane/workflow/resolution.py
  tests/gradients/core/test_hadamard_gradient.py
  tests/gradients/core/test_metric_tensor.py
  tests/transforms/test_set_shots.py
  tests/workflow/interfaces/run/test_autograd_run.py
  tests/workflow/interfaces/run/test_jax_jit_run.py
  tests/workflow/interfaces/run/test_jax_run.py
  tests/workflow/interfaces/run/test_tensorflow_autograph_run.py
  tests/workflow/interfaces/run/test_tensorflow_run.py
  tests/workflow/interfaces/run/test_torch_run.py
  tests/workflow/test_resolve_execution_config.py
  tests/workflow/test_setup_transform_program.py
Labels: review-ready :ok_hand:, do not merge :warning:

#7529 Pin `mitiq!=0.45.0`
  .github/workflows/interface-unit-tests.yml
  tests/test_compiler.py
Labels: urgent

#7394 Add ROWCOL CNOT routing algorithm
  .github/workflows/tests-labs.yml
  doc/releases/changelog-dev.md
  doc/requirements.txt
  pennylane/labs/.pylintrc
  pennylane/labs/intermediate_reps/__init__.py
  pennylane/labs/intermediate_reps/rowcol.py
  pennylane/labs/tests/intermediate_reps/test_rowcol.py
Labels: labs :scientist:
