Repository PennyLaneAI/pennylane, pull requests merged in 2025-02, with the labels that each got.

#6910 Fix return type call in noise conditionals
  doc/releases/changelog-dev.md
  pennylane/noise/conditionals.py
  tests/noise/test_conditionals.py
Labels: urgent

#6880 Update `interface-unit-tests.yml` handling of `pytest` warnings
  .github/workflows/interface-unit-tests.yml
Labels: gpu, ci:run-full-test-suite

#6863 `StatePrep` accepts sparse matrices as input
  doc/releases/changelog-dev.md
  pennylane/ops/qubit/state_preparation.py
  tests/ops/qubit/test_state_prep.py
Labels: enhancement :sparkles:, review-ready :ok_hand:

#6927 Update GPU workflow to use the new self-hosted GPU runner infrastructure
  .github/workflows/tests-gpu.yml
Labels: gpu

#6926 Fix double QubitUnitary bug from Catalyst
  doc/releases/changelog-dev.md
  pennylane/ops/op_math/controlled.py
  tests/ops/op_math/test_controlled.py
Labels: bug :bug:

#6940 Fixing dismatch between dense `matrix()` and sparse repr `sparse_matrix()` of GlobalPhase
  doc/releases/changelog-dev.md
  pennylane/math/matrix_manipulation.py
  pennylane/ops/identity.py
  tests/ops/qubit/test_parametric_ops.py
Labels: merge-ready :heavy_check_mark:

#6889 `QubitUnitary` accepts sparse matrices as inputs
  doc/releases/changelog-dev.md
  pennylane/math/single_dispatch.py
  pennylane/math/utils.py
  pennylane/ops/op_math/decompositions/single_qubit_unitary.py
  pennylane/ops/op_math/decompositions/two_qubit_unitary.py
  pennylane/ops/qubit/matrix_ops.py
  pennylane/ops/qubit/parametric_ops_single_qubit.py
  pennylane/ops/qubit/state_preparation.py
  tests/ops/qubit/test_matrix_ops.py
  tests/ops/qubit/test_state_prep.py
Labels: enhancement :sparkles:, review-ready :ok_hand:

#6881 Multi-level dynamic decompositions
  doc/releases/changelog-dev.md
  pennylane/operation.py
  pennylane/transforms/decompose.py
  tests/capture/transforms/test_capture_dynamic_decompositions.py
Labels: merge-ready :heavy_check_mark:

#7015 Fix `qml.math.get_interface` for `scipy` input
  doc/releases/changelog-dev.md
  pennylane/math/interface_utils.py
  pennylane/math/multi_dispatch.py
  pennylane/math/single_dispatch.py
  tests/math/test_functions.py
Labels: bug :bug:

#6854 Bump `rng_salt` version to `v0.40.0`
  doc/releases/changelog-dev.md
  tests/capture/autograph/test_autograph.py
  tests/devices/default_qubit/test_default_qubit.py
  tests/devices/qubit/test_sampling.py
  tests/devices/qutrit_mixed/test_qutrit_mixed_sampling.py
  tests/gradients/core/test_pulse_gradient.py
  tests/gradients/finite_diff/test_spsa_gradient_shot_vec.py
  tests/gradients/parameter_shift/test_parameter_shift_shot_vec.py
  tests/measurements/test_expval.py
  tests/pytest.ini
  tests/templates/test_subroutines/test_qdrift.py
  tests/transforms/test_broadcast_expand.py
  tests/workflow/interfaces/execute/test_torch.py
  tests/workflow/interfaces/qnode/test_jax_jit_qnode.py
  tests/workflow/interfaces/qnode/test_jax_qnode.py
Labels: WIP :construction:, do not merge :warning:
